### ISSUE TITLE
énergie grise

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#100]
Bonjour. Je souhaite savoir si le simulateur intègre l'impact de l'énergie grise.
Les véhicules motorisés et le logement en génèrent une quantité qui passe inaperçue dans les calculateurs.

**Comment by Benjamin-Boisserie-ABC** [comment]
Voiture : oui autant que possible. la construction de la voiture est pris en compte, la construction des routes rentre en partie dans les services publiques.
Logement : la question de l'amortissement est en réflexion
