### ISSUE TITLE
Km en voiture - séparer quotidien et départ en vacances

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#103]
Il faudrait pouvoir distinguer le nb de km réalisé au quotidien (travail, courses,...) et ceux réalisés pendant les vacances (départ en famille).
De même, le questionnaire ne tient pas compte du lieu d'habitation et des capacités de déplacement autre que la voiture. Pour être complet, il aurait également été intéressant de s'intéresser aux trajets à pied ou en vélo.

**Comment by Benjamin-Boisserie-ABC** [comment]
La différenciation des trajets entre boulot/vacances/etc. est fait sur le volet action. Ce volet est en cours d'amélioration. 
Concernant les trajets en vélo/à pied voir #74 
Prise en compte de la remarque sur la capacité à agir en fonction du lieu d'habitation
