### ISSUE TITLE
Individuel ou par foyer 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#104]
Bonjour
Bravo pour ce Test, j'attendais quelque chose de similaire depuis longtemps. J'ai juste deux remarques qui pourraient améliorer le test.
1/ les questions portent parfois sur une consommation  individuelle (heures de bus, heures d'avion) et parfois sur une consommation  collective (électricité). Peur être faudrait il faire le test par foyer et diviser par le nombre de membre du foyer ?
2/ ensuite j'aurai rêvé d'une appli permettant de compenser ses dépenses carbones. Par exemple je dois prendre l'avion  pendant 4 heures, que dois je faire pour compenser cette dépense (ex ne pas manger de viande pendant x mois)... 
En tous cas merci pour ce travail qui va dans le bon sens et va permettre de  sensibiliser la population.
Bien cordialement 
Marion

**Comment by laem** [comment]
Voir #113 

>ensuite j'aurai rêvé d'une appli permettant de compenser ses dépenses carbones. Par exemple je dois prendre l'avion pendant 4 heures, que dois je faire pour compenser cette dépense (ex ne pas manger de viande pendant x mois)...

Je pense que https://futur.eco, site collaboratif que je développe à titre personnel indépendamment d'Ecolab, répond à votre question :)
