### ISSUE TITLE
6t seulement au lieu de 10t avec MicMac

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#108]
Bonjour, 
Je suis assez étonné du résultat final, je me retrouve à 6t contre 9-11t avec d'autres calculateurs (dont MicMac) ; 
Je ne saurai dire exactement où mais cela me semble assez sous-estimer l'empreinte carbone

**Comment by laem** [comment]
Étonnant ! Peut-être que la différence vient d'une forte consommation d'avion, qui était surestimé dans MicMac ?

En l'absence d'informations en plus, on ne va pas pouvoir aller plus loin, donc je ferme.
