### ISSUE TITLE
Impact véhicule électrique

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#110]
Je suis étonné de l'impact du VE. Il semble d'autant plus élevé que le véhicule est récent. J'imagine que c'est parce que le coût CO2 de la fabrication (notamment batterie) est amorti sur les premières années, mais c'est un parti prix qui ne va pas inciter les gens à s'équiper, d'autant que les offres sur le marché de l'occasion sont encore assez peu nombreuses... Pourquoi ne pas lisser cet impact sur l'ensemble de la durée de vie du véhicule, et retenir par ex un taux de 55gCO2/km (voir http://www.avere-france.org/Site/Article/?article_id=7831) quel que soit l'âge du véhicule ?

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet un véhicule est plus impactant à la construction mais est en revanche moins impactant au km (en France). Au final trancher entre véhicule thermique et électrique nécessite de questionner l'usage qui est fait du véhicule. Plus d'infos ici : 

https://www.ademe.fr/elaboration-selon-principes-acv-bilans-energetiques-emissions-gaz-a-effet-serre-autres-impacts-environnementaux 

Concernant l'amortissement, la manière d'amortir est à reprendre.
