### ISSUE TITLE
PROVENANCE DE NOTRE NOURITURE

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#114]
bonjour,
je suis vegetarien mais je n’achète que des produits locaux ou bio, cela doit modifier de manière significative le bilan ?

**Comment by Benjamin-Boisserie-ABC** [comment]
L'impact GES des produits locaux ne se limite malheureusement pas à un calcul de distance. Il faut prendre en compte les taux de remplissage, les déplacements des clients, les véhicules utilisés etc. 
Cette question est néanmoins en réflexion. Voir #71
