### ISSUE TITLE
le travail

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#115]
bonjour,
 doit on prendre en compte notre travail, j'utilise ma voiture perso pour mon travail ça augment le nombre de kilomètre...

**Comment by Benjamin-Boisserie-ABC** [comment]
Il ne faut pas considérer les aspects professionnels quand on répond au questionnaire. Seulement ce qui relève de ces choix personnels. Utiliser sa voiture perso dans le cadre du travail relève de la compétence de l'entreprise et donc de l'aspect professionnel
