### ISSUE TITLE
Régime alimentaire 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#116]
Bonjour
Merci pour ce simulateur.
Une remarque : les propositions de reponses pour le régime alimentaire ne sont pas satisfaisantes. Je suis flexitarienne, (mange 2 a 3 fois de la viande blanche uniquement, jamais de boeuf ni agneau),légumes bio et de saison. Du coup, aucune réponse ne le correspond. Avec le régime vie vegetarien, mon bilan est a 6 tonnes. Avec de la viande une fois par jour, mon bilan est a8 tonnes. Je me situe donc entre les 2. merci ! Écologiquement votre, marie odile

**Comment by Benjamin-Boisserie-ABC** [comment]
Problème résolu avec la version actuelle du modèle de calcul du poste alimentation
