### ISSUE TITLE
Version adaptée aux enfants

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#117]
Bonjour Super outil !!
Je travaille sur ce thème avec des élèves de collège. Pourriez vous envisager une version adaptée aux adolescents ?
C'est quand même eux l'avenir ;-)

**Comment by laem** [comment]
Excellente question ! Vu le public, il faudrait le faire dans le cadre d'une collaboration avec un collège. Construire un jeu de question simplifiées, tester, itérer, etc. :) 
Qui veut se lancer ?

**Comment by Benjamin-Boisserie-ABC** [comment]
L'ABC travail dans le cadre d'un projet européen sur la sensibilisation/la formation des plus jeunes aux enjeux de transition. Plus d'infos ici : https://www.associationbilancarbone.fr/enseignement-secondaire-projet-etablissement-bas-carbone-pebc/
