### ISSUE TITLE
Calcul personnel vs. foyer

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#118]
Bonjour,
Je trouve cet outil réellement intéressant, néanmoins il ne semble être orienté que sur une seule personne et non sur l'ensemble du foyer qui peut contenir plusieurs véhicules par exemple et dont les besoins peuvent varier en fonction des âges. De même, il serait intéressant de pouvoir différencier l'empreinte professionnelle vs. personnelle (transports).

**Comment by laem** [comment]
Je ferme au profit de #113
