### ISSUE TITLE
Véhicule électrique et facture EDF

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#119]
Bonjour et bravo pour votre outil très pédagogique !

Pour un véhicule électrique rechargé à domicile, le nombre de kilomètres annuel n'est-il pas déjà pris en compte dans la consommation électrique du ménage ?

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, il y a double comptage entre le facteur d'émission de l'empreinte au km d'un voiture élec et la consommation d'élec (quand le véhicule est rechargé à la maison). Néanmoins, ce n'est pas préjudiciable pour le calcul de l'empreinte carbone étant donné que l'électricité française a un très faible poids carbone.
**Information sur le double comptage élec à intégrer dans la F.A.Q**
