### ISSUE TITLE
Regrouper la sélection du matériel numérique

### ISSUE THREAD

**Issue by laem** [betagouv/ecolab-data#12]
Appareil photo, vidéoproj, téléphone, etc. 

On pourrait proposer une liste de vignettes illustrées, à l'utilisateur de cocher ce dont il dispose, pour poser moins de questions. 

On pourrait même permettre l'ajout de plusieurs ordis, plusieurs téléphones, etc. Mais à voir si c'est pertinent en pratique. Quand on a plusieurs téléphones par personne, c'est souvent un pro et un perso, ou un vieux (donc période de simulation passée) et un récent. Si on a deux ordinateurs, alors on a souvent une tour + un portable. Etc.
On pourrait déterminer par contre que certains appareils peuvent être doublés : télé 1, télé 2

**Comment by martinregner** [comment]
J'avais bien aimé dans le questionnaire de François Laugier, il demande de compter : 
- "Gros électroménager (machine à laver, four ...)
- Petits électroménager (bouilloire, grille pain, fer à repasser ...)
- Ecrans (télé, smartphone, tablette)"

Ca permet de mieux se projeter dans le fait que tous les équipements qui nous entoure.... et ça simplifie la saisie pour le numérique.
Faut juste trouver le bon FE ^^

On pourrait d'ailleurs inclure le gros électroménager de la même manière.

Qu'en penses-tu ?

**Comment by laem** [comment]
Je pense qu'avec une interface intuitive (grosses vignettes à cocher, icônes) on peut même proposer les ~10 matériels les plus courants pour chaque catégorie, ou au moins ceux pour lesquels on a le facteur d'émissions :)

**Comment by laem** [comment]
Une fois regroupée, ajouter : 
- enceinte bluetooth
- robot aspirateur 😄 
- ...
