### ISSUE TITLE
Évaluation internet

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#123]
Dans la synthèse de l'impact de l'utilisation d'internet, vous utilisez l'unité heures par jour, alors qu'il s'agit de gCo2e/j

**Comment by somusset** [comment]
Dans le même registre, il faudrait mieux expliquer le calcul réalisé ici. Je n'ai aucune expérience en calcul d'empreinte carbone, du coup voir que le calcul suivant est affiché : 
0.01* 1 h/jour = 0.01/j = 3.65 h/j
*365
est assez déroutant... il s'agit peut-être d'une erreur d'affichage notamment pour la deuxième ligne mais il faudrait ajouter les unités, et puis une explication de l'origine des différents facteurs.

**Comment by laem** [comment]
Merci pour les remarques. L'unité a déjà été corrigée dans  #130 , mais pas encore poussée en production (vacances 😅 ).

Au sujet du calcul, il y a deux problèmes (au moins) : 
- l'affichage de la formule, qui devrait s'améliorer bientôt avec une mise à jour de publicodes
- le 0.01 : vous avez bien raison, il aurait du être sourcé.
