### ISSUE TITLE
Détailler questions alimentation

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#124]
Bonjour,
serait-il possible d'affiner la section sur l'alimentation : le régime flexitarien n'est pas représenté alors qu'il concerne de plus en plus de monde. Il n'y a rien non plus sur l'achat de produits bio et fruits et légumes exclusivement de saison/locaux/produits français. Ou alors il faut cocher qu'on mange végétalien... Ça manque un peu de nuance. Merci.

**Comment by Benjamin-Boisserie-ABC** [comment]
La version actuelle du volet alimentation fait plus de différence entre les repas.
Concernant les autres aspect de l'alimentation saison/locaux/etc. voir #71
