### ISSUE TITLE
Chauffage urbain

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#126]
Le chauffage urbain manque à l'appel...

**Comment by laem** [comment]
C'est noté !

**Comment by Spadice** [comment]
En fouillant  dans la base carbone j’étais aussi tombé sur le site du cerema, qui dresse une liste des émissions de CO2 d'une grosse liste de réseau de chaleur et de froid. 
Cf : http://reseaux-chaleur.cerema.fr/contenus-co2-des-reseaux-de-chaleur-et-de-froid-arrete-du-11-avril-2018

Et qui font aussi des rapport de synthèse plutôt sympathiques :
https://www.fedene.fr/wp-content/uploads/sites/2/2019/12/SNCU-Rapport-Global-2019-Restitution-enquete-r%C3%A9seaux.pdf

Qui conclu à : 
- 0,116 kgCO2/kWh pour les réseau chaud en moyenne
- 0,010 kgCO2/kWh pour les réseau froid

**Comment by laem** [comment]
Autre remarque : 

> Bonjour! J'habite Grenoble et nous avons le plus gros chauffage urbain de France derrière Paris, il semble que ce mode de chauffage ne soit pas intégré dans le calcul... Du coup j'ai répondu "non" aux questions me demandant si j'étais chauffé au charbon ou au fioul, mais je suppose que du coup j'ai zéro en chauffage, ce qui n'est à priori pas exact, sauf à considérer que mes ordures me chauffent (en vrai ils utilisent aussi 15% de charbon... :(

**Comment by Benjamin-Boisserie-ABC** [comment]
Question répondue sur la F.A.Q
éIntégrer les réseaux urbains nécessiterait de répertorier l’ensemble des réseaux de chaleur en France et il en existe plus de 750… De plus, la donnée (i.e. le facteur d’émission du réseau) n’est pas toujours fiable et contrôlable et est sujette à de fortes évolutions au cours du temps, en fonction des procédés utilisés pour faire fonctionner le réseau de chaleur (chaleur récupérée depuis les incinérateurs, énergie renouvelable mais aussi souvent fuel ou gaz naturel). 
Nous n’avons pas fait le choix non plus de considérer un réseau de chaleur « moyen » étant donné qu’en fonction de la part d’hydrocarbure utilisée dans leur fonctionnement, leur impact en termes de gaz à effet de serre peut varier très fortement.

Néanmoins prise en compte de la remarque pour futur intégration dans l'outil !

**Comment by estellecomment** [comment]
J'ai du chauffage urbain, et j'ai répondu "gaz", au hasard. Ca aiderait d'avoir même un vague ordre de grandeur, ou une suggestion de quoi répondre, même si elle est inexacte.

**Comment by laem** [comment]
Merci pour le commentaire :) 

Oui on n'a pas lancé les travaux encore mais c'est bien prévu :) https://github.com/datagir/nosgestesclimat/pull/1328
