### ISSUE TITLE
sujet alimentation - transports

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#129]
Je trouve que les propositione ne sont pas assez complètes, notamment sur les produits locaux et de saisons où il n'y a pas assez d'options. Pour le transport il faudrait peut être voir pour des ratios? Pouvoir valoriser les km à vélo ou à pieds, ainsi que le covoiturage

**Comment by Benjamin-Boisserie-ABC** [comment]
L'évaluation de l'impact GES des produits locaux ne se résume pas à un simple calcul de distance. En fonction des taux de remplissage, du déplacement des clients, des véhicules utilisés l'avantage des produits locaux peut se retrouver "annuler". 
Néanmoins nous travaillons à l'amélioration du volet alimentation afin de prendre en compte les caractéristiques locales/de saison/ etc.

Concernant les km à vélo ou à pied, voir #74
