### ISSUE TITLE
conception du questionnaire

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#136]
Bonjour, la démarche est bienvenue, par contre je trouve qu'elle n'est pas assez détaillée et expliquée: par exemple, sur la maison, le nombre de m2 me semble moins important que la façon dont elle est construite et aménagée (parpaings, briques mono-murs ou paille n'ont rien d'équivalent, idem en termes d'isolation, bioclimatique ou pas, etc.); pour les transports, pourquoi ne jamais mentionner les bateaux, toujours oubliés?; etc. Quant aux explications, il serait important me semble t-il de faire prendre conscience justement, de la part incompressible de notre empreinte du simple fait que nous sommes piégés dans les flux du commerce international qui fait que faire ses courses en supermarché, même en bio, fait bondir notre empreinte, comme nos placements financiers dans les banques classiques, ou la privatisation progressive des services publics pour en faire des marchés lucratifs pour une poignée d'humains au détriment de tous les autres. Bref, si avec tous mes efforts je ne peux jamais atteindre les 2 tonnes maximales nécessaires, cela tient à des choix politico-économiques où nous avons tous aussi notre part de responsabilité et de champs d'action...Tant que nos sociétés se mettront au service de l"'économie" (en fait des gros bonnets des multinationales et de la finance internationale), nous resterons dans l'impasse et condamnerons nos enfants.

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat est un calculateur grand public. Renseigner des m2 plutôt que la manière dont a été construit le logement est bien plus accessible au grand public. Même si en effet des logements éco-construits on moins d'impact que des construction classiques. 
Le mode de transport par bateau est un mode de transport très peu utilisé de manière récurrente.
Quand aux explications pour réduire son empreinte carbone et faire prendre conscience des enjeux, le volet passage à l'action est en cours de développement. Des actions sont d'ailleurs prévues sur le choix des banques, etc.
