### ISSUE TITLE
UI - Reprendre les couleurs des barres pour chaque catégorie

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-data#14]
Pour plus de lisibilité, la catégorie au dessus de la question pourrait être surligné de la même couleur que la barre qui est dans le graphe en dessous.
J'aimais bien cette idée dans MicMac v2, ça permet de suivre plus facilement je trouve

**Comment by laem** [comment]
Capucine m'a fait la même remarque, c'est corrigé ✔️
