### ISSUE TITLE
alimentation

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#144]
Bonjour, 
je suis végétarienne, bio, local et je n'ai pas trouvé de case correspondante. C'était soit végétarien tout court, soit végétalien. 
Egalement, il n'y a pas de questions sur les produits transformés : je n'achète jamais de galette végétale toute faite par exemple. Merci !

**Comment by laem** [comment]
Voir #23 
Je ferme car c'est un problème connu et documenté. Merci !
