### ISSUE TITLE
Questions sur la voiture alors qu'on n'en possède pas

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#152]
Dans la section voiture, si on répond non à la question 'avez-vous une voiture ?', il faudrait avoir une option de "passer" sur les questions concernant l'utilisation de la voiture :)

**Comment by laem** [comment]
Il se passe quelque chose que je ne comprends pas, ce n'est pas le premier retour de ce genre. Or, les questions sur la voiture n'apparaissent que si l'on a dit qu'on faisait des km en voiture, peut importe si on en a une ou non. 

Peut-être qu'il faut reformuler les questions pour préciser ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Ils doivent penser que de ne pas avoir de voiture implique de ne pas avoir derrière de question et ce même s'ils ont renseigné des distances parcourues en voiture chaque année. 
Répondre à ça dans la F.A.Q (que l'on peut très bien faire des km en voiture sans en posséder une (covoit, location, etc.) auquel cas on pose des questions sur les caractéristiques de la voiture).
