### ISSUE TITLE
Calcul individuel ou par foyer ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#155]
Bonjour, une remarque : une partie des dépenses concerne le foyer, une autre partie concerne des dépenses individuelles. Donc, pour avoir les dépenses par foyer, il faudrait pouvoir ajouter au moins un ordinateur et un téléphone. Pour le moment, on ne peut avoir ni le calcul exact par foyer, ni le calcul exact par personne, sauf erreur dans la compréhension de votre mode de calcul.

**Comment by laem** [comment]
Bonjour, oui c'est exact. Pour la voiture par exemple, on peut renseigner le nombre de voyageurs. Pour l'ordinateur, on ne peut renseigner le nombre d'utilisateurs. 
Voir #113
