### ISSUE TITLE
c'est un peu de la merde

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#158]
questions biaisé dirigé sans nuances, il se trouve que mon pc n'est pas neuf, que c'est de la recuperation que j'ai la clim que je mange pas de boeuf mais du poulet et de la dinde, que j'ai un velo electrique que j'utilise 1 fois par jour,  bref vous donné des resultat precis avec des données imprécise, à part faire culpabilisé encore ce teste ne sert à rien, basez vous plutot sur des echelles de valeurs, de couleurs révisez votre copie

**Comment by laem** [comment]
Pour la clim : bonne remarque #167 
Pour votre PC : il vous suffit de préciser l'âge du PC. 
Pour la viande : la nouvelle version arrive bientôt, plus personnalisable. 

> que j'ai un velo electrique que j'utilise 1 fois par jour

Bravo. Nous n'avons pas de questions sur le vélo électrique car son empreinte est négligeable par rapport aux autres modes de transport carbonés. Il faudrait peut-être qu'on pose cette question pour montrer l'empreinte faible ?

>  à part faire culpabilisé encore ce teste ne sert à rien

Ce test ne fait que ressortir des faits, certes imprécis, mais les meilleurs actuellement disponibles. 

>  basez vous plutot sur des echelles de valeurs, de couleurs révisez votre copie

N'hésitez pas à faire des propositions plus concrètes, l'outil va beaucoup évoluer.
