### ISSUE TITLE
empreinte numérique

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#159]
Bonjour, je ne comprends pas le calcul pour la partie numérique. En effet  j'ai écouté la présentation de ce simulateur sur France Inter. La personne qui le présentait, expliquait que 1 heure de streaming par jour équivaut à 1 tonne de GES par an. Or on ne retrouve par cela du tout lorsqu'on remplit le questionnaire.

**Comment by laem** [comment]
Votre confusion est légitime. Cette affirmation est fausse, l'ordre de grandeur n'est pas le bon. Il est très difficile d'évaluer précisément l'empreinte du streaming* aujourd'hui, mais vous pouvez retenir pour l'instant les chiffres du simulateur. Le poste streaming est donc bien inférieur à la plupart des autres éléments de notre quotidien en France. Ce qui n'empêche pas de chercher plus de sobriété : pas de 4k, pas de télé géante, etc. 😸
