### ISSUE TITLE
Rubrique Alimentation peu détaillée

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#160]
La rubrique Alimentation pourrait être plus étoffée pour nuancer le score. Il me semble qu'il n'y a pas que le régime végétarien qui peut avoir un impact positif sur l'empreinte carbone : les régimes sans produits laitiers, sans gluten, font consommer des alternatives ; ainsi que la consommation de soja ou non ; les fruits et légumes de saison ; produits locaux, nationaux, internationaux ; les achats de vrac ou sur les marchés (tout ou partie)... Même si ce ne sont pas des sources aussi impactantes que nourrir des animaux d'élevage, ces actions peuvent contribuer à la réduction de l'empreinte individuelle.

**Comment by laem** [comment]
Tout à fait. Voir #23 et le travail en cours #71
