### ISSUE TITLE
Numérique : ajout du fairphone

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#161]
J'utilise un téléphone de 5,5 pouce mais il s'agit d'un fairphone, dont 40% de 8 composants nécessaires à sa fabrication font partie de filières fair et qui a pour véritable avantage de permettre de changer des éléments cassés (batterie, écran, apn...) sans changer de téléphone. L'achat de ce téléphone est clairement militant d'un point de vue environnemental.

**Comment by laem** [comment]
Le Fairphone est intéressant, mais dispose-t-on de mesures de son empreinte climat et est-elle inférieure aux autres ? Les utilisateurs de Fairphone gardent-ils leur téléphone plus longtemps que la moyenne grâce à ces remplacements de composants (à noter, l'écran est remplaçable sur tous les téléphones, mais peut-être à un coût plus important) ?

En cas de prolongement de la durée de vie du téléphone, il est possible de simplement considérer qu'on l'a gardé plus longtemps. On sous-estime alors l'empreinte du remplacement de la batterie ou de l'écran, mais c'est d'un ordre de grandeur inférieur au reste de la simulation.
