### ISSUE TITLE
Numérique et/ou électricité : réglage de la box

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#162]
Il est possible de configurer une box internet pour qu'elles s'éteignent aux heures d'inactivité ou d'absence. Dans le même ordre d'idée : utilliser des multiprises chronométrées ou simplement débrancher les appareils lors des absences prolongées. Idem pour le chauffage électrique.

**Comment by Benjamin-Boisserie-ABC** [comment]
Prise en compte de la remarque pour le volet action
