### ISSUE TITLE
Douche ou bain ou bassine ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#163]
Le type de chauffage peut être combiné avec les litres d'eau consommés par session de lavage (?). D'ailleurs il manque chauffage collectif dans vos propositions.
Bel outil ! Si les lacunes sont comblés, ca devrait être très utile pour tous !

**Comment by Benjamin-Boisserie-ABC** [comment]
Prise en compte de l'impact environnemental au sens large sera traité à très long terme
