### ISSUE TITLE
Quelques remarques

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#165]
— Lorsque l’on indique qu’on n’a pas de voiture, on doit quand même indiquer son type de carburant, etc.
— Impossible d’avoir un smartphone de 0 année. Aussi, le fait de se baser sur l’ancienneté du smartphone n’est pas très précis, je peux très bien avoir juste acheté un nouveau téléphone le mois dernier alors que j’avais utilisé le précédent pendant 6 ans.
—

**Comment by laem** [comment]
> Lorsque l’on indique qu’on n’a pas de voiture, on doit quand même indiquer son type de carburant, etc.

@juliennrf oui c'est voulu. Pour ne pas avoir de questions sur le type de carburant, etc, il faut répondre "0 km" à la question précédente. Sinon, on suppose qu'on s'est posés dans une voiture d'un proche ou de location, dont il faut renseigner (à peu près) les caractéristiques. Peux-tu préciser un peu ton incompréhension ?

**Comment by laem** [comment]
> Impossible d’avoir un smartphone de 0 année. Aussi, le fait de se baser sur l’ancienneté du smartphone n’est pas très précis, je peux très bien avoir juste acheté un nouveau téléphone le mois dernier alors que j’avais utilisé le précédent pendant 6 ans.

Pour le bug, voir #91 
Pour la discussion sur l'âge : je fais une issue spécifique ici pour cette question intéressante 😺  : #168
