### ISSUE TITLE
Ergonomie générale

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#171]
Hello,
Je préfère ici que sur Github car c'est une remarque pour améliorer le design plus qu'un bug précis.

Je trouve l'expérience utilisateur assez désagréable. Il est difficile de s'y retrouver car il y a beaucoup de fenêtres différentes. C'est dommage car les fenêtres sont souvent pauvres en informations à mon goût.

C'est le cas pour la décomposition du bilan carbone moyen accessible au début. Peut-être serait-il plus agréable et plus facile de s'y retrouver avec une arborescence visible sur la page directement.

Ensuite, lors du test, la décomposition du bilan carbone moyen est toujours présente et cela porte légèrement à confusion, on se demande si c'est notre bilan ou pas.

Enfin, au résultat du test, même remarque que pour la décompo du bilan carbone moyen, il y a trop de fenêtres, on s'y perd. Je recommande encore un genre d'arborescence.

Je laisserai par ailleurs des suggestions dans Github.

Bonne journée,
François Laugier

**Comment by Benjamin-Boisserie-ABC** [comment]
Je ne comprends pas bien le problème des fenêtres, il y a toujours eu qu'une seule page d'affichée et l'outil me semble assez sobre en informations
