### ISSUE TITLE
Alimentation bio

### ISSUE THREAD

**Issue by laem** [betagouv/ecolab-data#172]
Il semble qu'on ne puisse pas dire que la nourriture bio soit moins impactante pour le climat. 

Voir les références de cette video quu en parle  https://m.youtube.com/watch?v=8PmM6SUn7Es

Peut-on l'affirmer (dans la FAQ qui apparaîtrait sur le site bientôt) avec une source solide pour trancher la question, au moins jusqu'à nouvel ordre ? 

Cela n'empêche pas que la nourriture bio est souvent associée (dans mon expérience, que je généralise) à moins de consommation de viande et à une nourriture locale de saison.

**Comment by Benjamin-Boisserie-ABC** [comment]
Question traitée par la F.A.Q
