### ISSUE TITLE
depenses en textile

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#173]
J'ai indiqué un montant assez "élevé" de dépenses en textile mais tout ce que j'ai acheté neuf était en fibre biologique et produit en europe. Ce type de textile coûte bien plus cher (la moitié du montant que j'ai indiqué correspondait à 2 culottes menstruelles (80euros)...). Et les 200 euros de total que j'ai indiqué ne sont que des sous vetements... Du coup, je trouve l'évaluation un peu biaisée sans précision derriere. Peut être faudrait il aussi proposer une question sur le nombre de commande par internet et de livraison à domicile (repas, colis, ...). Bon courage et merci.

**Comment by laem** [comment]
Tout à fait. Problème déjà répertorié sur  #44
