### ISSUE TITLE
Unité affichée lors du clic sur une barre d'un poste d'émission

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#174]
Bonjour,
Je viens de m'appercevoir que, lorque je clic sur la barre "alimentation" (par exemple) du calculateur, pour laquelle on m'annonce un résultat annuel de 3,2tCO2e sur l'écran principal, c'est en réalité 3,200 gCO2e qui sont affichés dans la page alimentation.

**Comment by laem** [comment]
En effet, bien vu ! Devrait être corrigé par #71 qui sera publié bientôt :)
