### ISSUE TITLE
Chiffre de la moyenne française

### ISSUE THREAD

**Issue by QuentinBrch** [betagouv/ecolab-data#180]
Lorsqu’on est sur la page principale du calculateur, et que l’on clique sur l’un des postes (alimentation, transport), je trouve qu’il faudrait recontextualiser le chiffre qui apparaît (et repréciser que c’est pour un français moyen seulement). Peut être même ajouter des éléments de comparaison pour rendre ce chiffre plus tangible ?

**Comment by laem** [comment]
Par exemple ici préciser "valeur par défaut" ? 

![image](https://user-images.githubusercontent.com/1177762/91882669-9b624100-ec83-11ea-8a54-9d2de5befb5c.png)

> Peut être même ajouter des éléments de comparaison pour rendre ce chiffre plus tangible ?

Tu as des exemples en tête ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Prise en compte de la remarque en vue d'une amélioration de la navigation dans l'outil
