### ISSUE TITLE
Calculateur version simple et version expert

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#181]
Bonjour, Merci pour le travail ! Cette version est appréciable pour se faire une 1ère idée rapide de son empreinte carbone. Elle est très facile d'emploi, on se laisse guider de question en question, et simplifiée. Personnellement, j'aurai besoin d'accéder à une version plus précise, permettant de comprendre mieux dans le détail certaines sous catégories. Notamment alimentation on peut détailler. Est-ce qu'on ajouterait pas l'option "flexitarien"? + dominante à + de 80% "bio" + "local". Dans transport, je crois qu'il n'est pas demandé si l'on a une moto ou scooter ? J'avais déjà mentionné par email que j'ai des doutes (appuyés par l'avis d'une personne ayant travaillé dans le milieu bancaire et connaissant les sujets s'empreinte carbone) sur le calcul retenu pour les finances classiques. Ce résultat m'apparait sous-estimé. Et cela pourrait pourtant être un fort levier pour déplacer son épargne vers La Nef/Crédit Coop ou parts sociales dans des entreprises responsables, si l'on était + conscient que cela pèse et soutient "le monde d'avant, des énergies fossiles et activités non transparentes, peu éthiques"... J'apprécie la simplicité, le graphique, et l'évolution en temps réel. L'article explicatif est très bien également pour comprendre la notion de budget d'ici 2050 avec les images associées. Je serai contente de discuter davantage pour une version + experte. Dans le tableau Excel d'Avenir Climatique, je trouve intéressant de poser son chiffre et voir tout de suite l'équivalent en CO2e quand on entre dans la précision. Je vous envoie un email distinct. Merci, à bientôt, très cordialement, Marie Paysant-Le Roux

**Comment by laem** [comment]
Pour l'alimentation : nouvelle version imminente permettant de renseigner un régime flexi.
Pour la finance : ce poste sera enlevé, voir #24 

> Dans le tableau Excel d'Avenir Climatique, je trouve intéressant de poser son chiffre et voir tout de suite l'équivalent en CO2e quand on entre dans la précision. 

Nous n'affichons en effet en direct que l'évolution du total, pas de la consommation la plus directement impactée par la question. Voir https://github.com/betagouv/ecolab-climat/issues/81
