### ISSUE TITLE
Transports,  vélo manquants car décarbonés

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#183]
Je suis étonnée que les déplacements decarbonė (vélo,  marche) ne soient pas pris en compte

**Comment by laem** [comment]
Retour intéressant. Ils ne sont pas pris en compte, justement car décarbonés. Je pense qu'il serait intéressant en effet de les intégrer pour bien montrer qu'ils le sont.

**Comment by laem** [comment]
Voir #74
