### ISSUE TITLE
Amortissement du véhicule

### ISSUE THREAD

**Issue by Spadice** [betagouv/ecolab-data#189]
Dans la variante actuelle, je trouve la simulation assez punitive envers ceux qui ont un véhicule récent. 

Je vais prendre mon exemple personnel pour illustrer mon propos, j'ai hérité de mes parents une vieille voiture diesel de 19 ans maintenant. Soucieux de mon impact, j'aimerai changer pour une voiture électrique, moins mauvaise solution dans mon cas à l'heure actuelle. 

En l'état, j'ai un résultat à 6,5 tonnes avec ma vieille voiture diesel. Je fais donc une modif pour évaluer le gain que je pourrai attendre d'un passage à l'électrique, et la le résultat me donne 11 tonnes de CO2 équivalent, de par l'amortissement sur 1+1 ans des 12000 kg de CO2 à l'achat. 

Ne serait'il pas possible de calculer l'amortissement sur la durée de vie moyenne d'un véhicule ? (Google me dit 12 ans en France, mais cela mériterait sans doute une source un peu plus sérieuse). 

Avec la possibilité à la limite de préciser l'âge du véhicule, et de l’intégrer au calcul si celui-ci dépasse l'âge moyen.

**Comment by laem** [comment]
Merci pour le retour ! ça a été en partie corrigé dans #674
