### ISSUE TITLE
Mon potager peut-il être considéré comme un puits de carbone ? 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#190]
Ou du moins, peut-on considérer par exemple que les fruits et légumes produits dans le jardin nous évitent de se voir imputer les émissions de la production de ces denrées, 
ainsi que d'une part des poubelles grâce à un compost (comptabilisées dans le poste "service public" ?) ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Cette action (cultiver un potager) sera proposée dans le volet action même si l'impact sur la baisse de son empreinte carbone est négligeable. En revanche, poser cette question revient à complexifier le modèle et l'expérience utilisateur.

Concernant l'aspect puits de carbone du potager/jardin, c'est là encore rajouter des questions pour quelque chose de peu significatif
