### ISSUE TITLE
Objectif décourageant?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#193]
Mon empreinte carbone calculée par votre simulateur est de 4 tonnes. Je pense être déjà assez raisonnable. Je suis prête à faire des efforts, cependant passer à  2 tonnes me semble déjà difficile à atteindre. 
Pour d'autres personnes ayant une empreinte plus élevée, leur donner un objectif de 2 tonnes ne risque t il pas de les décourager avant de commencer?

**Comment by laem** [comment]
Bonne question ! 
Déjà, être à 4 tonnes quand la moyenne est à 12, c'est déjà avoir fait l'essentiel du chemin. Le met-on assez en évidence ? 

Revenons à la question : 
- d'un côté, oui passer de 12 à 2 est un énorme effort, et il se trouve que nous avons travaillé dans [cet article](https://ecolab.ademe.fr/blog/général/budget-empreinte-carbone-c-est-quoi.md) en lien sur la page de résultat un effort graduel chaque année pour rester sous les 1.75°. On pourrait donc afficher cet objectif annuel
- d'un autre côté, se limiter à cet effort graduel, plus facile à atteindre, c'est condamner la terre (à l'incertitude près) à 1.75° de réchauffement, ce qui est un changement climatique extrêmement rapide et conséquent. Seul l'objectif à 2 tonnes permet vraiment, du point de vue de la France, de limiter la casse à ce qui a déjà été fait. 
- et finalement, une autre façon de raisonner pourrait être : pourquoi viserai-je 2 tonne, si mes compatriotes et la société dans son ensemble, ne font aucun effort ? Autant viser 8, 6, 4 tonnes et les attendre

Bref, question compliquée mais essentielle.
