### ISSUE TITLE
Logement : Electricité renouvable et gaz renouvelable ça vous parle?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#200]
Pas de possibilité de préciser que l'on a une offre d'électricité verte (avec réinvestissement ENR type enercoop ) ou offre biogaz... ça manque et ça compte. C'est là que réside le potentiel rapide de changement de pratique et de signal de changement du consommateur

**Comment by fjg** [comment]
On arbitre le questionnaire entre expérience utilisateur (rapidité, difficulté à avoir les données...) et précision. Sur l'électricité "verte", l'offre électrique n'est pas déterminante sur l'impact carbone : le mix électrique français est fortement décarboné de base (hydroélectricité, nucléaire, EnRi, biomasse...). Donc rajouter une question sur le fournisseur n'apporte pas à notre connaissance d'impact majeur sur le résultat.
Si vous avez des données précises (études, ...), nous sommes preneurs.

Sur le biogaz, effectivement ca pourrait être autrement plus conséquent. Là encore, on manque d'informations à ce stade pour quantifier l'impact. Preneur si vous avez des éléments.

**Comment by fjg** [comment]
voir #4
