### ISSUE TITLE
Calculateur transport

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#202]
Bonjour,
J'ai indiqué parcourir 12000 Km en véhicule électrique et le calculateur me donne une empreinte carbone de 6T1 au lieu des 3T2 pour la moyenne des Français !!! Je pense qu'il y a une erreur...
Mon calcul serait plutôt de l'ordre de 120 Kg (production d'électricité) + 600 Kg (6T de CO2 liés à la fabrication du véhicule amortis sur 10 ans).
Je pense que le calculateur ne tient pas compte de l'amortissement du véhicule (eq. CO2 liés à sa fabrication) puisque vous ne demandez pas combien de temps je garde mes véhicules. Il est absolument évident que celui-ci durera minimum 10 ans, et très probablement plus.

**Comment by Benjamin-Boisserie-ABC** [comment]
La simulation du volet transport intègre aussi les déplacements en avions susceptibles de faire monter l'empreinte carbone. 
Qui plus est le calculateur dans sa version actuelle prend en compte un amortissement.
