### ISSUE TITLE
Types d'essence

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#214]
Dans la partie sur les voitures, il faudrait également demander le type d'essence utilisée : une voiture roulant au E85 plutôt qu'au E5 ou E10 a un bilan carbone bien plus faible...

**Comment by Benjamin-Boisserie-ABC** [comment]
Les ordres de grandeur sont similaires dans la Base Carbone : 1.68 kgCO2e/l pour le E85 contre 2.8 kgCO2e/l pour le E10. Qui plus est cela rajouterai une question (avec le risque que l'utilisateur ne sache pas y répondre). Enfin, l'objectif de la réduction de l'empreinte carbone de la mobilité est de réussir à se passer dans la voiture individuelle
