### ISSUE TITLE
Le coût des achats divers

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#216]
Même si j'ai bien saisi que tout ça reste négligeable devant le transport et l'alimentation, il me semble que vous gagneriez en précision en proposant tant le coût en €/an que le nombre d'items : c'est assez facile d'estimer combien de vêtements ou de meubles on achète par an et on sait que souvent un prix élevé par item peut se corréler avec un impact plus faible. Comme vous le dites si bien avec le tabouret en plastique vs bois massif, il me semble également que 500 € dépensés dans 3 tshirts et 1 pull produits en Europe ont un impact sensiblement plus faible que 450 € a raison de 30 articles à 15 € en fast fashion. Je ne sais en revanche pas dans quelle mesure un tel calcul peut être mis en place.

Voilà voilà. :)

**Comment by Benjamin-Boisserie-ABC** [comment]
Question répondue dans la F.A.Q
