### ISSUE TITLE
Questionnaire pas ou peu adapté pour une famille

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#220]
Dans une famille, les equipements peuvent être multiples (2 voitures, plusieurs téléphones ...).
Pour la nourriture, il faut non seulement prendre e compte les produits mais aussi leurs contenants et une famille de 6 achète des contenants + gros ce qui diminue la quantité relative de déchets
les quantités de nourritures sont à prendre en compte (60g de viande rouge / repas est différent de 180g/repas d'un facteur 3....
Il faut prendre en compte les déchets

bref interessant mais surtout illustratif 
pas utilisable pour travailler sur la diminution

**Comment by Benjamin-Boisserie-ABC** [comment]
Voir #113 
Nous réfléchissons à une approche par foyer
De plus le volet action est en cours d'élaboration
