### ISSUE TITLE
Que puis-je changer ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#222]
Une fonctionnalité qui serait je pense pertinente serait, une fois le test terminé, de proposer à la personne de modifier ses réponses, pour voir l'impact. Par exemple j'ai dit que je mangeais 5 repas avec de la viande par semaine, quel est l'impact si je deviens végétarien ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Volet action en cours d'élaboration
