### ISSUE TITLE
Possibilité de choisir plusieurs énergies pour le chauffage

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#224]
Je pense qu'il serait judicieux de pouvoir sélectionner plusieurs énergies de chauffage pour un même domicile, notamment pour les personnes qui se chauffent en partie au bois (souvent combiné à des radiateurs électriques).

**Comment by Benjamin-Boisserie-ABC** [comment]
Cela est possible dans la version actuelle de l'outil
