### ISSUE TITLE
Amortissement construction voiture

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#225]
Contrairement à l’usage qui est divisé par le nombre d’usagers, l’amortissement de la construction de la voiture est fait sur le propriétaire indépendamment du nombre d’usagers (dans le cas d’une famille avec une voiture pour 2 ou pour 3 par exemple), ne faut-il pas également permettre une propriété à plusieurs de la voiture?

**Comment by laem** [comment]
Même problème que #168 , mais beaucoup plus grave que le smartphone.

**Comment by laem** [comment]
On a trois possibilités : 
- attribuer l'empreinte de l'achat à l'année de l'achat. Position extrême, cohérente du point de vue du climat, mais produisant un yoyo de l'empreinte les années suivantes (j'achète une voiture électrique en 2019 -> 12 tonnes; de 2020 à 2030, je ne fais que l'utiliser -> 500kg / an; e, 2031 j'en achète une autre -> 10 tonnes)
- lisser l'empreinte sur la période entre l'achat et la simulation. On retrouve le même effet de yoyo, mais atténué. L'avantage : c'est une empreinte "dans le pire des cas", car même si l'utilisateur pense la garder 5 ans, il est aussi tout à fait possible que pour diverses raisons (accident, déménagement, nouveau modèle trop cool) ce ne soit pas le cas.
- lisser l'empreinte sur une estimation de la durée de vie moyenne du bien, en laissant l'utilisateur s'engager sur x années d'utilisation. Pas d'effet yoyo ✔️ . Problème : c'est super compliqué de répondre à cette question. Qui peut sincèrement savoir combien de temps il va garder son smartphone ? Le réflexe sera de se dire "et mon ancien smartphone / ancienne voiture, je l'ai gardée combien de temps" ? Dans ce cas là, pourquoi ne pas poser cette question explicitement ?
- lisser l'empreinte de façon dégressive : par exemple, on attribue 30% de l'empreinte à la 1ère année, 20% à la 2ème, 10% à la 3ème, et ainsi de suite pour une durée finale de x années à paramétrer en fonction du bien (valeur par défaut, puis saisie utilisateur). L'avantage : grâce à cette méthode, on n'oublie pas que les émissions sont bien produites dès la 1ère année, et qu'elle réchauffent bien la planète dès la 1ère année.

Personnellement je penche pour la 1ère.

**Comment by hokkos** [comment]
Ou alors utiliser la solution qui est celle de toute la littérature scientifique sur le sujet : amortir sur la durée de vie moyenne du type de voiture considéré.

Les effets pervers des différents points sont :

- si on achète une voiture d'occasion, alors c'est 0 empreinte puisque celle ci a déjà été payé par le consommateur précédent. Mais en réalité le consommateur précédent a acheté cette voiture neuve car il sait qu'il y a un marché et une demande pour l'occasion, donc l'acheteur du marché secondaire est aussi une force qui entraîne le marché primaire.
- une voiture ce n'est pas un smartphone car cela ce revend dans la très grande majorité des cas avant les 10 ans d'utilisation moyenne, personne ne met à la casse une voiture utilisable s'il peut en tirer un bénéfice. De plus faire ainsi ne respectera pas le critère d'additivité des années, car l'année d'achat de la voiture elle sera complètement incluse, la deuxième année à 50%, bref c'est la somme de la série harmonique, c'est toujours supérieur à 1.
- autant si je pense que demander combien de temps vous gardez votre smartphone, et si vous le revendez/reconditionnez à la fin, est une bonne idée. Pour les voitures la revente est implicite, alors autant prendre la durée de vie moyenne, surtout qu'on est pas maître de son usage post revente.
- je ne vois pas l’intérêt d'utiliser un lissage non linéaire, il n'y a aucun raison de singer les règles de comptabilités issue des règles fiscales ayant pour but de constater une dépréciation plus forte au cours des premières années de la durée de vie du bien dans le but de créer une incitation fiscale à l'investissement.

Je pense que le but est d'avoir une idée générale du CO2eq émis par le mode de vie asymptotique dans l'année en cours, pas de savoir si l'achat d'une voiture neuve vs occasion est pire, car ce n'est pas le cas vu l'efficience du marché de la revente. Les acheteurs à l'occasion finances les acheteurs de neuf, et doivent donc participer à la charge CO2eq, ainsi le seul moyen étant donné l'impossibilité de savoir le devenir de la voiture poste revente, est d'amortir linéairement sur la durée de vie moyenne du type de voiture.

**Comment by nerdua-OZC** [comment]
Mon avis sur les 4 scenarii:
1- difficile à comprendre pour intégrer la notion d'investissement. Une personne achetant un véhicule, même très sobre, se voit infliger une "punition". dans ce contexte le jeep cherokee de papa est moins impactant (sur le papier a l'instant t)
2- je crois que c'est ce qui est intégré au calculateur ? année 1: 12t, n+1 : 11t, n+2: 10t... 
bilan en 3 ans : 33t émis. ca me semble compliqué a justifier.
3- a mon sens, un véhicule est conçu pour être fiable et réparable sur une période prédéterminée. c'est la durée de vie conventionnelle. sur un groupe c'est la moyenne avant "très grosse maintenance". Si un véhicule est vendu avant ce terme il a de la valeur qui est l’espérance de vie restante. un lissage sur DVC me parait un calcul sage.
4- de mon point de vue, l'émission de l'année 1 ne devrait pas avoir plus de pénalité que l'année 2 jusqu'au terme de la DVC mais il y a quelque chose intéressant dans la dégressivité. 

-> ma chèvre a cinq pattes: 
- émissions maintenance : fixe (env 5gCO2/km)puis augmentation progressive après DVC justifié par une probable maintenance lourde
- émissions construction: Lissée sur la DVC (10ans ou kilometrage) puis diminution progressive jusque 0 en relais de la maintenance. 

appliqué ca donne pour 20000km/an, DVC(10ans), emission construction 7t (zoé 21KWh d'après le site climobil, pourquoi 12t dans le simulateur ?) : 

n0-10:  560kg (80% construction) + 100kg (maintenance) + X emissions directes mix elec = environ 860kg au total
n10-15: 280kg (20% construction post DVC)+150kg (maintenance post DVC) + emissions directes = 630
>n+15: 200kg maintenance + emissions= 400

L'effort de maintenabilité et d'entretien est payant mais "l'heritage" de l'émission initiale est soutenue.  L'investisseur n'est pas écrasé sous le poids de l'année 1.

le système des CEE et des KWhCumacs peut être une source d'inspiration.

**Comment by laem** [comment]
Merci pour vos retours @nerdua-OZC et @hokkos  😃 
De loin les retours les plus constructifs pour l'instant sur le simulateur 🥇 ! 

> Ou alors utiliser la solution qui est celle de toute la littérature scientifique sur le sujet : amortir sur la durée de vie moyenne du type de voiture considéré.

Tu as des liens ? Quelle littérature scientifique travaille sur l'affiche de l'empreinte climat aux citoyens ? 

Pour moi, appliquer une "pénalité" la ou les premières années est essentiel, dans le contexte décrit dans [cet article](https://ecolab.ademe.fr/blog/général/budget-empreinte-carbone-c-est-quoi.md). C'est ce que je voulais dire par "cohérente du point de vue du climat". Je m'explique : 

> Supposons qu'un constructeur de voiture électrique réussisse à faire durer sa voiture 1 million de km (c'est déjà supposément le cas pour certaines, mais la batterie reste limitée à < 500k km). En partant d'un usage de 20k km/an, on arrive à une durée de vie de... 50 ans, qui nous amène en 2070. On voit bien le problème : en lissant l'empreinte sur la durée de vie, on a affiché à l'utilisateur une bonne estimation de l'empreinte à horizon 2070, qui sera donc bien ridicule pour la seule année d'achat, 2020. Pourtant, notre sujet ce n'est pas *que* le climat en 2070, il aura été impacté par la production entrainée par cet achat dès les 1ères années de 2020.

Pour l'instant, suite aux remarques pertinentes, je laisse de côté la question de l'occasion ou pas. Idem pour l'intégration de des gCO2 de l'entretien et le dépassement de la durée de vie moyenne : il faut déjà qu'on sorte une version simple et cohérente du point de vue d'un utilisateur qui ferait sont calcul plusieurs années de rang.

Proposition à venir bientôt en PR ;)

**Comment by laem** [comment]
Implémenté dans #646

**Comment by laem** [comment]
Ce sujet continue de faire couler l'encre. Voir https://twitter.com/hokkos/status/1336356421319921665
