### ISSUE TITLE
Très bon test détaillé et synthétique à la fois

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#226]
La question sur l'alimentation précise hebdomadaire sur les repas (viande rouge, viande blanche, végétarien, végétalien) je l'ai particulièrement appréciée, néanmoins, je suggérerais d'ajouter le poisson qui est tout de même consommé assez fréquemment et que vous avez omis d'ajouter aux choix possibles (j'ai donc considéré l'option médiane en l'ajoutant à la viande blanche à chaque fois). Par ailleurs, en ce qui concerne les vêtements, vous devriez différencier selon la provenance et la qualité des vêtements achetés, et pas seulement le prix total, car par exemple entre le T-Shirt de qualité produit localement à 30 euros et 10 T-Shirts à 3 euros importés du Bangladesh ou du Vietnam, la différence en terme de bilan CO2 finale sera considérable. Une question sur les fruits exotiques importés devrait aussi être ajoutée. Enfin, en ce qui concerne l'aviation, étant donné le poids colossal de la question sur les émissions CO2 totales d'un individu, la question devrait être plus détaillée et notamment prendre en compte le fait que les vols court-courrier et très long-courrier sont plus polluants au km que les vols moyen-courrier et long-courrier. J'ajouterais aussi que je trouve les émissions numériques largement sous-estimées (sans être un spécialiste en la matière), en particulier pour la consommation de vidéos qui est bien plus gourmande en données et en énergie que le reste. J'espère que ce commentaire vous sera utile.

**Comment by laem** [comment]
> Enfin, en ce qui concerne l'aviation, étant donné le poids colossal de la question sur les émissions CO2 totales d'un individu, la question devrait être plus détaillée et notamment prendre en compte le fait que les vols court-courrier et très long-courrier sont plus polluants au km que les vols moyen-courrier et long-courrier. 

Distinction faite ! :partying_face: 

Merci pour vos retours, ils sont pertinents et notés déjà dans plusieurs issues :)
