### ISSUE TITLE
Alimentation

### ISSUE THREAD

**Issue by fjg** [betagouv/ecolab-data#23]
## Régime

"Quel régime vous correspond le plus ? ℹ️"

Il manque un régime avec "Viande 1 fois par semaine" ?

**Comment by laem** [comment]
#8

**Comment by laem** [comment]
Pour répondre à cette question il faut créer nous-même des régimes représentatifs en se basant sur les valeurs de la base carbone / agribalyse v3.

**Comment by laem** [comment]
Et personnellement j'aimerais ajouter le régime planétarien https://www.theguardian.com/environment/2019/jan/16/new-plant-focused-diet-would-transform-planets-future-say-scientists

**Comment by laem** [comment]
Retour utilisateur : "il manque flexitarien. Je ne me sens pas concernée par les propositions. Et végétarien c'est pas de poisson".

**Comment by Benjamin-Boisserie-ABC** [comment]
Pourquoi ne pas envisager la même approche que dans Mic Mac où l'on doit choisir le nombre de repas par semaine. On demanderait alors à l’utilisateur de venir cliquer pour obtenir 14 repas (ou 21 si on décide de prendre en compte le petit dej). Ex : 
        Je clique 7 fois sur à base de viande blanche, 3 fois à base de viande rouge, 1 fois sur à base de poisson, 10 fois végétarien (3 repas + 7 petit dej)

On pourrait garder les choix des différents types de repas déjà existant en y ajoutant d'autres comme  "repas à base de viande blanche", "repas à base de poissons", "petit déjeuner viennoiserie café, "petit déjeuner oeuf et jambon", etc.

J'ai conscience que cela peut être un peu plus contraignant pour l'utilisateur sans toutefois rentrer dans les grammages

NB : l'article du guardian me fait penser au rapport Afterres sur l'assiette 2050 : 
https://afterres2050.solagro.org/wp-content/uploads/2015/11/Solagro_afterres2050-v2-web.pdf (p15)
Voir aussi : https://www.wwf.fr/sites/default/files/doc-2017-11/171109_rapport_vers_une_alimentation_bas_carbone_saine_abordable_0.pdf

**Comment by laem** [comment]
On s'est fait un petit atelier de remue-méninges sur cette question : voilà ce qui ressort. Une question par colonne, donc 4 en tout (au lieu d'une seule aujourd'hui).

![image](https://user-images.githubusercontent.com/1177762/86597554-2f719e00-bf9c-11ea-8255-6b0ac9394a8b.png)

**Comment by laem** [comment]
Je ferme au profit d'une nouvelle issue sur l'alimentation, maintenant que #71 a été intégrée :)
