### ISSUE TITLE
emprunte du logement

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#231]
il manque selon moi un gros poste dans l'estimation, c'est l'emprunte carbone de l'habitation, particulièrement pour ceux qui font construire ou démolissent/reconstruisent un logement en construction traditionnelle (bloque béton, isolation en PUR etc). Vivre en ville ou en campagne pourrait être une information intéressante aussi...

**Comment by laem** [comment]
> c'est l'emprunte carbone de l'habitation, particulièrement pour ceux qui font construire ou démolissent/reconstruisent un logement en construction traditionnelle (bloque béton, isolation en PUR etc)

C'est pris en compte. Certes, mal voir #111 

>Vivre en ville ou en campagne pourrait être une information intéressante aussi... 

Trop vague aujourd'hui. Il n'existe pas de modélisation de cette question à ma connaissance.
