### ISSUE TITLE
Section divers approximative

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#232]
Bonjour, peut être devriez-vous préférer fréquence de remplacement pour l’électroménager plutôt que demander depuis combien d’années il est en notre possession. De même pour les vêtements un nombre de pièces est peut-être préférable à un prix. Enfin indiquer le total estimé peut inciter à sous estimer chacun de nos choix pour apparaître plus vertueux.
Merci

**Comment by Benjamin-Boisserie-ABC** [comment]
Nous réfléchissons à la prise en compte de la fréquence de remplacement dans le volet action afin de faire émerger des actions de type "allonger la durée de vie". A ce sujet consulter : 
https://www.ademe.fr/evaluation-environnementale-economique-lallongement-duree-dusage-biens-dequipements-electriques-electroniques-a-lechelle-dun-foyer 
Concernant les ratios monétaires et l'approche par le prix, cela est expliqué dans la F.A.Q
