### ISSUE TITLE
Boissons chaudes ? 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#233]
Dans les résultats finaux j'ai une valeur attribué pour les boissons chaudes mais je n'ai répondu à aucune question à ce sujet. Les seules questions que je vois sont boissons froides et boissons alcoolisées.

C'est attribué d'office ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Oui les boissons chaudes de types cafés/thé sont attribuées d'office en attendant dans une version prochaine de poser la question à l'utilisateur
