### ISSUE TITLE
Unités sources d'énergies à modifier

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#235]
Les formulaires concernant les quantités de fioul, gaz et bois utilisent le kwh comme unité (comme pour l'electricité). Or, sur la plupart des factures, ces unités sont respectivement en litres, metres cubes et stères. Ce serait donc bien plus simple si vous adaptiez vos formulaires à ces unités: à votre outil de faire la conversion. D'autant que la conversion dépend fortement du rendement de l'appareil de chauffage utilisé (exemple: poêle Jotul à 85% contre cheminée ouverte à 15%).

**Comment by Benjamin-Boisserie-ABC** [comment]
Remarque prise en compte
