### ISSUE TITLE
Foyer / personne unique

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#236]
Bonjour,
Merci pour ce questionnaire. Une petite remarque : pensez à préciser si on parle d'un foyer ou d'une seule personne dés le départ. (Les questions liées à l'habitat semblent s'appliquer à un foyer complet).
Du coup prévoir plusieurs véhicules si c'est un foyer complet (l'une thermique l'autre électrique par exemple).

**Comment by guillaumepy** [comment]
Je plussoie, ce n'est pas très clair aussi au niveau des résultats. Est-ce bien affiché par personne du foyer ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Répondu dans la F.A.Q. 
Au sujet de l'approche par foyer voir #113
