### ISSUE TITLE
Prise en compte des familles 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#239]
Bonjour, bravo pour ce beau boulot. J’ai une remarque sur la distinction pas toujours facile à faire entre l’impact individuel et celui d’une famille. Il n’est pas toujours évident de savoir si l’info saisie va s’appliquer à tout le foyer ou juste à la personne qui répond. Peut être faudrait-il clarifier ce point dès le début du questionnaire (qui est par ailleurs très facile à remplir).

**Comment by Benjamin-Boisserie-ABC** [comment]
Question répondue dans la F.A.Q
Au sujet de l'approche par foyer voir #113
