### ISSUE TITLE
Finance

### ISSUE THREAD

**Issue by fjg** [betagouv/ecolab-data#24]
## Finance

"Quelle est votre épargne dans les banques ou fonds classiques ?"

C'est quoi "classique" ? comment répondre ? Donner des exemples sans nommer des marques.

**Comment by laem** [comment]
D'ailleurs, je crois bien que c'est la question finance elle-même qui devrait être enlevée du bilan, car elle aboutit probablement à un double comptage. 

J'ai de l'argent dans une banque française, et qu'on suspecte que cet argent finance une compagnie pétrolière => on m'attribue une partie de l'impact de la production ou de la combustion de l'essence
- si je conduis ma voiture sur 1000km, on m'attribue l'ensemble des émissions des 70l d'essence 
Mon bilan est donc surestimé. 
Je pense, a ce stade, que le poste finance doit être intégré comme une action de réduction, au chiffrage incertain. C'est une action de privation de liquidité.

**Comment by laem** [comment]
Dans un premier temps, on peut déjà bien expliquer qu'on est conscient du double comptage, mais que le simulateur fait aussi des "sous-comptages" ailleurs.

**Comment by laem** [comment]
Bon, on a déjà 2 retours utilisateur sur le sujet du double comptage : 

`Ex : mon voisin est propriétaire d'un logement de 300 K€, tandis que je suis locataire et que j'ai 300K€ d'argent en banque (fonds d'état en euros) : dans mon empreinte, vous calculez mon logement et mon placement; dans celle de mon voisin, vous ne calculez que son logement : manifestement pas normal !
En fait, l'argent n'émet jamais de CO2 ni assimilé : erreur de raisonnement ! Admissible pour une petite association (pourquoi pas un peu de provocation pour sensibilser aux placements dits "responsables"); mais pas de la part d'organisations sérieuses. Les outils et bases perdent du crédit sinon.`

**Comment by laem** [comment]
Nous avons enlevé la finance du calcul, car c'est un double comptage. Il pourra revenir dans les fiches action :)
