### ISSUE TITLE
Précision à apporter

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#242]
Manque une information sur le bio/local pour l'alimentation
Manque des questions sur le seconde main pour le numérique (j'achète personnellement tout sur BackMarket, le produit n'est pas neuf) 
La consommation numérique au travail est oublié, perso je travail sur ordinateur et serveur, mon travail pollue.

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant l'alimentation bio/local, des réponses sont apportées dans la F.A.Q. De plus voir #185 pour une amélioration du modèle de calcul du poste alimentation
Sur la seconde main, nous allons tacher de la prendre en compte sur le volet action
La consommation numérique au travail relève de l'aspect professionnel et n'est donc pas à prendre en compte (cela rentre dans le périmètre de comptabilité de l'entreprise). Nos Gestes climat s'intéresse à l'aspect personnel.
