### ISSUE TITLE
Alimentation & achat

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#244]
Bonjour, 

Dans la section Alimentation il n'y a pas assez d'informations sur la provenance des aliments consommés. J'imagine que consommer local pollue moins que consommer de la process food. 

Idem pour la section Achats, Il faudrait demander la provenance des produits achetés. 

C'est génial merci pour ce travail !

**Comment by Benjamin-Boisserie-ABC** [comment]
Questions répondues dans la F.A.Q + voir #185 pour l'amélioration du modèle de calcul de l'empreinte du poste alimentation
