### ISSUE TITLE
Petit déjeuner : le lait est uniquement animal

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#246]
La Cour de Justice de l’UE  a décidé que certains produits végétaux, comme le lait de soja ou le beurre végétal, ne pourront plus être commercialisés sous ces appellations.

La Cour relève que, aux fins de la commercialisation et de la publicité, la réglementation en cause réserve, en principe, la dénomination « lait » au seul lait d’origine animale.

**Comment by laem** [comment]
Merci pour l'information. Nous n'avons donc pas à nous inquiéter, car nous ne faisons aucune commercialisation ou publicité :) 

Si un nom émerge pour designer ce qu'on appelle aujourd'hui couramment les laits végétaux, nous serons ravis de l'utiliser.
