### ISSUE TITLE
chauffage au bois

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#248]
je n'utilise ni des bûches ni des granulés mais des déchets de scieries le bilan est très différent !!

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat se base sur les modes de consommation les plus fréquents. Si vous connaissez la différence d'ordre de grandeur entre les facteurs d'émissions "déchets de scieries" et bûches/granulés vous pouvez renseigner une valeur de consommation "adaptée" en conséquence afin d'approcher votre impact réel
