### ISSUE TITLE
Question mal posée voiture

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#249]
La question quant a l'âge de la voiture ne colle pas avec le calcul qui est fait derrière. Vous calculez l'amortissement de la production de la voiture donc la question devrait plutôt être "combien de temps comptez vous  garder cette voiture" plutôt que son âge ... voilà :)

**Comment by Benjamin-Boisserie-ABC** [comment]
Cette question sert à savoir "la durée restante d'amortissement" vis à vis d'une durée d'utilisation moyenne
