### ISSUE TITLE
qualité du questionnaire

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#250]
Il faudrait que vous demandiez quelques éléments d'information de base pour connaître le profil des répondants. Je critique particulièrement l'environnement des questions transport (ex : ma pratique de covoitureuse en tant que passagère compte-t-elle ?)  et logement

**Comment by Benjamin-Boisserie-ABC** [comment]
Tous nos actes du quotidien ont un impact. Certains bien plus que d'autres. Félicitation pour votre pratique du covoiturage en tant que passagère plutôt que d'avoir recours à l'achat d'une voiture individuelle. Néanmoins, ce trajet en covoiturage participe tout de même à émettre des émissions (même si c'est bien moins que si tout le monde utilisait une voiture individuelle).
Concernant le profil des répondants, nous travaillons sur le volet action pour proposer des actions adaptées
