### ISSUE TITLE
Quantification du bois

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#251]
Bonjour, merci pour ce calculateur. Une remarque sur le comptage du bois énergie. Exprimer la quantité en stère serait sans doute plus pratique qu’en kWh.

**Comment by laem** [comment]
Voir aussi ce retour : https://mobile.twitter.com/geninbv/status/1303430470336679942

**Comment by Benjamin-Boisserie-ABC** [comment]
Se reporter à #867
