### ISSUE TITLE
Scotter, et autre engin motorisé ??

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#252]
Votre évaluation comporte d enormes omissions. 
Transport: quid des déplacements en quad, scooter, camionnette, campung car etc?...
- hobbies!! Quid des personnes qui pratiquent l'aviation de loisirs,  bateau à moteur, chute libre, ski , depose en helicoptere, motocross, etc...  fréquentent les établissements de luxe, possèdent une climatisation,  etc.....

**Comment by Benjamin-Boisserie-ABC** [comment]
NGC est un outil grand public qui cherche à être simple d'utilisation. Il ne peut pas prendre en compte tous les cas spécifiques de déplacements. Néanmoins certains modes peuvent, à défaut, être approximés dans les réponses aux questions déjà présente.
Au sujet des 2 roues, une question est prévue
Au sujet des loisirs, en effets certaines pratiques sont extrêmement impactante pour le climat. Elle mériterait d'être prise en compte. Cependant elle ne représente qu'une petite partie de la population. Ce n'est donc pas une priorité mais nous prenons en compte ce retour.
