### ISSUE TITLE
Apprenez à faire du contenu agréable.

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#256]
La forme est tellement négligée qu'elle dessert complètement le fond et le propos. 
- Agrandissez vos images, vos schémas, la taille de la font. C'est illisible. J'ai honnêtement du me faire violence pour lire.
- Le discours n'est pas structuré. En terme de teasing, si on est pas déjà partisan de la cause on a aucune accroche et aucune envie de lire (appliquez la méthode AIDA)
- Le ton est beaucoup trop agressif. Être passionnés et désespérés par la situation actuelle ne doit pas rendre la discussion désagréable.
- Lisez ça: https://firstround.com/review/a-founders-guide-to-writing-well/
c'est tellement cliché que les devs soient incapables de se mettre au content marketing.

**Comment by laem** [comment]
N'hésitez pas à être plus précis dans vos remarques, par exemple en citant un paragraphes précis, ou à appliquer à vous-mêmes vos propres remarques génériques ;) 

Je me permets d'éditer votre retour car ça ressemble beaucoup à du placement d'URL.
