### ISSUE TITLE
Lieu résidence 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#259]
Votre article est très intéressant mais comme vous le dites il est très difficile de calculer de façon précise cette empreinte. Ce qui me gêne avec ces algorithmes, c'est que lorsque que l'on vie à la campagne on a toujours une empreintes carbone élevée due au transport alors que l'on consomme localement....
Donc difficile de rester compréhensif/par rapport aux citadins pour qui ces calculateurs sont faits
Merci

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat est fait pour tout le monde. Prendre en compte les déplacements en voiture (plus fréquent pour les ruraux) relève juste d'une réalité physique. Nous travaillons actuellement au développement d'un volet action afin de proposer des actions adaptées à la réalité de l'empreinte carbone de chacun et du profil de l'utilisateur
