### ISSUE TITLE
lisibilité et compréhension

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#262]
Il serait intéressant de comparer nos résultats à la moyenne nationale pour se rendre compte de notre impact, par exemple en superposant les jauges : nos résultats sur la jauge de la moyenne.

**Comment by Benjamin-Boisserie-ABC** [comment]
Moyenne française actuellement donnée de manière générale. Remarque prise en compte pour l’avoir par poste. Voir #868
