### ISSUE TITLE
âge  des Véhicules persos versus consommation

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#263]
Bonjour,
étrangement, mon bilan est plus mauvais avec une voiture récente qu'une voiture ancienne.
Or... je viens de changer de véhicule, avec l'objectif de le conserver longtemps...
mon objectif était simple : consommation -20%, bilan CO2 -80%...
Dommage que cela n’apparaisse pas dans le calcul...
En fait, comme pour les questions sur les équipements électroménagers, ce qui compte, c'est aussi la durée d'amortissement. Je ne change pas ma voiture tous les 3 ans. Mais je viens de changer et cela me pénalise, même si je roule peu car je suis principalement cycliste et mes enfants utilisent les transports.
Sans doute une piste d'amélioration de ce point, parce que je trouve que ça n'incite pas à aller vers des outils moins énergivores (tant qu'il reste difficile de se passer d'un véhicule, ce qui est un débat différent)...
Merci !

**Comment by laem** [comment]
Voir #225
