### ISSUE TITLE
erreur electrique

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#264]
bonjour. Je me permets de faire un retour sur l idee tres bonne mais avec un parti pris trop marqué.
Les moteurs electriques n ont de loin pas une si faible empreinte. J essai petit a petit de trouver les articles mais cela reste difficile pour le moment de les lister. 
Merci

**Comment by Benjamin-Boisserie-ABC** [comment]
L'impact de la construction de la voiture est pris en compte. Nous avons bien un facteur plus important pour les voitures électriques que pour les voitures thermiques
