### ISSUE TITLE
Les questions autour du transport en voiture ne sont pas forcément pertinentes

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#265]
Bonjour et merci pour ce questionnaire de qualité !

Dans les première questions relatives au transport, je me retrouve dans une situation où je ne peux pas répondre correctement.

Je n'ai pas de voiture, mais je fais de la voiture (en étant conduit par des amis/famille/covoiturage) de temps en temps.
Si je dis que je fais au moins 1km de voiture par an, j'ai des questions sur la motorisation/age/type/consommation de ma voiture alors que je n'en possède pas.

- "Avez-vous votre propre voiture individuelle ?"
- Non
- "Quel type de voiture utilisez-vous ?"
- Le type "avec chauffeur qui va à la même destination que moi"

Cordialement,

**Comment by Amoki** [comment]
C'est moi qui ai écrit ce message.

Une solution pourrait être de conditionner les questions sur le véhicule à la question "Avez-vous votre propre voiture individuelle ?" (https://github.com/betagouv/ecolab-data/blob/master/data/transport.yaml#L103)

Dans mon cas, je fais des km en voiture avec différentes voitures de proches/covoiturage. Je ne les choisi pas.
Peut-il être pertinent de prendre la consommation moyenne du parc de véhicules actuels Français pour estimer la consommation dans ce cas ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Le questionnaire est pensé pour que les personnes covoitureurs comme vous renseigne tout de même les informations des véhicules les transportant. En effet, même si l'impact est réduit du fait d'un nombre important de personne dans la voiture, il y a tout de même émissions de GES. Concernant les caractéristiques des voitures utilisées vous pouvez renseigner une voiture "moyenne" ou à défaut répondre "je ne sais pas"
