### ISSUE TITLE
Estimation coût d'alimentation intensive / extensive / local 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#266]
Bonjour,

Votre site est super, le calcul de l'empreinte carbone est très informatif.
J'aurais toutefois une suggestion concernant la nourriture, il faudrait probablement rajouter pour chaque type d'aliment une provenance (local / supermarché) afin d'affiner l'estimation de l'empreinte carbone. 
Par exemple consommer de la viande en agriculture extensive (animaux paturent) et local (moins de transport) aurait un impact carbone moins fort qu'une consommation de fruit ou légume produit de manière intensive (utilisation d'engin énergivore) à l'autre bout de la planète (fort coût de transport). Cela serait intéressant de bien calculer ses coûts.

Merci pour votre travail.

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat est un calculateur grand public d'information. Nous cherchons donc à être simple et à limiter le nombre de question afin d'engager le plus grand nombre à la simulation. 
Prendre en compte ces informations (saison/local/mode de production/etc.) sont complexes et nécessiterait de nombreuses autres questions. Nous réfléchissons néanmoins à une manière (simple) de prendre en compte ces paramètres dans le calculateur.
