### ISSUE TITLE
Des précisions qui peuvent changer les résultas

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#267]
Bonjour,
Je viens d'effectuer le test pour évaluer mon empreinte carbone et je souhaiterais vous faire part de quelques questions /remarques.
Mon budget carbone le plus important reste celui de l'alimentation. 
Cependant parmi les réponses proposées il n'était pas possible de prendre en compte les types d'achats que nous effectuons (Amap, locaux et bio), qui il me semble, permettent de réduire les émissions de GES.
Par ailleurs, il me semble également que ne pas renouveler trop souvent son véhicule contribue à réduire ses d'émissions de GES. Cela évite toutes les émissions liées à la production de la voiture en elle même. Est ce que cette énergie grise est comptabilisée dans votre calcul de l'empreinte carbone transport?
Cordialement,
C.SAKDA

**Comment by Benjamin-Boisserie-ABC** [comment]
Au sujet de l'alimentation de nombreuses réponses sont apportées dans la F.A.Q. De plus, prendre en compte certains paramètres sont complexes et nous avons fait le choix de rester simple afin d'engager le plus de monde à la simulation.
Renouveler moins souvent ces équipements participe, de manière générale, à limiter les émissions car il cela permet en effet, de ne pas avoir à construire de nouveau équipement. Dans le cas d'une voiture, ce constat doit être nuancé si l'on considère un vieux véhicule très émissif qui plus est utilisé de manière fréquente. Le remplacement du véhicule peut s'avérer bénéfique.
L'énergie grise est en partie pris en compte pour les transports(construction voiture, services publics de voirie, etc.)
