### ISSUE TITLE
Alimentation + bus

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#268]
1. pas d'option de petit-dejeuner sale.
2. pas d'option de choix de la nourriture (bio, local, import depuis des continents etrangers, etc)
3. pas d'option de diete sans produits laitiers mais avec viande: un grand probleme dans la communication en generale car il n'y a pas d'identification des gens ne consommant pas de produits laitiers.
4. pas d'option de trajets en bus par an. je me deplace en velo quotidienement mais pour rentrer en France je prends le bus, moins cher que le train et moins polluant que l'avion.

**Comment by Benjamin-Boisserie-ABC** [comment]
De nombreuses réponses sont apportées dans la F.A.Q.
Concernant l'option petit déjeuner salé voir #185 
De plus, Nos Gestes Climat se veut être un outil grand public, le nombre de question est limité afin d'engager le plus de monde à la simulation.
Prise en compte de la remarque sur les grands trajets en bus
