### ISSUE TITLE
Retour à zéro de certaines rubriques

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#269]
Bonjour, lorsqu'on met à zéro certains paramètres (age d'un appareil par exemple) la rubrique (par exemple habitation) se met à zéro, alors que techniquement ce n'est qu'une partie de cette rubrique et pas la rubrique entière, ça me paraissait bizarre, mais c'est un détail!

**Comment by Benjamin-Boisserie-ABC** [comment]
Problème résolu avec la version actuelle du simulateur
