### ISSUE TITLE
Expliquer ce que sont les kgCO2eq

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [betagouv/ecolab-data#27]
Il faudrait expliquer et vulgariser cette notion en mettant éventuellement un lien d'une page Ademe

Je vais chercher

**Comment by laem** [comment]
Bien vu, j'ai mis un texte et un lien vers [notre article](https://ecolab.ademe.fr/blog/g%C3%A9n%C3%A9ral/budget-empreinte-carbone-c-est-quoi.md) quand on clique sur "comprendre le calcul"

![image](https://user-images.githubusercontent.com/1177762/84030048-a878d800-a993-11ea-9eea-64b3c24198ca.png)
