### ISSUE TITLE
Il y a des manques dans cette simulation

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#270]
L'empreinte hygiène (douche, conso eau, savon). Les déchets ( achat de produits cuisinés avec packaging, combien de poubelles papiers et déchets de 50 litres par exemple par semaine).

**Comment by Benjamin-Boisserie-ABC** [comment]
Beaucoup de question relève de l'impact environnemental en général. Nos Gestes Climat est un simulateur portant sur le critère carbone seul (à l'heure actuelle).
L'eau chaude sanitaire se retrouve pris en compte dans le type de chauffage utilisé dans le logement
Les déchets sont déjà pris en compte dans le simulateur via la question sur le mode de vie zéro déchet
Un volet action est en cours de développement pour affiner cela
