### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#271]
Bonjour,
Merci pour ce simulateur très bien fait. Si je puis me permettre une suggestion : dans le chapitre logement, il n'est pas possible de sélectionner la source d'énergie électrique que l'on utilise, à savoir énergies renouvelables ou énergie nucléaire. Je me doute que la différence en termes de rejets de CO2/GES n'est pas énorme entre les deux mais tout de même, ce serait un raffinement intéressant à développer (avec la difficulté de distinguer les fournisseurs qui sont "vraiment verts" j'en conviens)
Encore bravo , continuez comme cela.

**Comment by Benjamin-Boisserie-ABC** [comment]
Réponse apportée dans la F.A.Q
