### ISSUE TITLE
Deux petites difficultés

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#272]
J'ai répondu non à la question avec vous une voiture personnelle mais le questionnaire m'a tout de même posé des questions sur les caractéristiques de ma voiture. 
Par ailleurs, dans les repas que vous proposez il y a le choix entre viande 1 et 2 vegan et végétarien mais quid d'un repas avec des légumes et du poisson !!

**Comment by Benjamin-Boisserie-ABC** [comment]
Quand on renseigne des km parcourus, le simulateur pose les questions sur les caractéristiques des véhicules. En effet, ne pas posséder sa voiture personnelle n’empêche pas d'utiliser de voitures (covoiturage, location etc.). C'est pour cela que ces questions sont ensuite posées.
Pour le poisson, voir #185
