### ISSUE TITLE
Chauffage collectif 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#273]
C'est sûrement compliqué à intégrer, mais j'ai de l'eau chaude et un chauffage collectif. Cette partie là du calcul ne peut donc pas être utilisé.

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, difficile de savoir combien vous consommez. Nous avons introduit l'approche par prix qui peut s'avérer plus pertinentes (en divisant la facture collective par le nombre d'habitants ou par les m2 chauffés). Même si cela reste approximatif.
