### ISSUE TITLE
formulation question lait

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#274]
Je trouve que la question sur le lait est bizarrement formulée. "Est-ce du lait végétal, plutôt que du lait de vache ?". Surtout avec une réponse "oui" "non". 

Mieux vaudrait : 

"quel type de lait consommez vous ?" 

avec comme réponse possible : "lait animal"/"lait végétal", ou "lait de vache" / "lait végétal"

Merci,

**Comment by Benjamin-Boisserie-ABC** [comment]
Voir #185
