### ISSUE TITLE
Pouvoir choisir le nombre de repas par jour 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#276]
Il serait intéressant de pouvoir choisir le nombre de repas par jour, avant de distribuer les repas entre les différents types de menus. Certains ne font qu'un repas par jour. Donc ne devrait distribuer que 7 repas plutôt que 14.

**Comment by Benjamin-Boisserie-ABC** [comment]
La version actuelle du simulateur permet de renseigner moins de 14 repas
