### ISSUE TITLE
Questionnaire pas assez précis -> est-il possible de passer en dessous de 2 tonnes si on n'est pas sdf ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#278]
Tout est dans le titre, ceci dit, merci, c'est une très bonne initiative, j'attendais depuis longtemps que ce test soit remis en ligne (je l'ai utilisé il y a longtemps) !

Le questionnaire devrait être un peu plus précis, car le côté "à la louche" fait qu'il est impossible de passer en dessous de 2 tonnes à moins d'être sdf. Rien que le chauffage d'un appartement en coloc' fait passer au-dessus de 2 tonnes, à cause de la part incompressible des "services publics" (est-on tous égaux dans la consommation de service public ? probablement pas).

Ceci dit si le but est de faire prendre conscience aux gens qu'ils consomment trop c'est sans doute réussi.

Bonne journée.

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, à l'heure actuelle il est impossible de passer en dessous des 2 tonnes. Rien que l'impact carbone des services publics représente 2 tonnes.
C'est là tout l’enjeu de la transition au sens large. Induire des changements de comportements à l'échelle de l'individu mais aussi prendre conscience que la réduction globale de nos émissions (i.e. à l'échelle nationale) passera par des changements structurels profonds. Ces derniers ne peuvent se faire sans la participation des citoyens mais loin de nous de vouloir leur faire porter l'ensemble du poids de la transition. Ils ont une part à jouer dans la transformation de notre société vers une alternative bas carbone. Elle est nécessaire mais malheureusement pas suffisante. 
Pour approfondir : http://www.carbone4.com/wp-content/uploads/2019/06/Publication-Carbone-4-Faire-sa-part-pouvoir-responsabilite-climat.pdf

**Comment by laem** [comment]
Pour les services publics : 1,1 plus exactement : https://nosgestesclimat.fr/documentation/services-publics

Ce qui laisse une marge de ~1 tonne, ce qui est en effet faible, mais pas impossible.
