### ISSUE TITLE
Remarques générales

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#281]
Pour les appareils électroménagers / électroniques, différencier les appareils de deuxième main et les achats neufs (téléphonie, TV, appareil photo, etc). Idem pour les vêtements
Pour l'alimentation, aucun détail / distinction sur la provenance / origine des produits (local ou importé) ; traitement du poisson (viande / pas viande ?)
Pour le petit déjeuner, manque une autre proposition : fruits seuls / thé

Autrement super projet ;)

**Comment by laem** [comment]
Merci, c'est noté dans #185, et la section numérique / textile va être entièrement revue.
