### ISSUE TITLE
Précisions diverses

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#282]
Bonjour!

Déjà, le principal: être un peu moins européo-centré/tradi dans les ptits déjs possibles ;) : une quatrième option "autre" (ou salé/restes etc) serait bien (voir "autre végé" ET "autre animal")
Ensuite, rien de très très précis, j'imagine qu'on vous l'a déjà fait remonter mais s'il y a moyen d'être plus précis, quitte à réjouter des questions, ce serait cool! 

Quelques points qui me viennent à l'esprit:

- alimentation bio locavore saisonnière etc? (végé dans ces conditions ou pas, ça change pas mal l'empreinte carbone!! Idem pour si on inclut de la nourriture récupérée ou sauvage dans son alimentation et à quelle hauteur.)

- fournisseur d'éléctricité vert? (pas de bonus si on est chez enercoop?)

- pour les gens qui achètent du neuf, éthique/écolo un minimum quand même ou pas? Idem que pour la nourriture, ça compte…

- estimer d'une manière ou d'une autre la quantité de choses réparées/jetées… Même si on n'achète que de l'occasion, entre réparer/recoudre quand il y a un problème et mettre à la benne et retourner chez emmaüs, j'imagine qu'il y a une différence d'empreinte aussi…

- estimer d'une manière ou d'une autre la conso générale, ZD ou pas (par exemple via les dépenses par mois dans tel ou tel domaine — j'avais une fois utilisé un calculateur qui fonctionnait comme ça, bien intéressant), ce qui rejoint le point sur la nourriture "pas achetée" : l'empreinte carbone, par exemple, d'un shampoing solide utilisé tous les deux jours va quand même être plus élevé qu'une cuillère à soupe de bicarbonate tous les deux mois!

Voilà pour quelques idées!

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat est un outil qui se veut grand public. Nous limitons donc le nombre de question afin d'engager le plus grand nombre à la simulation. 
Concernant l'alimentation (petit-déjeuner). voir #185  Concernant, les animaux, il n'est pas pertinent de lister l'ensemble des types de viandes consommables quand l'enjeux principal du poste alimentation est la réduction de la quantité de viande consommée
Pour les reste, l'ensemble des questions sont traitées dans la F.A.Q
