### ISSUE TITLE
Le transport en commun est compté double

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#283]
Bonjour,

Le calculateur compte double le transport en commun : les heures de métro/tram et les heures de bus reprennent toutes les deux le temps complet de transport déclaré par l'utilisateur.

Il faudrait sûrement faire un ratio, ou demander si le temps de transport en question est du métro/tram ou du bus.

Sinon c'est très facile à utiliser, bravo. 

Autre question : que faites-vous des données collectées ?

Cordialement,
William

**Comment by Benjamin-Boisserie-ABC** [comment]
Le simulateur n'utilise pas le même nombre d'heure pour le métro/tram et pour le bus. Il y a bien deux questions.

Les réponses des utilisateurs ne sont pas collectées. Seules les données de connexion nécessaires à la tenue du simulateur sont utilisées (nombre de connexion, temps de connexion, taux de complétude, etc.)
