### ISSUE TITLE
Une API publique de pesage en CO2, SVP !

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#284]
En tant que salarié d'une entreprise, je cherche une API qui pour plusieurs info en entrée (type=déplacement, mode=métro, de=Vaugirard, à=Montparnasse) m'évalue par un organisme officiel le poids en CO2. Cela nous permettrait d'évaluer les gains possibles et de guider une politique d'amélioration individuelle comme globale si l'affichage était généralisé pour les marchandises comme pour les services.

**Comment by Benjamin-Boisserie-ABC** [comment]
Les transporteurs de marchandises (routier, ferroviaire, aérien) sont dans l'obligation de vous renseigner le poids carbone de leur transports.
S'il s'agit d'une estimation de l'empreinte de vos déplacements ce simulateur peut peut être vous être utile : https://ecolab.ademe.fr/apps/transport 
Si vous souhaitez approfondir et affiner l'évaluation des émissions de GES associées à une activité professionnelle, la méthode du Bilan Carbone est probablement celle qu'il vous faut. Plus d'infos ici : https://www.associationbilancarbone.fr/se-former/
