### ISSUE TITLE
Simplicité au prix de l'imprécision

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#285]
Chauffage habitation, la température des pièces de vie et couchage est essentiel, vie 19/20° et chambre16/17° fait une grosse différence avec ceux qui surchauffe 25°salon, 20°chambre. Idem si le logement est une passoire ou un bbc++
Alimentation , trop vague , il faut pouvoir quantifier plus précisément, tout se que l'on consomme est pesé, portioné, donc quantifiable.
Matériel, habillement, le prix ne démontre rien, dissocier les matières, la durée de vie moyenne(mode ou usure jusqu’à la corde), type de produit chaussure cuir de bonne facture ou basket 1er prix, idem meuble bois massif ou aggloméré merdique. 
Conclusion, ce calcule est une démarche personnelle qui doit etre le plus complet possible ,meme si long à faire , j'aimerais disposer d'un site qui me permette un calcul sur an, à remplir de manière hebdomadaire voir journalière, selon ma liste de course, mes conso réelles, une sorte de "cahier de bord", etc

**Comment by robinparisi** [comment]
L'unité utilisée étant le kWh, la température n'est pas utile pour le calculateur (au final, une température plus élevée pour une habitation donnée résultera sur une consommation plus élevée).

Pour le reste, il me semble que le but est avant tout de proposer un ordre de grandeur tout en proposant aux utilisateurs de remplir rapidement leurs informations pour se rendre compte des différents postes. Vous pouvez procéder par vous-même à une estimation plus précise grâce à la base carbone de l'ADEME par exemple : https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/index

**Comment by Benjamin-Boisserie-ABC** [comment]
Comme expliqué par @robinparisi , l'objectif de Nos Gestes Climat est de fournir un ordre de grandeur général et d'embarquer le plus grand nombre d'utilisateurs à la simulation. Pour ce faire nous avons choisi de limiter le nombre de questions à l'essentiel. 
Néanmoins, sachez qu'il existe des applis bancaires et des sites dédiés au monitoring de votre empreinte sur le climat. Probablement que ces solutions seront plus adaptées à ce que vous recherchez.
