### ISSUE TITLE
Plusieurs voitures

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#286]
Je trouve qu'il manque des questions pour mieux cerner l'impact carbone de deux choses : 
- les transports : on peut poser la question du nombre de véhicules, et pour chaque véhicule le nombre de km parcourus et l'âge (quelqu'un peut avoir un véhicule thermique et un électrique par exemple)
- l'alimentation : il faudrait demander la localisation des aliments (français, local, n'importe) ainsi que leur degré de transformation (pas le même impact si on ne mange que des produits transformés de manière industrielle que si on n'achète que des produits de base)
Je pense que ces deux facteurs peuvent avoir un impact important sur le bilan carbone.

**Comment by laem** [comment]
Pour la nourriture, voir #185 .
Pour les voitures, ce n'est pas encore d'actualité, nous avons des choses plus importantes à fixer, mais c'est noté :)
