### ISSUE TITLE
Vivre dans son vehicle

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#287]
Je vis dans un camion depuis 6 ans. Mon camion est équipé de panneaux solaires qui me permettent de recharger mon telephone, mon appareil photo et mon ordinateur et d'avoir de la lumière. Je n'ai aucun autre appareil electromenager (pas de frigo). Puisque mon vehicle est ma maison, je choisis de cocher l'option "je n'ai pas de voiture" puisque l'option "je n'ai pas de logement" n'est pas disponible. Cela serait bien d'inclure une option qui permettent aux personnes sans logement de calculer leur empreinte. Aussi, le chauffage dans mon camion marche au propane. Une bouteille de 20kg dure 2 semaines en hiver et 3-5 mois en été. L'approximation en facture mensuelle est bien plus haute que ce qu'elle devrait être parce que le prix du propane en bouteille est bien plus élevé que si on était raccordé au réseau.

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat se veut être un outil grand public destiné à engager le plus grand nombre à la simulation. Nous ne pouvons malheureusement pas prendre ne compte l'ensemble des cas particuliers sans complexifier l'outil et le nombre de questions. 
Je vous invite tout de même à consulter les données de la Base Carbone https://bilans-ges.ademe.fr afin d'évaluer l'empreinte de votre consommation de gaz. Vous pourrez ainsi additionner votre évaluation au reste de l'estimation du simulateur
