### ISSUE TITLE
Remarques diverses : compost, occasion, produits d'entretien, cosmétiques, potager, local

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#290]
Super calculateur, gros coeur sur la facture d'électricité, sinon est-ce possible de rajouter compost et achat de seconde main?
Concernant les produits d'entretien et pour se laver, je ne sais pas si ça impacte beaucoup
Faire son petit potager aussi, acheter plutôt en local aussi

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant l'impact de la seconde main voir la réponse apportée dans la F.A.Q
Concernant les autres pistes proposées, nous travaillons au développement d'un volet action qui intégrera très probablement (à terme) nombre de ces petites actions
