### ISSUE TITLE
Inclure le travail

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#291]
Il faudrait prendre en compte le travail. Bien que celui-ci ne soit pas modifiable à cour termes pour certains, c'est un moyen de se représenter son impact en tant que salarié. C'est quand même ce que l'on pratique 1/3 de notre temps donc il me semble que ce soit non-négligeable. Par exemple, j'ai une démarche personnelle bas carbone (végétarien, peu d'achat, déplacement en train...) mais mon travail consiste à construire des bâtiment neuf, la plupart du temps en béton. J'aimerais connaitre le poids de mon travail dans ma balance carbone.
Belle initiative sinon! C'est hyper clair et super simple à faire! 
Merci beaucoup :)

**Comment by robinparisi** [comment]
De mon point de vue, l'individu n'est pas "responsable" de l'impact carbone lié à son travail. Ce bilan doit être imputé à l'entreprise et faire l'objet d'une comptabilité carbone dédiée, ce que l'entreprise peut faire volontairement au travers d'un site comme celui de l'ADEME par exemple (https://www.bilans-ges.ademe.fr/fr/bilanenligne/bilans/index/siGras/0).

Dans tous les cas, cet impact est ensuite réimputé au consommateur final : disons que j'achète un ordinateur, dans l'idéal, c'est à l'entreprise de tenir une comptabilité carbone puis de pouvoir me dire que l'ordinateur que je viens d'acheter équivaut à tel impact (en prenant en compte l'ensemble de son cycle de vie, depuis l'extraction des matières premières jusqu'à l'élimination en fin de vie). Au final, ce ne sont pas aux salariés de l'entreprise de supporter ce coût carbone, mais bien aux consommateurs finaux.

**Comment by Benjamin-Boisserie-ABC** [comment]
L'impact carbone dans le cadre du travail relève de la responsabilité de l'employeur et non de l'individu. C'est donc à l'entreprise d'effectuer un Bilan d’Émissions de Gaz à Effet de Serre (BEGES) afin de connaitre et se rendre compte de son empreinte sur le climat. Nos Gestes Climat s'intéresse seulement aux choix personnels de l'utilisateur. Néanmoins comme expliqué nos empreinte carbone sont influencées (et donc plus ou moins carbonées) par les pratiques des entreprises. L'individu peut (dans une certaines mesures) choisir de soutenir certaines pratiques mais il ne peut pas s'en attribuer la responsabilité des émission.
Si vous voulez connaitre l'impact GES de votre entreprise, vérifiez si cette dernière a effectué un Bilan d'Emissions de Gaz à Effet de Serre. Si ce n'est pas le cas, elle peut se tourner vers des outils de comptabilité carbone dédiés. Plus d'infos : https://www.associationbilancarbone.fr/se-former/
