### ISSUE TITLE
Approfondir certains paramètres

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#293]
Bonjour,

Concernant la rubrique "repas", il serait peut être utile de laisser le nombre de repas à attribuer dans une semaine libre - le nombre actuel minimum étant bloqué à 14 repas pour une semaine. 

Pour illustrer cette remarque : nous vivons à 3 dans une maison, nous mangeons tous un repas par jour uniquement. 

Concernant la rubrique "Achats", une bonne idée (mais compliqué au niveau du calcul) serait d'ajouter une question concernant les achats des équipements neufs en ligne et de quelle région de la planète (Asie, USA, Europe...) afin de prendre en compte l'impact du transport des achats. 

Un grand merci pour cette initiative très intéressante !

**Comment by Benjamin-Boisserie-ABC** [comment]
La nouvelle version du simulateur donne la possibilité de ne pas renseigner 14 repas par semaine.

Les ratios monétaires de la rubrique Achat prenne en compte une distance moyenne de transport. Pour compléter voir la réponse apportée dans la F.A.Q
