### ISSUE TITLE
Pas adapté pour les personnes qui sont déjà à 2t ou moins

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#295]
Par exemple je n'utilisé aucun système de santé et n'en utiliserai pas car ce n'est pas du tout ma méthode de soin celle ci étant basé sur une approche spirituelle de la perception de la vie. Je n'ai et n'aurai jamais recours à la justice ou tout autre système du genre. Juste j'utilisé la route mais jamais autoroute ou même national. Pour l'alimentation vous ne considérez pas la possibilité de ce nourrir par soi même voir l'agradation qu'un humain peut avoir pour le sol. Par exemple l'ensemble de tout ce qui ressort de moI retourne toujours au sol par mes moyens et dans de bonne condition pour le sol. 
Enfin comme je le dis dans le titre votre test est fait pour des personnes consommant plus que 2t.
Il faudrait aussi considérer le fait de recycler dans son usage de vie ce qui irait à la destruction 
Merci pour ce test et bon courage.

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat se veut être un outil grand public et généraliste qui reflète (par ses questions) les modes de vie moyens. Nous ne pouvons donc pas intégrer tous les cas particuliers sans complexifier l'outil et le nombre de questions
