### ISSUE TITLE
chauffage collectif

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#297]
Bonjour, 
sauf erreur de ma part, l'option chauffage collectif n'est pas proposée.
le chauffage a des impacts non négligeable sur le bilan final.
Bien cordialement

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, l'option chauffage collectif n'est pas intégrée. Néanmoins, nous avons introduit l'approche par prix qui peut s'avérer utile pour votre cas (même si cela reste très  approximatif) en divisant la facture collective par le nombre d'habitants ou par les m2 chauffés.
