### ISSUE TITLE
Prise en compte du covoiturage

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#299]
Bonjour.
Juste une petite suggestion :
J'ai fait une simulation d'empreinte CO2 et je n'ai pas trouvé d'option pour prendre en compte le covoiturage. J'ai fait le choix de ne pas posséder de voiture, donc je me déplace exclusivement en train ou en covoiturage. Par honnêteté j'ai fait un rapide calcul des km parcourus, mais le fait que l'application n'ait pas d'autre choix que de considérer qu'il s'agit de ma voiture personnelle fait grimper la facture CO2 et je trouve cela dommage. 
Si vous pouviez ajouter l'option covoiturage, ça serait top :)
Merci et bonne continuation !

**Comment by Benjamin-Boisserie-ABC** [comment]
La version actuelle du simulateur demande en effet de renseigner les caractéristiques de la voiture à partir du moment ou une distance parcourue en voiture est renseignée et ce même si vous ne possédez pas de voiture. En effet, même si le covoiturage permet de limiter son impact sur le climat, il génère tout de même des émissions de GES. C'est pour évaluer ces émissions (et vous en attribuer une partie) que les questions sur les caractéristiques de la voiture sont posées
