### ISSUE TITLE
Carburant

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#308]
Bonjour 
Hésitez pas à vous renseigné aussi sur le coût énergétique suivant les pays.
Par exemple je vie à Tokyo, nos bus sont à hydrogène. Les calculs pour les transports devrais aussi prendre en compte le type de véhicule (diesel, essence, électrique) pareil pour les trains.
Niveau consommation de la maison. Prenez aussi en compte la climatisation.

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat est un simulateur destiné à l'évaluation de son empreinte carbone en France.
La différence électrique thermique est bien faite pour les véhicules
La question des carburants est traitée dans la F.A.Q
La climatisation est prise en compte dans la consommation d'électricité (même si à l'heure actuelle les fuites résiduelles de fluides frigorigènes ne sont pas prises en compte)
