### ISSUE TITLE
Velo

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#309]
Il manque le transport vélo et à pied.
Il manque une section loisir et sport ( certain sont très polluants)
Il manque une estimation des depots aux dechetteries
Et enfin la conso en eau

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant les mobilités actives, voir #74
Concernant les loisirs et le sport voir la réponse donnée en #252 
L'aspect recyclage des déchets sera traité dans le volet action en cours de développement
Nos Gestes Climat traite de l'aspect carbone uniquement. L'aspect impact environnemental n'est pas dans les priorités actuelles même si la préservation de la ressource en eau est tout autant essentiel
