### ISSUE TITLE
Conso streaming

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#311]
Hello, j'ai adoré faire mon bilan mais j'ai un peu tique sur le bilan numérique : passer 8h/jour à alterner entre mails et réseaux sociaux est il équivalent à une journée de binge watching sur Netflix ou au téléchargement d'une série en torrent ou d'une journée passée sur YouTube ?

**Comment by Benjamin-Boisserie-ABC** [comment]
L'impact du numérique souffre de nombreuses approximations du fait du manque de données sur cette thématique. Nous cherchons toutefois à affiner l'impact carbone de ce poste.
Se référer à #56
