### ISSUE TITLE
opérateur d'électricité verte

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#313]
Pourriez vous prendre en compte le fait que l'on soit abonné à un opérateur d'électricité verte (pour ma part Enercoop).

**Comment by hokkos** [comment]
Le fait d'être abonné à un opérateur ayant acheté des garanties d'origine ne change en rien l'intensité carbone que vous utilisez. Ces GO sont achetées sur une bourse, et peuvent être consommées jusqu'à 1 an après l'émission et partout dans le secteur ENTSO-E, il y en a très peu issue en France à cause des règles fiscales interdisant de cumuler subventions ENR et émission de GO. Bref non, ce serait un très mauvaise idée tant que le système n'est pas ajusté au pas horaire et localisé dans le pays d'habitation.

**Comment by laem** [comment]
C'est très juste. Voir la #170 que je n'ai toujours pas mis en ligne, pour éviter ces redites ...
