### ISSUE TITLE
banque éco responsable

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#314]
Pourriez vous prendre en compte le fait que l'on soit hébergé par une banque éco responsable (pour ma part le Crédit Coopératif).

**Comment by Benjamin-Boisserie-ABC** [comment]
L'impact carbone de son épargne est en effet dépendant de la banque choisie. Même si nous pourrions poser cette question, il nous faudrait poser également la question sur le montant de l'épargne, chose que nous ne souhaitons par faire.
Néanmoins, le volet action intégrera une action portant sur l'impact des banques et de son épargne

**Comment by laem** [comment]
En complément, intégrer l'empreinte de la finance poserait un problème de double comptabilité : https://github.com/betagouv/ecolab-data/issues/24#issuecomment-638177378

**Comment by Benjamin-Boisserie-ABC** [comment]
On devrait pouvoir s'affranchir du double comptage en raisonnant sur les flux (i.e. rémunération de l'épargne, taux de rendement, etc.) plutôt qu'en raisonnant en montant absolu. A confirmer tout de même. De toute faàon c'est s'embêter pour des questions qu'on ne souhaite pas poser et qu'on traitera sur le volet action par un message de sensibilisation à l'impact de son épargne
