### ISSUE TITLE
Manger bio et local, choisir notre consommateur d'électricité

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#315]
Bonjour,
Je souhaitais vous indiquer qu'il est dommage de ne pas prendre en compte d'où vient notre nourriture ou notre énergie.
J'ai effectivement indiqué ma consommation de viande et de légumes, mais je n'ai pas pu préciser que celle-ci est à 100% produite localement et bio (AMAP).
Je passe par Enercoop qui s'engage à créer de l'énergie renouvelable pour l'électricité. C'est un critère important pour moi de réduction de CO2 et il est intéressant de pouvoir le valoriser.
Enfin, nous avons 1 voiture pour 2, je me déplace en vélo, à pied et en bus, et pourtant le taux de déplacements en voiture de mon foyer est énorme. J'ai indiqué qu'un seul passager prenait la voiture, j'aurais peut-être du mettre 3 pour être plus réaliste. A préciser aussi je pense.
Sinon merci pour ce site, c'est très intéressant de se poser ces questions !

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant l'alimentation bio/locale/etc. ainsi que pour l'électricité renouvelable se référer à la F.A.Q
Concernant les déplacements en voiture, cela revient à considérer une approche foyer (que nous souhaitons développer). Voir #113
