### ISSUE TITLE
Nouvelle section "Nombre d'enfants"

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#317]
Pourriez-vous ajouter une section "Nombre d'enfants" ?
Faire un enfant est de loin la plus grande source de production de C02.
C'est un sujet grave qui touche au plus profond de chacun de nous, je comprend que ça puisse choquer/gêner mais ça me semble indispensable de le prendre en compte dans vos calculs si on veut rester objectif.
https://iopscience.iop.org/article/10.1088/1748-9326/aa7541/pdf

**Comment by Benjamin-Boisserie-ABC** [comment]
Se référer à #88
