### ISSUE TITLE
Impressions

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#318]
Les questions me semblent trop vagues et assez inadaptées aux contextes personnels. Mais, merci quand même de la démarche, ça donne une idée.

**Comment by Benjamin-Boisserie-ABC** [comment]
NGC se veut être un outil grand public. Il cherche donc être simple d'utilisation en limitant le nombre de questions afin d'embarquer le plus grand nombre à la simulation. Les questions posées couvrent cependant la quasi totalité des postes d'émissions d'un individu. N'hésitez pas à contribuer sur le modèle pour proposer des améliorations si vous en avez : 
https://github.com/betagouv/ecolab-data/blob/master/CONTRIBUTING.md
