### ISSUE TITLE
La taille des smartphones 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#321]
Aujourd'hui quasiment tous les smartphones ont des écrans de plus de 5 pouces. Sans doute trop de choix de réponse malheureusement.
Mais les technologies d'affichage Oled consomment un peu moins.

**Comment by Benjamin-Boisserie-ABC** [comment]
Nous nous basons sur les données de la Base Carbone et nous reprenons donc la terminologie. La Base Carbone est amenée à être compléter par d'autres facteurs d'émissions. Nous adapterons alors les questions en conséquence
