### ISSUE TITLE
Ajouter une question sur la quantité de data mobile consommée

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#323]
Beaucoup connaissent l'enveloppe data de leur forfait. L'impact en émission peut se calculer avec  Mobile Carbonalyser
: https://theshiftproject.org/carbonalyser-extension-navigateur/

**Comment by Benjamin-Boisserie-ABC** [comment]
L'estimation de l'impact du numérique souffre du manque de données. Nous tacherons de mettre à jour les données et les éventuelles questions quand plus de données seront disponibles.
Par ailleurs, nous mettons bien en avant l’extension Carbonalyser dans les actions proposées.

**Comment by laem** [comment]
Attention, les chiffres de carbonalyser, qui sont ceux de la 1ère étude du Shift à ma connaissance, sont très contestés.
