### ISSUE TITLE
Manque l'impact lié aux services financiers

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#324]
Votre calculateur est très bien fait, simple à remplir, notamment avec les propositions pour faciliter la saisie. Merci !

Mais après avoir testé plusieurs calculateurs, je trouve celui de MicMac plus pertinent car il inclut aussi la partie lié au services financiers (en revanche le calcul est basé sur une étude qui date de 2010)

On a hâte de voir les propositions d'actions !!! (comme le calculateur Carbo).

Pour info, en parallèle de notre bilan carbone entreprise, nous allons pousser votre calculateur auprès de nos 700 salariés en France, pour les inciter à calculer leur empreinte carbone individuelle et à mener des actions de réduction.

**Comment by Benjamin-Boisserie-ABC** [comment]
L'impact carbone de son épargne est en effet dépendant de la banque choisie. Même si nous pourrions poser cette question, il nous faudrait poser également la question sur le montant de l'épargne, chose que nous ne souhaitons par faire.
Néanmoins, le volet action intégrera une action portant sur l'impact des banques et de son épargne
