### ISSUE TITLE
il manque le compost!!!

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#327]
J'ai un compost, ce qui est vertueux et je ne peux pas le mettre en valeur :)))

**Comment by Benjamin-Boisserie-ABC** [comment]
La gestion des déchets est en partie pris en compte avec la question "mode de vie zéro déchet".
Qui plus est le volet action (toujours en cours de développement) aborder la notion de compostage des biodéchets/déchets verts
