### ISSUE TITLE
Présentation des résultats

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#328]
Bonjour,

Le test est super ! Simple à compléter et très clair.
Je trouve par contre cela un  peu dommage que l'on ai pas un peu plus d'infos sur les résultats : 
- comparaison avec l'empreinte d'un français moyen et avec l'objectif poste par poste
- décomposition des postes : par exemple pour le transport voir la part de l'avion, etc.

In fine, cela rendrait l'analyse encore plus pertinente et actionnable pour tous

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant la comparaison par poste avec la moyenne française, la remarque est prise en compte en #868 
Concernant la décomposition par poste il suffit de cliquer sur le post souhaité pour voir apparaitre la part de chaque mode de transport
