### ISSUE TITLE
électro-menager achat occasion à pouvoir indiquer

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#331]
Ce serait bien de pouvoir préciser si l'achat est d'occasion ou neuf, selon moi, cela change le bilan. 
Pareil pour la voiture cela dit 
Bon travail!

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, les produits d'occasion sont moins impactant que des produits neufs.
Le simulateur pose maintenant la question sur les produits **neufs** achetés
