### ISSUE TITLE
L'empreinte carbone de notre activité

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#333]
Certaines activités, pro (efficacité énergétique ou extraction pétrolière) ou hobbys (sports mécaniques, golfs me viennent en tête immédiatement), peuvent avoir une incidence non négligeable sur l'empreinte. Evidemment, la prun hobby est sans doute plus facile à évaluer que l'activité pro !

**Comment by Benjamin-Boisserie-ABC** [comment]
Les activités professionnelles ne sont pas à évaluer avec l'outil Nos Gestes Climat. En effet, ce dernier se focalise sur l'aspect personnel et non professionnel. L'aspect professionnel et l'impact sur le climat associé relève de la responsabilité de l'entreprise et non des choix des individus.
Concernant les hobbys, la remarque est prise en compte en #252
