### ISSUE TITLE
Suggestion question

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#334]
—> Pourcentage de votre nourriture non transformée que vous cuisinez, en vous approvisionnant chez des primeurs / marchés.. etc 

—> si vous consommez de la viande, ou l’achetez vous :
- supermarché 
- chaîne de surgelés 
- Boucherie indépendante 
- Chaîne de boucherie (type boucherie André)p

—> la nourriture transformée à un impact considérable sur le changement climatique

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat dans le cadre du développement action va chercher à quantifier l'impact des produits transformés/surgelés en se basant notamment sur les données de la base Agrybalise : https://www.agribalyse.fr/app
