### ISSUE TITLE
Zoé

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#335]
Bonjour,
je viens d'acheter une Zoé.
Au moment où j'ai cliqué sur "voiture électrique" puis "neuve" ça m'a mis 6 tonnes de CO2.
Est-ce que c'est son empreinte carbone totale que vous comptez sur la 1ère année ou un amortissement sur plusieurs années ?
ça me plombe grave mon empreinte ;-)
Merci,
Laure

**Comment by Benjamin-Boisserie-ABC** [comment]
L'empreinte carbone liée à l'achat d'un véhicule électrique ou thermique est maintenant amortie avec la nouvelle version du simulateur
