### ISSUE TITLE
Electricité

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#337]
Bonjour,
Pourriez vous ajouter une option permettant d'indiquer si on produit ou non sa propre électricité (solaire ou éolienne) ?
Merci

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat se veut être un outil grand public qui permet d'engager le plus grand nombre d'utilisateur possible à l'évaluation de leur empreinte sur le climat. Nous nous basons donc sur les systèmes énergétiques les plus courants et nous ne pouvons pas prendre en compte de nombreux cas particuliers sans complexifier le calcul et le nombre de questions.
