### ISSUE TITLE
Prise en compte de compensation carbone

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#339]
Peut être qu’une façon de visualiser la compensation carbone pourrait être intéressante lorsqu’on partage nos résultats :)

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat a pour finalité l'évaluation mais surtout la réduction de l'empreinte carbone de l'utilisateur (le volet action est en cours de développement). La finalité de la compensation au vu des controverses qu'elle suscite (même s'il elle trouve ça place dans une démarche  de compensation des **émissions résiduelles**) n'est pas mise en avant afin de ne pas inciter à la compensation en lieu et place de la réduction réelle de son empreinte carbone
