### ISSUE TITLE
Utilisation voiture

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#342]
Il est difficile de savoir à l’avance qu’on nous demandera combien de personne sont en moyenne dans la voiture après avoir remplis le nombre de kilomètres.

Peut être que pouvoir remplir sur la même page “2000km seul, 3000km a 2 en moyenne” serait plus pratique et précis

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat se veut être un outil grand public, facile d'utilisation et engageant le plus nombre au passage à l'action. En ce sens, nous avons choisi de limiter le nombre de question afin d'engager le plus d'utilisateurs possibles vers la simulation.
Qui plus est, approximer le nombre de voyageurs moyens (en une seule question) permet tout de même une estimation pertinente de l'empreinte carbone liée à l'utilisation de la voiture
