### ISSUE TITLE
Logement

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#347]
Je viens de finir le test et je me demande si un info a bien été prise en compte : j'a indiqué payer 50€ d'élec/mois et habiter à 4 personnes dans ma maison. Cependant c'est une colocation et les 50€ sont juste ma part, pas à diviser par 4. Il faudrait juste préciser la question de la consommation : "combien consommez-vous personnellement", ou"combien votre foyer consomme-t-il ?"

**Comment by laem** [comment]
Merci pour cette remarque super précise. Je corrige. On avance :)
