### ISSUE TITLE
Suggestion logement

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#348]
la rubrique logement me semble beaucoup trop sommaire
il faudrait distinguer habitat individuel/collectif. la forme de la maison (1 étage ou de plein pied uniquement, conso différente
il faudrait la date de construction : conso d'energie très différente
peut etre ajouter la région (paca ou est de la france, pas la meme conso)

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat se veut être un outil grand public, facile d'utilisation et engageant le plus nombre au passage à l'action. En ce sens, nous avons choisi de limiter le nombre de question afin d'engager le plus d'utilisateurs possibles vers la simulation.
Par ailleurs, nous demandons directement de renseigner la consommation. Ainsi rajouter, des questions sur le type d'habitat ou la localisation ne ferait que complexifier le modèle.
Nous réfléchissons, en revanche, à introduire une question sur l'age du logement afin de considérer un amortissement
