### ISSUE TITLE
suggestion alimentation

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#349]
le choix me semble trop général
il faudrait avoir la possibilité de dégager une rubrique laitage/fromage
il faudrait aussi distinguer la conso de surgelé
peut etre aussi demander l'information sur la provenance : plutot local, français, ou étranger
faudrait il ajouter une rubrique poisson.?

**Comment by laem** [comment]
Merci pour vos remarques, elles sont notées dans #185 .
