### ISSUE TITLE
suggestion numerique

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#350]
il faudrait apporter des infos sur l'utilisation du numérique: personnellement je ne vais jamais sur netflix et très peu sur youtube. j'imagine que mon empreinte carbone est plus faible que la moyenne. il faudrait aussi faire des précisions sur les portables: periodicité de renouvellement, achat neuf ou reconditionné

**Comment by Benjamin-Boisserie-ABC** [comment]
L'évaluation de l'impact carbone du numérique et plus particulièrement du streaming de vidéo en ligne souffre du manque de données à disposition.
Le volet action (en cours de développement) s’intéressera à la fréquence de renouvellement des objets (afin de pouvoir proposer des actions de types "allonger la durée de vie") ainsi qu'à l'achat d'occasion.
