### ISSUE TITLE
suivi des conso

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#351]
personellement ma référence pour la calcul du bilan carbone c'est coach carbone qui a malheureusement disparu. il faudrait avoir la possibilité d'ouvrir un compte pour sauvegarder un bilan carbone et pouvoir le comparer dans le temps ou alors plus simplement avoir la possibilité de sauvegarder le bilan sur son ordi. 
enfin, il faut une rubrique suggestion : des conseils pour améliorer son bilan carbone dans les domaines où on peut progresser. peut etre aussi de la pédagogie : pourquoi tel comportement est vertueux et pourquoi tel autre ne l'est pas

**Comment by hellomedia** [comment]
Tout à fait d'accord !

Est-ce que ça fait partie des objectifs ce projet ?

NB: Le calculateur d'emprunte carbonne tel qu'il existe actuellement est quand-même très bien fait ! j'aime beaucoup :)

**Comment by Benjamin-Boisserie-ABC** [comment]
L'objectif de Nos Gestes Climat au delà du calculateur est de proposer de nombreuses actions pour réduire son empreinte carbone. Un volet action est en cours d'élaboration
A longue échéance, nous aimerions aussi pouvoir proposer une sauvegarde et un suivi de ses propres bilans
