### ISSUE TITLE
Bien mais...

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#355]
Super outil.
Petites remarques : pour le fioul, demander en kWh peut amener à des erreurs. 
Ne vaudrait-il pas mieux parler en litres (en général on connaît notre conso en litre) ? La possibilité de noter en € ne me paraît pas fiable (forte variation du prix / tout le monde ne l'achète pas au même prix).

Autre chose, il serait intéressant d'avoir à la fin la moyenne logement / alimentation ....  ça permettrait de se situer plus précisément.

Beau travail, merci. La partie explication des enjeux est vraiment top !

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant l'unité renseignée pour la consommation de combustible, voir #867 
Concernant la présentation de la moyenne nationale par poste, voir #868
