### ISSUE TITLE
Trop de clics

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#357]
Bonjour, dans le cadre d'un choix multiple à cliquer, je trouve redondant de devoir cliquer encore pour confirmer. Pourquoi ne pas mettre un bouton "retour à la question précédente" en cas d'erreur de clic ?

Cela dit, je trouve qu'il est très bien fait ! Merci !

**Comment by Benjamin-Boisserie-ABC** [comment]
Prise en compte de la remarque

**Comment by laem** [comment]
C'est un choix d'interface qui permet de comparer ses choix avec d'autres possibilités : je clique sur "thermique", puis sur "électrique", je vois la différence calculée.
