### ISSUE TITLE
Vehicule electrique et consommation elec

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#360]
Bonjour

Dans le cas d un véhicule électrique rechargé à la maison, il serait opportun de retrancher la consommation elecrrique liée au véhicule sinon celle-ci est comptabilisée 2 fois.

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, il y a bien double comptage dans le cadre d'un véhicule électrique rechargé à la maison. Cependant, le mix français étant faible carboné, cela ne représente au final qu'une légère surestimation de l'empreinte carbone
