### ISSUE TITLE
Remarque sur formulation question

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#361]
Bonjour,
Génial ce test! par contre la question sur la taille du smartphone, la taille en "pouces" ne parle pas à tout le monde: vous pourriez indiquer aussi en cm?

Et sinon à la fin du test on a très envie de comprendre quels aspects de notre vie ont fait le plus grimper le score... vous pourriez expliquer un peu les résultats individuels?

Bravo en tous cas!

**Comment by Benjamin-Boisserie-ABC** [comment]
La formulation sur la taille en "pouces" des smartphones résulte de la formulation utilisée dans la Base Carbone. Raisonner en cm ne simplifiera pas réellement les choses étant donné que les tailles seront très proches les unes des autres. Néanmoins nous prenons en compte cette remarque.
Par ailleurs, un volet action est en cours d'élaboration pour proposer de nombreuses actions afin de réduire son empreinte carbone
