### ISSUE TITLE
pre, post covid

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#364]
il serait super intéressant d'avoir des questions sur lesquels nous pouvons répondre deux fois : une réponse pré et une pour post covid. cela donnerait à réfléchir pour le retour à la "normale" :)

**Comment by Benjamin-Boisserie-ABC** [comment]
A l'heure actuelle, l'utilisateur devra effectuer 2 simulations. Il est aussi possible de venir modifier certaines réponses (en cliquant sur "modifier mes réponses" sur la partie haute de l'écran) et ainsi de constater l'impact que cela a sur son empreinte carbone.
A longue échéance, nous aimerions intégrer la possibilité pour l'utilisateur de sauvegarder certaines simulation afin de pouvoir les comparer
