### ISSUE TITLE
fin de test

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#366]
peut-être il pourrait y avoir des suggestions pour améliorer en fin de test, ou alors une champ libre sur les engagements de la personne qui a fait le test...
pour avoir de stats et pour engager la personne

**Comment by Benjamin-Boisserie-ABC** [comment]
Un volet "passage à l'action" est en cours de développement afin de proposer de nombreuses actions pour réduire son empreinte carbone
