### ISSUE TITLE
quantité co2 lié au public

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#367]
Bonjour, super test merci;

Seulement vous indiquez dans mon résultat 1,2t de co2 liés au public c'est à dire routes, ecoles etc. impossible donc de réduire cela. Impossible pour moi non plus de réduire sur l'alimentation à moins de sauter des repas, l'objectif de 2t de co2 me semble donc mathématiquement impossible.

Je partage votre test.

Cordialement

**Comment by Benjamin-Boisserie-ABC** [comment]
Réponse apportée en #278 

De plus, l'impact des services publics permet de mettre en avant que la transition et la réduction de nos empreintes carbone n'est pas un simple problème individuel mais bien un sujet qui doit être traité collectivement.
