### ISSUE TITLE
Age du téléphone 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#368]
Bonjour, on nous demande l'âge du téléphone, mais par exemple je peux avoir un téléphone depuis un mois alors que le dernier est mort au bout de 6 ans, c'est un peu biaisé. Pareil pour l'électroménager, on n'en achète pas chaque année et en même temps une machine à coudre à 500€ va tenir 30 ans ou plus si tout va bien.

**Comment by Benjamin-Boisserie-ABC** [comment]
Un volet "passage à l'action" est en cours de développement et cherchera à approcher ces notions de renouvellement afin de proposer des actions de type "j'allonge la durée de vie de mes objets"
Qui plus la question sur l'age du téléphone permet de considérer un amortissement du produit.

**Comment by laem** [comment]
Voir #816, c'est une question de fond complexe
