### ISSUE TITLE
Une question sur une consommation de proximité et de saison 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#370]
Peut être que pour le calcul de l'impact de l'alimentation il pourrait être intéressant de prendre en compte la provenance des produits et les saisons, ainsi que l'option du potager personnel ? Merci

**Comment by Benjamin-Boisserie-ABC** [comment]
Question sur la provenance des produits traitée dans la F.A.Q
Concernant la saisonnalité, voir #185
