### ISSUE TITLE
Lien entre surface du logement et CO2

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#377]
Je remarque que lorsque l'on faire varier la taille du logement et uniquement celle ci, la consommation de CO2 augmente, à part pour un logement neuf, je ne vois pas le lien.

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, un impact carbone est considéré pour tout logement du fait de sa construction. Nous réfléchissons à introduire un amortissement pour ne pas continuer à considérer un impact pour les très vieux logements.
