### ISSUE TITLE
Impact véhicule électrique

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#379]
Il n'est pas pris en considération l'usage d'énergie renouvelable pour la recharge de véhicule électrique ou pour l'alimentation en autoconsommation de la maison. De plus, il n'est pas pris en compte la fourniture d'énergie verte décarbonnée chez un fournisseur comme Enercoop pour la recharge du véhicule électrique du coup, le bilan est nettement plus élevé qu'il ne devrait l'être.

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant l'alimentation par des fournisseurs d'électricité "verte", se référer à la réponse apportée dans la F.A.Q
Concernant l'autoconsommation, Nos Gestes Climat est un outil grand public qui cherche à être simple d'utilisation. Il ne peut pas prendre en compte tous les cas spécifiques.
Si vous voulez réussir à intégrer l'impact d'une autoconsommation, vous pouvez renseigner 0 dans la consommation électrique. Cela est très approximatif étant donné que l'impact du cycle de vie des panneaux solaires n'est pas pris en compte, mais c'est une première approche
