### ISSUE TITLE
11 tonnes de CO2/an uniquement par le véhicule électrique est absurde

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#387]
11 tonnes de CO2/an uniquement par le véhicule électrique est absurde  car il est rechargé sur une borne dans mon garage et si non les bornes de recharge Tesla, TOUTES ALIMENTÉES EN ÉLECTRICITÉ 100% RENOUVELABLE!!! CAR J'HABITE EN SUISSE!!! Dont acte.

**Comment by laem** [comment]
Nous avons changé la méthode d'amortissement de la construction de la voiture. 
Cela dit, un véhicule d'1,5 tonnes n'est jamais "zéro émission" ;)
