### ISSUE TITLE
Amortissement véhicule

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#388]
Dans l'amortissement de la voiture, si je comprend bien vous divisez l'empreinte de la construction par l'âge actuel de la voiture... et pas par son espérance de vie (durée de vie moyenne d'un véhicule) ? Si c'est le cas, alors ce n'est pas cohérent : si je viens de changer ma vieille voiture de 12 ans par une neuve, vous partez du principe qu'elle n'aura jamais plus d'un an ? ;o)

**Comment by laem** [comment]
Voir #225
