### ISSUE TITLE
Resultats / numerique

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#390]
- Infographie / pourquoi les transports sont représentés par une voiture ? 
- est ce que le temps smartphone / tablette se déclarent dans ordi / internet ?
Merci.

**Comment by Benjamin-Boisserie-ABC** [comment]
Les transports sont maintenant représentés par un feu tricolore
Le temps de smartphone / tablette se déclare dans la question "Combien d'heures passez-vous par jour sur internet hors bureau (envoi de mail, surf Web, streaming vidéo, etc.) ?"
