### ISSUE TITLE
Produits reconditionnés/2nde main

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#394]
Bonjour,

Merci beaucoup pour ce formulaire très enrichissant. Je n'aurais qu'une suggestion, concernant les achats divers d'electromenager, de vetements ou autres, peut être serait il pertinent d'y ajouter une dimension avec les produits recondionné type back market pour l'electromenager (tel, ..) ainsi que les produits de secondes mains en textiles. Egalement, la partie bio/locale pour l'alimentation pourrait avoir un impact sur le bilan.

Mais j'imagine que vous travaillez déjà dessus.

Merci encore,
Clément

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant l'alimentation, la question est traitée dans la F.A.Q
Concernant les achats divers, le simulateur actuel demande maintenant de renseigner seulement les achats **neufs**
