### ISSUE TITLE
Rigolo, instructif, bien fait mais inutile en fait

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#395]
Merci pour votre appli. C'est ludique et bien fait. Maintenant comment atteindre les 2 tonnes/an si les services publics qui me sont imputées font déjà 1,2 tonne et que ma seule nourriture représente 3 tonnes ...

Donc là on se dit que c'est une appli pour zadiste décroissant et on se contente de partager son score avec les amis 😂

**Comment by laem** [comment]
> Merci pour votre appli. C'est ludique et bien fait. Maintenant comment atteindre les 2 tonnes/an si les services publics qui me sont imputées font déjà 1,2 tonne et que ma seule nourriture représente 3 tonnes ...

C'est la triste réalité. Sauf pour votre nourriture, dont l'empreinte peut être largement améliorée avec d'autres choix. 

Ce qu'on peut faire, nous : expliquer ce que veulent dire ces 1.2 tonnes de services publics :)  C'est prévu ! #3
