### ISSUE TITLE
Améliorer précision

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#397]
Bonjour,
Très bonne application, un point à améliorer : impossible sur cette version d'utiliser les virgules par exemple pour la consommation de carburant (ex : si l'on consomme 4.5L de carburant au 100km, que l'on renseigne 5L, arrondi, car impossible de mettre une virgule) cela fait tout de même 10% de différence.

**Comment by Benjamin-Boisserie-ABC** [comment]
La version actuelle du simulateur permet de renseigner une consommation avec une virgule
