### ISSUE TITLE
Imprécis et intrusif

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#402]
Quid de l'usage des informations personnelles pour estimer la consommation (Rgpd ?) 
Très imprécis car ne prends pas en compte certains éléments :
Le type de radiateur électrique et leur âge, l'isolation thermique du bâtiment, le nombre d'équipements numériques, le type de carburant et les nouveaux usages (télétravail, personne travaillant à domicile à son compte), la situation géographique si en zone rural ou urbaine... Bref, ça fausse beaucoup de choses et cela mériterait d'avoir connaissance de la méthodologie utilisée pour plus de transparence. Par exemple un véhicule électrique consommera moins d'essence mais n'est pas écologique s'il possède une batterie (leur recyclage est quasi impossible actuellement donc pas écologique).

**Comment by laem** [comment]
> Quid de l'usage des informations personnelles pour estimer la consommation (Rgpd ?)
Le bouton "Vie privée" sur l'accueil vous répond...
N'hésitez pas si vous avez d'autres questions.

**Comment by laem** [comment]
Questions brouillonnes et toutes mélangées, la plupart déjà notées ou non pertinentes : télétravail ? renseignez moins de km en voiture; situation géographique, urbain ou rural ? Pas pertinent pour la mesure des émissions, sauf à moduler le poste service public, chose qu'on ne peut pas faire pour l'instant, voir #3
