### ISSUE TITLE
Ajout d'autres critères 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#407]
Bonjour,
La consommation de produit d'hygiène peut avoir un impact : bouteilles plastiques, cotons tiges, cotons, brosses à dents.
Je ne sais pas si le poids est important  mais l'inclure permettrait de sensibiliser les personnes.
En parallèle,  je n'ai pas compris si dans le textile,  vous incluez les chaussures.

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant l'impact des produits d'hygiène, une grande partie provient des emballages et sont donc évalués avec la question sur le mode de vie zéro déchets.
Concernant la précision que le terme textile inclue les chaussures, cette remarque est pris en compte
