### ISSUE TITLE
incohérence dans la rubrique "Numérique"

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#410]
"ordinateur fixe" ? je réponds non, l'écran suivant me demande "quel âge a-t-il" ! dois-je faire comme si j'avais un ordinateur fixe pour pouvoir continuer ?

**Comment by Benjamin-Boisserie-ABC** [comment]
La question sur l'ordinateur fixe permet de savoir de savoir si l'on parle d'un PC portable ou d'une PC avec une tour. Vous avez au préalable répondu que vous possédiez un ordinateur. la question sur l'âge est donc normal

**Comment by laem** [comment]
On précise maintenant dans les questions : "quel âge a [l'object]" :)
