### ISSUE TITLE
EMPRUNTE CARBONE ALIMENTATION 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#414]
bonjour
Le poisson est inexistant dans vos menus !! - ou est ce un aliment non autorisé?
pourquoi 3 repas par jour, à titre personnel c'est 1 pdj et un repas par jour largement suffisant pour faire 2000 kcal/jour !!! 
Cdt

**Comment by laem** [comment]
Voir #185 
et #207
