### ISSUE TITLE
Rien sur le vélo

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#415]
La rubrique « transports » se réfère aux conducteurs de voiture vs. les usagers de transport en commun. Impossible de se retrouver dans les questions si on utilise à 99% le vélo pour les déplacements quotidiens. Merci d’en revoir compte et bravo pour cette initiative !

**Comment by martinregner** [comment]
Les modes de transport qui n'émettent pas de gaz à effet de serre ne sont pas comptés. Pour en savoir plus et comparer les modes de transport, nous vous suggérons de regarder le simulateur transport : https://ecolab.ademe.fr/transport
