### ISSUE TITLE
Calcul

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#417]
Ma famille possède un bois de 3 hectares 
Votre calcul n en tiens pas compte
Merci
José

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat est un outil grand public qui cherche à être simple d'utilisation. Pour cela nous cherchons à limiter le nombre de questions afin d'engager le plus grand nombre d'utilisateur au calcul de leur empreinte carbone. Il ne peut donc pas prendre en compte tous les cas spécifiques propres au logement
