### ISSUE TITLE
Jus de fruit

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#420]
Votre question sur le jus de fruit peut être assez réductrice.
Pour ma part je bois du jus de pomme que je ramasse (verger délaissés), qui est pressé d'en un pressoir associatif à quelques kilometres. Ainsi je ne pense pas être à 700K concernant le jus.

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat est un outil grand public qui cherche à être simple d'utilisation. En ce sens, nous ne pouvons coller aux particularités de chacun. Le facteur d'émission utilisé pour évaluer l'impact de la consommation de jus est celui de la base carbone et se base sur la moyenne que l'on trouve dans la grande distribution.
