### ISSUE TITLE
Amortissement voiture

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#424]
Actuellement la question posée est “qu’elle âge à votre voiture”. Il vaudrait mieux poser la question “En partant de la date d’achat, combien de temps penser vous conserver votre véhicule actuel?”. Actuellement, si on vient d’acheter un véhicule le calcul amortit sur l’âge renseigné + 1 an (d’où sort ce +1 : mystère, à part d’éviter une division par 0...). La perspective de garder son véhicule plusieurs années n’est pas du tout prise en compte.

**Comment by laem** [comment]
> d’où sort ce +1 : mystère, à part d’éviter une division par 0...

C'est exactement ça 😄 Et puis pour éviter de diviser par 0.1 aussi. 

Voir #225, nous avons en effet un gros problème sur ce point.
