### ISSUE TITLE
circuit de consommation

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#426]
Il me semble important d'intégrer les circuits de consommation : direct producteur, grande surface, plateforme d'achat ce qui a un effet considérable sur l'empreinte carbone.

**Comment by Benjamin-Boisserie-ABC** [comment]
La question des circuits courts ne se résument malheureusement pas à un simple calcul de distance. A ce sujet, consulter la F.A.Q

**Comment by laem** [comment]
Et l'issue alimentation v3 #185
