### ISSUE TITLE
Consommation logement et enfants

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#428]
la consommation d'énergie ou le montant des factures, c'est vraiment au pif dans mon cas ! Ne vaudrait il pas mieux évaluer la consommation en fonction des appareils électroménagers possédés etc ?
Et vous n'ajoutez pas une question sur le nombre d'enfants? C'est pire que l'avion et la viande, pour le climat...
A part ca merci votre test est bien fait et instructif.

**Comment by Benjamin-Boisserie-ABC** [comment]
Nous proposons l'approche par facture pour les personnes ne connaissant pas leur consommation d'énergie, car il est fréquent de connaitre seulement combien on paie. Détailler les appareils reviendrait à rajouter de nombreuses questions. Or nous souhaitons les limiter au strict minimum afin d'engager le plus grand nombre d'utilisateurs vers l'estimation de leur empreinte carbone.
Au sujet des enfants, voir #88
