### ISSUE TITLE
déchets

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#43]
Bonjour

dans les paramètres "déchets" vous indiquez 200, or il s'agit de 200kg de carbone, d'après la source Jancovici alors que dans le reste des paramètres vous êtes en éq.CO2 . => convertissez vous bien par le facteur 3,7 dans le résultat final pour passer en éq CO2 ?

**Comment by laem** [comment]
Très bonne question, à vérifier.

**Comment by fjg** [comment]
Corrigé 200*3,67=734
