### ISSUE TITLE
Remarque utilisation simulateur empreinte climat

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#430]
Bonjour,

J'ai deux remarques concernant l'utilisation du simulateur :
1/ dans le choix des plats de la rubrique alimentation. Je ne sais pas quel sélection faire pour les repas dans lesquels il y a du poisson .
2/ pour toutes les questions de la rubrique transport, ce n'est pas clair pour moi si je dois compléter en prenant en compte mes déplacements professionnels ou pas ?

Sinon je trouve l'ensemble très bien. 

Cordialement

**Comment by laem** [comment]
Pour le poisson, c'est noté dans #185 

Pour la question des déplacements pro, je pense qu'il va falloir expliquer ça sur l'écran "transport" ou comme une question rhétorique (étape du simulateur où l'on ne peut répondre que "D'accord").
