### ISSUE TITLE
Mon retour

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#432]
Bonjour et bravo pour le quizz avec le calcul
Effectivement il est en construction surtout pour les idées d'amélioration. 
Mais ils manquent beaucoup de question comme : avoir un compost aller au boulot à vélo
Les aliments qui periment
Avoir son potager 
Le nombre de kilo produit par son jardin 
Je sais que le soucis est que trop de question les gens s'arrêteront mais faites dans ce cas un mode simplifié et un mode développé. 
En tout cas bravo pour l'idée et je vais partager

**Comment by laem** [comment]
Voir #290
