### ISSUE TITLE
Et les scooters ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#436]
Franchement c’est vraiment top !
Juste vous ne posez pas la question pour les scooters : consommation différente d’une voiture non? Et l’électrique?
Si on achète tous nos vêtements en 2ème main, mais qu’il y a du transport (Vinted), ça change quelque chose ?
Merci à vous !

**Comment by laem** [comment]
Voir #184 
Pour l'occasion, oui bien sûr, le transport est à prendre en compte. Difficile pour nous de l'estimer cependant. On retrouve la question de la livraison.
