### ISSUE TITLE
Erreur d'affichage facteur 100 impact de la voiture

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#437]
Bonjour, 

Dans le détail des impacts de la voiture, on trouve une erreur concernant la quantité de CO2/100 km utilisée dans le calcul : 0,19 kgCO2/100 km.
C'est plutôt 19 kgCO2/100km ou bien 0,19 kgCO2/km

**Comment by laem** [comment]
Merci pour la remarque, c'était un problème d'unité n'affectant pas le calcul :)
