### ISSUE TITLE
remarque

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#441]
le questionnaire pose des question individuelles "avez vous une voiture personnelle" "avez vous un téléphone" par ex et seulement après, le nombre de personnes dans le foyer. Donc tout est biaisé, je réponds à certaines question pour moi mais concernant le chauffage ou les m2 c'est pour toute la famille. Donc ce bilan ne représente pas grand chose, sauf pour un(e) célibataire

**Comment by laem** [comment]
Voir #113
