### ISSUE TITLE
Manque de précision mais sympa

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#442]
Je comprends bien que vous fonctionnez avec des moyennes, mais le manque de précision apporte quelques failles :
- Le coût en électroménager neuf n'est pas insuffisant comme indicateur? L'occasion ou le réparé n'est pas prix en compte, l'investissement sert peut-être à consommer beaucoup moins, certains produits électroménagers sont plus locaux et faits de façon plus éthique
- Pareil pour le prix d'achat des habits : le côté local et durable n'est pas pris en compte, si on met une somme plus petite vous mettez un plus petit impact alors que les marques lowcosts ont les pires impacts (avec les grandes marques, bien plus chères mais qui n'ont pas un impact supérieur non plus)
- Pour l'alimentation, pareil : vous ne regardez pas la question de l'emballage, de la possession d'un potager, de la provenance (produit local, industriel, de saison ou sous serre chauffée, en vrac, etc). Vous considérez également que tout le monde consomme tout autant, peut-être que prendre le poids ou la quantité de calories consommées par jour pourrait être intéressant, certaines personnes mangent 4x plus que d'autres et l'alimentation à un impact conséquent d'après votre calcul.

Pas besoin d'être excessivement précis mais au vu de la différence de consommation selon notre réponse aux questions peu précises, il y a une faille dans le calcul.

Merci de votre compréhension, je trouve votre questionnaire déjà très agréable et très bien fait !

**Comment by laem** [comment]
Voir #44 

Pour l'alimentation,  #185

> Vous considérez également que tout le monde consomme tout autant, peut-être que prendre le poids ou la quantité de calories consommées par jour pourrait être intéressant, certaines personnes mangent 4x plus que d'autres et l'alimentation à un impact conséquent d'après votre calcul.

Je pense qu'on touche là aux limites du simulateur en termes de choix politique.
