### ISSUE TITLE
Précisions à apporter

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#458]
Dans la partie nourriture, vous ne parlez pas du poisson (on ne parle que de la viande). Cela n'a peut être qu'un impact faible, mais du coup la question posée sur les repas est difficile à répondre. (je mange un peu de poisson mais pas de viande). 
D'autre part, les aspects locaux, de saison, biologique ne sont pas demandés alors qu'ils ont (j'imagine un impact). 
De même pour le petit déjeuner, rien ne correspond vraiment. 

C'est néanmoins un bon outil, en espérant que vous soyez en mesure de l'améliorer prochainement !

**Comment by laem** [comment]
Merci pour le retour, voir #185 . Nous avons en effet plein de choses à améliorer sur ce sujet complexe :)
