### ISSUE TITLE
Alimentation local, bio ou NP voir même éthique plutôt que l'industriel !

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#459]
Bonjour, la production de viande (et autre) industrielle est très énergivore mais l'est beaucoup moins lorsqu'elle provient d'un petit élevage éthique local voir même personnel (je donnes très peu de graines à mes poules qui sont élevées à l'herbe). De plus, même si cela semble peu compter, je mange que des légumes de saison et local (avec presque aucun produit phytosanitaire). Toutes ces questions manquent (de mon point de vue). Désolé, je n'ai pas de sources pour étayer mes propos. En espérant faire avancer le schmilblick.

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat se veut être un calculateur grand public et facile d'utilisation. En ce sens, nous essayons de limiter le nombre de questions aux plus significatives (en terme d'impact carbone). Par exemple, la question de l'alimentation locale ne se réduit pas à un calcul de distance kilométirque (à ce sujet consulter la F.A.Q). De plus, la portée grand public de l'outil nous empêche de prendre en compte les spécificités de chacun. Néanmoins, nous travaillons à améliorer et à diversifier les questions posées sur le volet alimentation afin de prendre en compte les nombreuses remarques similaires #185
