### ISSUE TITLE
Erreur dans les calcul : bilan à 0t

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#46]
Testé et... mon bilan carbone est 0T !! Autant dire qu'il y a une erreur. Je voyais évoluer dynamiquement le graphique des différentes contributions au fur et à mesure de ma saisie. Il m'est arrivé de saisir plusieurs fois "0", mais il est théoriquement impossible d'atteindre la valeur 0T (les biens et services en France comptant à eux seuls pour 2T environ).

**Comment by laem** [comment]
En effet, c'est un bug. On doit avoir quelque part une valeur du calcul qui cloche, renvoyant un NaN, puis un zéro en remontant au montant final. Difficile de trouver l'erreur sans plus de détail 🤔

**Comment by laem** [comment]
Le problème venait du zéro déchet, réglé (peut-être ailleurs aussi, mais on rouvrira l'issue)
