### ISSUE TITLE
Félicitatino et suggestion sur el niveau de détail de "l'alimentaire"

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#460]
Excellente initiative pour permettre aux gens de se rendre compte de leur impact.

Je comprend que le niveau de détail soit limité pour faciliter l'utilisation de l'outil, mais j'aurai peut être rajouté un peu plus de personnalisation dans l'onglet alimentation (consommation locale, un niveau de détail supplémentaire dans la consommation de viande, consommation de produits transformés ou non).

Dans tous les cas, je soutiens cette initiative!

**Comment by Benjamin-Boisserie-ABC** [comment]
Cette amélioration est en cours d'élaboration (#185)
De plus, consultez les informations données à ce sujet dans la F.A.Q
