### ISSUE TITLE
Origine de la moyenne de 11tCO2.habitant.an

### ISSUE THREAD

**Issue by mmarionncern** [betagouv/ecolab-data#461]
Est ce que cette moyenne correspond à la moyenne des résultats des personnes visitant le test ou s'agit t'il d'un chiffre plus global provenant d'autre source?

Merci par avance pour la réponse

**Comment by fjg** [comment]
C'est un chiffre qui provient du CGDD cf. https://www.statistiques.developpement-durable.gouv.fr/lempreinte-carbone-des-francais-reste-stable
