### ISSUE TITLE
Calcul de l'empreinte voiture

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#462]
Remarque : lorsque l'on indique que l'on ne dispose pas de voiture individuelle mais que l'on effectue des kms en voiture, on nous demande quand même de renseigner le type de motorisation, le nombre de passagers par véhicule.
L'énonce n'est pas clair, doit-on également y répondre si l'on ne dispose pas de véhicule personnel ?

**Comment by laem** [comment]
Nous avons amélioré le texte des questions. Oui il faut y répondre, la voiture pollue surtout à l'usage, sauf si  électrique.
