### ISSUE TITLE
Plusieurs équipements numériques

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#463]
Bonjour,

Dans la partie Numérique, il n'est pas possible de renseigner le nombre d'appareils nous appartenant. Exemple : plusieurs téléphones, ordinateurs, TV, tablettes...

De plus, doit-on également compter nos équipements numériques professionnels ?

Merci

**Comment by Benjamin-Boisserie-ABC** [comment]
Cela rejoint les questionnements entre approche individuelle vs approche foyer #113 
Nos Gestes Climat s'intéresse seulement aux équipements numériques individuelles. Tous ce qui est professionnel relève du périmètre de l'empreinte carbone de l'employeur.

**Comment by laem** [comment]
En complément : voir #12, nous allons revoir l'interface de saisie du numérique.
