### ISSUE TITLE
Mobilités 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#467]
Pour la question des mobilités :
- quid d’un vélo ? Nous faisons tout en vélo et ne prenons la voiture que pour les vacances...
- pour le calcul de l’utilisation de la voiture : j’ai mis 9000 km mais en réalité, nous l’utilisons en famille surtout. Je n’ai pas trop compris comment faire apparaître cela.
Merci

**Comment by martinregner** [comment]
voir #170
