### ISSUE TITLE
Calcul Empreinte "placements financiers"

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#47]
Ex : mon voisin est propriétaire d'un logement de 300 K€, tandis que je suis locataire et que j'ai 300K€ d'argent en banque (fonds d'état en euros) : dans mon empreinte, vous calculez mon logement et mon placement; dans celle de mon voisin, vous ne calculez que son logement : manifestement pas normal !
En fait, l'argent n'émet jamais de CO2 ni assimilé : erreur de raisonnement ! Admissible pour une petite association (pourquoi pas un peu de provocation pour sensibilser aux placements dits "responsables"); mais pas de la part d'organisations sérieuses. Les outils et bases perdent du crédit sinon.

**Comment by laem** [comment]
Je ferme, sujet déjà documenté ici #24
