### ISSUE TITLE
Achat occasion et empreinte carbone

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#472]
Juste parce que je m’interroge : je n’achète quasiment que de l’occase mais je fais tout envoyer et livrer chez moi paumer au milieu de la campagne. Est ce réellement plus vert ? Merci

**Comment by Benjamin-Boisserie-ABC** [comment]
Acheter d'occasion à toujours moins d'impact qu'acheter neuf. Qui plus est un produit neuf, devrait dans tous les cas être aussi livré.
Si vous avez un autre moyen de récupérer vos produits (autre que la livraison par exemple lors de déplacements pro, de santé, etc.) cela peut en revanche avoir un impact significatif en terme de réduction d'émissions de Gaz à Effet de Serre

**Comment by laem** [comment]
J'ajoute que pour la livraison nous avons identifié le sujet dans  #141
