### ISSUE TITLE
ZONE RURALE

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#475]
A aucun moment vous ne prenez en compte si nous habitons en zone rurale ou urbaine. Or en zone rurale je ne peux ni prendre le train, ni le bus encore moins le metro. 
Dans le même esprit par contre j'achète des produits locaux et cela non plus n'est pas pris en compte dans vos calculs.

**Comment by Benjamin-Boisserie-ABC** [comment]
Au sujet des produits locaux, consulter la F.A.Q. Malheureusement la question du local ne se réduit pas à un simple calcul de distance.
Concernant le simulateur il cherche simplement à évaluer l'empreinte carbone de l'utilisateur. Un volet "passage à l'action" est en cours de développement afin de coller aux réalités de l'empreinte carbone de l'utilisateur ainsi qu'à son "profil" (rural vs urbain)
