### ISSUE TITLE
Type de logement et autres questions 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#477]
Pourquoi n'est-il pas demandé si j'habite dans un immeuble ou une maison individuelle ? Si j'ai une piscine ? Si j'ai un ou plusieurs véhicules  ? Combien de km de déplacements du quotidien j'effectue à vélo ? Etc. Si j'ai des animaux domestiques ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Certaines de ces questions sont en cours de traitement et/ou identifiées (vélo, animaux domestique).
Avoir plusieurs véhicules fait le lien avec l'approche foyer #113 
Nous demandons pas le type d'habitat car nous considérons un facteur d'émission unique. La différence n'est pas énorme de toute façon entre une maison individuelle et un logement collectif.
La piscine n'est pas prise en compte car au delà de l'impact de la construction (relativement peu impactant mais je me trompe peut être), l'impact majeur se situe sur la consommation de la ressource en eau. Nos Gestes Climat est à l'heure actuelle consacré uniquement au critère carbone (CO2eq)
