### ISSUE TITLE
Bois renouvelables ou non 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#478]
Bonjour
Nous nous chauffons avec un poele à bois, parfois le bois vient de forêt gérée durablement, parfois d'achat sur le bon coin (à un particulier qui s'est acheté un bois et une tronçonneuse, et qui faut probablement du deboisements). Il faudrait distinguer les deux cas ?
Merci

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat est un outil grand public qui a pour but d'engager le plus d'utilisateur à la simulation. Nous nous concentrons donc sur les modes de vies les plus courants et nous ne pouvons pas prendre en compte l'ensemble des spécificités de chacun.
Nous nous en excusons.
