### ISSUE TITLE
Conseil affichage résultat 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#481]
Bonjour,
Le résultat donné est arrondi, ce qui ne permet pas d’estimer l’évolution de mon bilan carbone selon mes actions. Ex: avec avion j’ai une empreinte de 5,2 et sans avion de 4,7 mais le résultat affiché est arrondi à 5 dans les deux cas..

**Comment by Benjamin-Boisserie-ABC** [comment]
Remarque prise en compte
