### ISSUE TITLE
Habillement 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#489]
Les questions sur l’habillement devraient se poser sur la nature des achats (chaussures, pantalons) et non sur le prix.

**Comment by LaurentGod** [comment]
Dans textile, si on achète français, on dépense 4 fois plus que si l'on achète pays asiatique, donc l'euro n'est pas forcément la bonne donnée pour estimer les téqCO2. 
Autre chose : il serait bon d'ajouter chaussures dans textile pour que l'on ne l'oublie pas dans notre évaluation.
Merci pour cet outil !

**Comment by Benjamin-Boisserie-ABC** [comment]
Cette question est traitée dans la F.A.Q et c'est un problème bien connu des ratios monétaires et des surestimations qu'ils peuvent entrainer
Nous pourrions demander le détail des habits achetés ainsi que la typologie (fast fashion vs éco-conçus) mais cela pourrait désengager l'utilisateur à la simulation (Nos Gestes Climat se veut un outil simple et engageant à la simulation). De plus, il est difficile de disposer d'autant de facteurs d'émissions que d'habits existants
