### ISSUE TITLE
[UX] affichage du bilan final

### ISSUE THREAD

**Issue by sdenier** [betagouv/ecolab-data#49]
Quand on finit la simulation, on a un affichage du bilan personnel total mais on perd la visualisation graphique détaillée précédente. Il faut revenir en arrière pour voir cette visualisation détaillée. Il peut être pertinent de l'intégrer à la visualisation finale, car elle est plutôt parlante.

**Comment by laem** [comment]
C'est en cours de dev :) 
Voir https://github.com/betagouv/ecolab-climat/pull/53
Je ferme, c'est bientôt en ligne, mais n'hésites pas si tu as des idées pour améliorer le 1er design avec graphique.

**Comment by sdenier** [comment]
:+1: c'est des retours rapides, les quelques trucs qui m'ont choqué au premier jet. Mais je suis allé jusqu'au bout dès la première utilisation, c'est bon signe ! 😃 C'est que les choses sont déjà plutôt claires et s'enchaînent facilement. Beau boulot !
