### ISSUE TITLE
Confusion age / durée d'utilisation

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#492]
Ma voiture a 1 an mais je vais la garder 10 ans comme la précédente.
Pourquoi diviser l'impact carbone de sa fabrication par 2 (1+1)? Ça n'a pas de sens, d'autant que même en en changeant avant elle est réutilisée..

**Comment by Benjamin-Boisserie-ABC** [comment]
L'amortissement de la voiture est maintenant non linéaire au lieu d'être affecté à l'année d'achat. Néanmoins cet amortissement est amené à évoluer
