### ISSUE TITLE
Conso d eau/utilisation de compost 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#494]
Bonjour, juste une petite remarque, il n y a aucune question concernant notre consommation d eau (nb de douche et de bain par semaine par personne).
De plus question du zéro dechets devrait être étoffée : proportion d achat en vrac, et utilisation d un compost?
Ensuite à titre exemple nous somme ds une démarche seront déchets mais depuis al naissance de notre fille c est couché jetable a gogo.. :/
En tout cas l interface est très agréable à utiliser.

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat est un simulateur portant, à l'heure actuelle, sur le seul critère carbone (CO2eq), l'impact sur la ressource en eau des douches et des bains n'est donc pas pris en compte (la consommation d'énergie pour chauffer l'eau chaude sanitaire l'ai en revanche).
Concernant les actions et le volet "passage à l'action", ce dernier est en cours d'amélioration notamment sur la partie gestion des déchets.
La problématique des couches rejoint les problématiques de calcul par foyer #113
