### ISSUE TITLE
Bien clarifier la période

### ISSUE THREAD

**Issue by laem** [betagouv/ecolab-data#5]
La simulation est annuelle. 
Certaines questions sont hebdomadaires.

S'assurer que l'utilisateur comprend bien la période, pour éviter d'avoir des facteurs * 52 😅 .

- sur les estimations de facture : mensuelle ou annuelle ?

**Comment by martinregner** [comment]
Mensuelle ET annuelle ?
Idée UI : 
- le champs de saisie
- collé à droite du champs : un bouton "€/mois" déjà sélectionné (comme les boutons oui/non)
- à droite du premier bouton : un bouton "€/an" qui déselectionne l'autre

**Comment by laem** [comment]
Même sujet que #24

**Comment by fjg** [comment]
Sujet clos. A voir si bug par la suite.
