### ISSUE TITLE
Lien Github bloqué par la CSP

### ISSUE THREAD

**Issue by sdenier** [betagouv/ecolab-data#50]
Petit détail, mais le lien vers le dépôt github sur la page Contribuer est bloqué de part le fait que l'app est hébergée dans une iframe et ne permet pas d'ouvrir une URL externe. URL à ouvrir dans une nouvelle fenêtre.

**Comment by laem** [comment]
Bien vu, merci ! 
c96c5c557d2ac36d1020b72ccd96681f161005f6
