### ISSUE TITLE
Question répartition de l’alimentation

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#500]
Bonjour ! Au moment de choisir la répartition des repas de la semaine, je constate qu’il manque quelques possibilités, notamment les repas à base de poisson. Ils sont peut être similaires à d’autre choix de votre questionnaire, ou pas ? Je pense que cela serait un ajout bienvenu. Cordialement :)

**Comment by laem** [comment]
Merci, voir #185 .
