### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#501]
Ajouter l'utilisation d'un vélo et d'une moto. 
Ajouter l'utilisation d'un composte.

**Comment by Benjamin-Boisserie-ABC** [comment]
Pour le vélo c'est en cours de traitement #813 
Pour la moto c'est en cours d'élaboration
L'utilisation d'un compost va être prise en compte dans le volet 'passage à l'action' de l'outil
