### ISSUE TITLE
Trop restreint 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#504]
Bonjour, je connais l'ademe depuis plus 15 ans. Je lis vos livres, vos rapports. Je reste circonspect par votre test. Il est extrêmement restreint, et sert juste à faire culpabiliser les gens par les choix limités. L'âge n'est pas forcement bon, tous les produits récents consomme en général moins d'eau, électricité ou gaz. Ne pas tenir compte qu'un vêtement éco-réponsable a forcément un coût aussi. Bref dommage. En simplifiant à l'extrême votre test vous décrédibilisez le message que vous essayez de faire passer et donnez raison aux gens qui ne veulent pas évoluer ou ont peur du changement. Le changement a un coût élevé à court termes sans doute plus que celui du non changement. Mais à long terme il est beaucoup plus faible. Votre notion d'échelle n'est pas la bonne.

**Comment by laem** [comment]
Bonjour, nous faisons notre possible pour que ce test soit plus précis tout en restant simple, avec les moyens dont on dispose. N'hésitez pas à nous aider : tout est en ligne ici, tout est améliorable.
