### ISSUE TITLE
Vie de ce bilan carbone personnel / familial

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#505]
Je trouverais intéressant que ce bilan carbone personnel / familial puisse être sauvegardé au moyen de la création d'un compte, ce qui permettrait de l'affiner et de le faire évoluer (en fonction des évolutions de nos consommations ou autre), sans avoir perdu les données précédentes et avoir ainsi tout à reprendre.

**Comment by Benjamin-Boisserie-ABC** [comment]
Cet aspect est actuellement en cours de réflexions. 
Nous prenons en compte votre remarque
