### ISSUE TITLE
voiture

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#506]
Bonjour,
Votre calcul impacte 6 tonnes de CO2 pour ma voiture, qui date certes de cette année, mais que j'ai l'intention de garder au moins 5 ans avant de la revendre (moyenne 7-8 ans en France). Pourquoi ne pas tenir compte de ce chiffre ?Mon impact carbone  de 11 tonnes par an tient pour moitié à l'achat de ce véhicule : je suis à 5 tonnes hors voiture, et 200kg/an d'usage du véhicule électrique, votre calcule gonfle artificiellement ma stat...y a-t-il une adaptation selon l'âge du véhicule ?

**Comment by laem** [comment]
Traité dans la dernière version.
