### ISSUE TITLE
Il est compliqué d'estimer en euros sa consommation de biens manufacturés, ce serait mieux par mois je pense. Par ailleurs en quoi le prix reflète-t-il l'empreinte carbone ? Il est souvent dû à la marque achetée, au style etc... non ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#507]

**Comment by Benjamin-Boisserie-ABC** [comment]
Question répondue dans la F.A.Q
Quant à la temporalité, le calcul de l'empreinte carbone se fait sur année ce qui permet de "lisser" les impacts des achats. Raisonner en mois peut induire de très fortes variations
