### ISSUE TITLE
Climat et CO2

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#51]
Vous liez systématiquement climat et CO2
Sur le long terme, il n'y a aucune corrélation entre température et CO2
Depuis 15 ans le CO2 continue de monter et pas la température.
Historiquement, les périodes chaudes ont toujours été fastes pour l'humanité.
Le CO2 est l'aliment des plantes et tant mieux s'il augmente car la population de la planète augmente de 200.000 personnes par jour:         + 40.000.000 depuis le début de l'année.
Certaines dépenses pour la production d'énergies dites "vertes" qui consomment des aliments (blé, soja, maïs, betteraves, canne à sucre...) pour produire de l'électricité ou des carburants ne seraient elles pas mieux utilisées pour soigner et nourrir ceux qui en ont besoin.

**Comment by laem** [comment]
>  Sur le long terme, il n'y a aucune corrélation entre température et CO2

On attend la définition de "long-terme" et les références qui soutiennent cette affirmation. En attendant, je ferme le ticket.
