### ISSUE TITLE
Estimation de la consommation de granulés bois en... kWh ??

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#512]
Pour le mode de chauffage granulés bois, donner l'estimation de sa consommation en kWh est compliqué. Les factures sont à la tonne (pour un système à silo. Par ailleurs, le granulé en sacs a une empreinte toute autre à ma connaissance).

**Comment by bertrandgorge** [comment]
Selon : https://www.picbleu.fr/page/equivalence-energetique-des-combustibles-et-energies-de-chauffage

1 tonne de granulés de bois = 5106 à 4600 kWh

**Comment by bertrandgorge** [comment]
PR ici : https://github.com/betagouv/ecolab-data/pull/796 (pas de modification du calcul, juste une indication pour aider le calcul)

**Comment by Benjamin-Boisserie-ABC** [comment]
Voir #867
