### ISSUE TITLE
Remarque textile

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#514]
Dans textile, si on achète français, on dépense 4 fois plus que si l'on achète pays asiatique, donc l'euro n'est pas forcément la bonne donnée pour estimer les téqCO2. 
Autre chose : il serait bon d'ajouter chaussures dans textile pour que l'on ne l'oublie pas dans notre évaluation.
Merci pour cet outil !

**Comment by Benjamin-Boisserie-ABC** [comment]
Question traitée dans la F.A.Q

Remarque prise en compte pour les chaussures
