### ISSUE TITLE
Partie alimentation imparfaite

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#517]
La partie "alimentation" ne correspond pas à mes choix alimentaires. Je mange 2/jours : petit dej= pâtes complètes ou riz
Repas= pâtes ou riz + légumes+fromage et viande ou poisson 2/semaines.

**Comment by laem** [comment]
> petit dej= pâtes complètes ou riz

Dans ce cas l'option "lait céréales" avec lait végétal correspond plutôt bien à votre habitude.

>  Repas= pâtes ou riz + légumes+fromage et viande ou poisson 2/semaines.

Il nous manque donc le poisson, sinon les repas végétarien / viande 1 / viande 2 sont une bonne approximation de votre régime.
