### ISSUE TITLE
Pas de prise en compte des trajets en vélo

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#520]
Bonjour,
Je suis un vélotafeur, comme ils disent, et je fais environs 80km par semaine à vélo.
Ma voiture ne me sert que les week-ends pour les courses et balades et les vacances.
Or, votre simulateur ne prend pas en compte ce paramètre.
Bien cordialement

**Comment by martinregner** [comment]
Les modes de transport qui n'émettent pas de gaz à effet de serre ne sont pas comptés. Pour en savoir plus et comparer les modes de transport, nous vous suggérons de regarder le simulateur transport : https://ecolab.ademe.fr/transport

**Comment by martinregner** [comment]
voir #415
