### ISSUE TITLE
Habillement

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#525]
Bonjour, je pense que ce n’est pas tout à fait juste de demander le coût des achat d’habits neuf par an pour déterminer l’impact environnemental. Une piece chère n’est à mon sens pas plus ou pas moins polluante qu’une pièce à un meilleur prix. Pourquoi ne pas demander plutôt le nombre de pièces?

**Comment by Benjamin-Boisserie-ABC** [comment]
Question traitée dans la F.A.Q
Concernant le nombre de pièces, Nos Gestes Climat se veut être un outil simple et engageant à la simulation. Pour se faire nous avons choisi de limiter le nombre de questions et de raisonner en approche monétaire que nous savons imparfaite. Renseigner l'ensemble des biens achetés peut conduire des utilisateurs à ne pas aller au bout de la simulation. De plus,  il n'existe pas de facteur d'émissions pour l'ensemble des différents types d'habits que l'on peut acheter dans le commerce.
