### ISSUE TITLE
Remarques diverses

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#526]
Dans vos calculs il y a des points qui représentent des gros biais:
- le foyer et sa composition est trop en tout ou rien alors que c'est un diviseur dans votre bilan qui a donc une grosse influence sur les résultats. Il faudrait prendre en compte l'age pour la consommation selon la croissance et nombre de personnes en permettant les virgules pour les gardes alternées.
- l'age de l'équipement à un instant T fausse, il faudrait demander la durée de vie escompté du matériel. 
- le calcul sur les repas fausse également : plutôt que de parler nombre de repas avec viande, il faudrait demander quantité de viande achetée par semaine. Un repas avec 800g de viande de porc est 8 fois plus impactant qu'un repas avec 100g de lardons, cela fausse énormément le résultat. 
- La part de ges dû aux infrastructures publiques est incluse mais on a aucune prise dessus. Pourtant elle pèse presque autant que l'objectif. Psychologiquement, c'est pas très constructif pour celui qui se teste...
Votre test me place à 5 tonnes. Pourtant j'ai calculé être en dessous du point de neutralité de ges. Donc si vous faites un test, faites le bien pour qu'il soit reconnu. Si c'est un gadget faux, il sera inutile et fera du mal à l'écologie en donnant des arguments aux climato sceptiques...

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant l'approche foyer vs indiv voir la F.A.Q et #113 
Concernant la durée de vie (ou de renouvellement) cet aspect sera approché dans le volet "passage à l'action" afin de proposer des actions de type "j'allonge la durée de vie de mes biens et équipements"
Concernant le repas, l'approche par repas est la plus facile d'utilisation et la plus simple pour engager le plus nombre d'utilisateurs à effectuer la simulation. Devoir rentrer les grammages c'est en effet être plus précis mais perdre de nombreux utilisateurs, découragés par le nombre et le détail des questions.
Concernant les infrastructures publiques, il est essentiel de les prendre en compte afin de comprendre que la transition écologique n'est pas une simple question de changement individuel mais bien une question de changement global. Nous concevons en revanche que le message pédagogique est à mieux amener.
Si vous êtes à 5 tonnes vous avez déjà fait l'essentiel du chemin de transition. Félicitations à vous
