### ISSUE TITLE
Impact animaux domestiques

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#527]
Bonjour,
Je suis curieux de ne pas voir l'impact des animaux domestiques carnivores, en effet la consommation de viande a un impact fort sur le CO2, or un chien / chat se nourrit en grande partie de viande. Il pourrait être intéressant (et pas forcément complexe en fonction du poids de l'animal) de le prendre en compte.
Merci beaucoup pour le travail réalisé !! C'est très sympa à utiliser et très important !
Thibault

**Comment by laem** [comment]
Merci pour le retour ! Voir #35
