### ISSUE TITLE
Segmentation questionnaire par thématique

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#529]
Bonjour, 

Je trouve votre questionnaire très complet, instructif et utile. Je pense que cela pourrait intéresser nombreux employeurs pour sonder leurs collaborateurs. Il serait bien de pouvoir raccourcir la longueur du questionnaire en permettant de répondre aux questions uniquement par thématique (transports, logement, etc). 

Belle journée à vous. Cordialement, 

Héloïse Poëy-Noguez, fondatrice du cabinet de conseil en écomobilité et app web de cotrajets entre citoyens SoliMobi - wwww.solimobi.com

**Comment by Benjamin-Boisserie-ABC** [comment]
Prise en compte de la remarque
