### ISSUE TITLE
remarques sur ecolab

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#53]
Dans la question sur la viande on passe de viande 1 fois/jour à boeuf 1xpar semaine puis végétarien
je pense qu'un item viande 1xpar semaine serait utile (pas que boeuf)

dans logement pour les granulés de bois il faut mettre l'unité en tonnes et non pas en kwh

Dans mes résultats mon total global est à 0 alors que j'ai plusieurs postes qui ne sont pas à 0! Il doit y avoir un bug de calcul

**Comment by laem** [comment]
Le problème du 0t venait du zéro déchet, réglé (peut-être ailleurs aussi, mais on rouvrira l'issue)

**Comment by fjg** [comment]
@laem pourquoi ne l'as-tu pas fermé ? C'est bon non ?

**Comment by laem** [comment]
Je crois que oui 🙂
