### ISSUE TITLE
Impact de la consommation locale pour l'alimentation

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#531]
L'impact du transport sur l'alimentation n'est pas négligable pour les végéta*iens. Je mettrais une grille à remplir avec le 
% d'auto consommation (jardin) 
% achat local (<80km) ou direct producteur 
% achat supermarché

**Comment by Benjamin-Boisserie-ABC** [comment]
La question de l'approvisionnement locale ne se résume malheureusement pas à une simple question de km parcourus. Cf. F.A.Q
