### ISSUE TITLE
indicateurs non pris en comptes

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#533]
Bonjour, 
Je me permets de vous faire ces remarques suite à l'utilisation de votre outil de calcul. 
Je ne vois aucunes questions sur les achats d'occasion, sur notre gestion des déchets (tri,compost...), sur nos achats locaux/bio/saisons/équitables et également sur nos consommations d'énergie ( panneaux solaires, régulateur d'eau, potager, récupérateur eau...) .

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant les achats bio/locaux voir la F.A.Q
Concernant la saisonnalité, la gestion des déchets, et autres actions, un volet "passage à l'action" est en cours de développement pour engager l’utilisateur à mettre en place des actions concrètes et dont l'impact aura été quantifié.
Concernant l'achat d'occasion, le simulateur pose maintenant la question sur les produits achetés neufs.
Concernant, l'électricité "verte" cette question est traitée dans la F.A.Q. S'il s'agit d'être producteur avec ces propres panneaux (et donc autosuffisant), c'est un cas particulier que nous ne prenons pas en compte. Il est possible dans le simulateur de ne pas renseigner de consommation électrique afin de traduire l'autosuffisance mais l'impact de la construction et de l'installation des panneaux ne sera pas pris en compte ce qui sous-estimera légèrement l'empreinte carbone finale.
