### ISSUE TITLE
prise en compte du nombre d'appareils à la maison

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#534]
il est demandé si on a un ordinateur mais pas plusieurs. cela compte forcément dans le calcul de l'empreinte (ordi bureau, ordi perso) ou une console....

**Comment by Benjamin-Boisserie-ABC** [comment]
Cela fait lien avec l'approche foyer ou l'on devra pouvoir renseigner plusieurs appareils. Voir #113
