### ISSUE TITLE
Faites une présentation avec le detail des sous-rubriques en camenbert

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#536]
Bonjour, 
j'ai fais le test mais la presentation de mes chiffres ne permet pas de savoir quelle est la fraction d'émission due )à la voiture et due à l'avion. Je ne sais pas conclure quelle est le levier le plus interessant.  Est ce diminuer mes km en voiture ou diminuer mes km en avion ... ? Ce serait bien de faire pour chaque rubrique (transport, logement, alimentation, ...), une presentation graphique qui détaille la proportion de chaque sous-rubrique (auto, avion, bus, ...). 
Je vous suggère de favoriser davantage les presentations graphiques (camenbert) aux présentations de "bêtes" chiffres isolés.

**Comment by Benjamin-Boisserie-ABC** [comment]
Une fois la simulation terminée, l'outil permet maintenant lorsque l'on click sur une barre de voir la décomposition chiffrée des impacts pour chaque poste.
Nous prenons en compte le besoin d'avoir un retour plus graphique/visuel sur le détail des postes
