### ISSUE TITLE
Impact des produits achetés neufs

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#539]
Je pense qu'il serait plus cohérent de calculer l'empreinte carbone des produits neufs par rapport au nombre d'articles achetés/la provenance/le mode de fabrication, plutôt que par rapport au prix de ceux-ci.
En effet, un seul pull fabriqué en France avec des matières recyclées/upcyclées va coûter bien plus cher que plusieurs pulls bon marché, bien que son impact écologique soit moindre.

**Comment by Benjamin-Boisserie-ABC** [comment]
Question traitée dans la F.A.Q
