### ISSUE TITLE
Gabarit de la voiture électrique

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#540]
Perso, je roule en voiture électrique. Mais une petite voiture avec batterie de 24kWh (Nissan Leaf ou Renault Zoé) n'a pas du tout la même empreinte qu'un modèle haut de gamme (Tesla, ...). Il serait bien de rajouter une question sur la taille de la batterie (lien : https://www.automobile-propre.com/voiture-electrique-impact-carbone-batteries/)

Je prends également une fois tous les 2 ans l'avion mais je finance une organisation qui plante des arbres à Madagascar en retour (https://grainedevie.org/fr/). Ce serait bien de pouvoir en tenir compte et même de proposer à des citoyens ce type de démarche.

Sinon, je trouve l'appli très ludique et très claire.

**Comment by laem** [comment]
Malheureusement, il semble que la base carbone ne contienne pas de données sur l'empreinte de fabrication d'une voiture.
https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=voiture

**Comment by laem** [comment]
On avait déjà fait une recherche de données sur le sujet ici https://github.com/betagouv/ecolab-transport/issues/13

**Comment by laem** [comment]
Voilà ce qui me semble le plus simple. 

Si thermique, "connaissez-vous votre consommation de carburant moyenne" ? Suggestions. 
Pour thermique comme élec, quesiton du gabarit, utiliser les mêmes suggestions. 
gabarit -> poids -> empreinte construction élec / hybride / thermique par extrapolation de l'étude [FNH-C4](www.fondation-nicolas-hulot.org/sites/default/files/vehicule_electrique_rapport.zip).
Gabarit -> conso kWh électrique -> empreinte du mix FR au km, ou utilisation des valeurs de bGES.

**Comment by Benjamin-Boisserie-ABC** [comment]
La question des gabarits du véhicule est une question que j'ai abordé dans une fiche élaborée (non publié sur NGC car en relecture du côté de l'ADEME). J'ai en effet utilisé l'étude de la FNH pour donner des ordres de grandeur mais je ne sais pas à quel point on peut "arrêter ces données" même s'il y a un communiqué de presse de l'ADEME à ce sujet et tout. Je te propose d'attendre le retour de l'ADEME sur ce que j'ai écrit (c'est Fanny Fleuriot qui relie). Ce retour devrait arriver incessamment sous peu et ça permettra de savoir ce qu'en pense Fanny. 

Concernant les questions j'ai du mal à suivre ton raisonnement. Je ferais : 
Quel type de voiture utilisez-vous ?
           Thermique          Hybride               Electrique
Quel est le gabarit de votre voiture ?
           Citadine              Berline/SUV
Si réponse thermique (qq soit le gabarit) : Quelle est la consommation moyenne de la voiture ?
Si réponse électrique --> on adapte l'empreinte au km en fonction du gabarit avec les FE de la base carbone (entrée de gamme et cœur de gamme)
Si réponse hybride --> je me demande s'il ne faudrait pas avoir la même approche que les véhicules élec (empreinte au km) en utilisant la encore les FE de la base carbone fonction du gabarit (entrée de gamme, haut de gamme)

Se pose la question de quels FE on choisi parmi la multitude qui existe dans la base carbone
Cette source peut, peut être, être plus intéressante pour "arrêter" les émissions au km d'un gabarit type  : https://www.ademe.fr/consommations-carburant-emissions-co2-vehicules-particuliers-neufs-vendus-france

Rien à voir : l'impact de la construction du véhicule qu'on utilisait jusque là vient d’où ? Le 12 000 est repris de Mic Mac il me semble mais qu'en est-il du 7000 (impact de la construction d'un véhicule thermique) ?

**Comment by laem** [comment]
Oui c'est ça dans l'esprit, mais cette issue était surtout pour améliorer le calcul de l'empreinte construction, car on fait déjà varier les FE thermique en fonction de la conso, et l'empreinte en France d'usage d'un VE est très faible.

>Rien à voir : l'impact de la construction du véhicule qu'on utilisait jusque là vient d’où ? Le 12 000 est repris de Mic Mac il me semble mais qu'en est-il du 7000 (impact de la construction d'un véhicule thermique) ?

Oui, on a repris MicMac, je ne sais pas d'où vient ce 7000... d'où l'intérêt d'utiliser des données plus précises et nuancées.
