### ISSUE TITLE
Sérieux de vos calculs

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#542]
Je viens de faire le test. Mon empreinte est censée être de 12 tonnes d'équivalent carbone. Le problème c'est que nous vivons plutôt simplement. J'en arrive à la conclusion que, pour arriver à 2 tonnes  il faudrait que je renonce à me déplacer (nous utilisons peu la voiture, mais elle est indispensable pour certains trajets de proximité pour lesquels le train ou le bus ne sont pas envisageables), que je dorme sous les ponts, que je ne mange que du pain sec et de l'eau.
Bref, j'ai du mal à prendre au sérieux vos calculs.

**Comment by 945fc41467** [comment]
Je ne connais le détail des calcul, et vu la précision des question, je devine que le résultat est aussi très approximatif (pas de prise en compte de l'isolation de la maison, de la cylindrée de la voiture, peu de détail sur l'alimentation, etc).
Cela dit il est de notoriété publique que les objectifs de l'accord de Paris sont très, très serrés. De mémoire l'achat d'un ordinateur portable correspond à votre quota annuel (le quota total, donc après, vous coupez les compteurs de gaz et d'élec et vous ne mangez plus pendant un an).

Donc il me parait effectivement vraisemblable que ces objectifs ne seront pas atteints. Cela ne veut pas dire qu'il n'y a rien à faire pour s'en rapprocher (on a des grosse marge de manœuvre avec la consommation de viande et de poisson, l'isolation et le chauffage des logement, et les moyens de transports). Mais pour le moment on en prends pas clairement pas le chemin.

Pour info, avec deux repas carnés par semaine, 80m2 pour quatre personnes chauffés au gaz, 2400km/an de train, un smartphone et un ordi, 5000km/an de voiture thermique, ça donne 5T de CO2. Donc, il s'agit pas non plus de se mettre à faire de la poterie dans une communauté hippie (sans vouloir vexer les hippies que je trouve dans l'ensemble très sympathiques).

**Comment by laem** [comment]
> Mon empreinte est censée être de 12 tonnes d'équivalent carbone. Le problème c'est que nous vivons plutôt simplement. 

Il se peut que notre calcul soit erroné ou approximatif à certains endroit, mais l'ordre de grandeur doit être le bon. Il est donc probable que vous ne viviez pas "simplement", mais plutôt comme la moyenne des français, au moins en terme d'empreinte climat.

>  que je dorme sous les ponts, que je ne mange que du pain sec et de l'eau.

Comme dit par @945fc41467, le simulateur vous a permis de vous rendre compte à quel point le problème du climat est un problème sérieux, qu'on ne balaie pas en 3 mesurettes à l'assemblée et 3 gestes climat de type tri des poubelles. 

>  Bref, j'ai du mal à prendre au sérieux vos calculs.

La fiabilité de nos calculs, qui est évidemment questionnable et a une grosse marge de manoeuvre (c'est le but de ce formulaire :), merci pour votre contribution ), n'a aucun rapport avec le fait que nous savons pertinemment que l'humanité émet assez de gaz à effet de serre pour détraquer notre climat. C'est un fait. 

> Je ne connais le détail des calcul

Tout est disponible sur ce dépot de code. 

> pas de prise en compte de l'isolation de la maison

Il faut reseigner les kWh, donc l'isolation de la maison est bien relfetée dans cette consommation d'énergie.

> de la cylindrée de la voiture

Il y a bien une question à ce propos, en l/100km.

> De mémoire l'achat d'un ordinateur portable correspond à votre quota annuel 

Non, plutôt 500kg de CO2e amortis sur > 4 ans, les quotas étant souvent définis à 1 ou 2 tonnes. 


> Donc, il s'agit pas non plus de se mettre à faire de la poterie dans une communauté hippie 

Je la retiens cette phrase :D
