### ISSUE TITLE
Alimentaire : poisson vs Viande

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#543]
Dans la partie Alimentaire, il y a deux cases différentes pour les viandes, mais rien pour les poissons. Est-ce volontaire? Comment évaluez-vous l'impact relatif à la consommation de poissons et produits de la mer?

**Comment by DaffyDuke** [comment]
Tout à fait d'accord, chez nous, le poisson est plus présent que la viande, on ne peut pas "jouer"....

**Comment by laem** [comment]
Merci pour la proposition, voir #185
