### ISSUE TITLE
Calcul pour le textile

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#55]
D'où vient le 0,3 du calcul du textile?

**Comment by laem** [comment]
Bonne question, je vais renseigner la source, qui doit être dans l'excel MicMac

**Comment by AlixPoitou** [comment]
En effet je suis allée voir dans le MicMac (je ne connaissais pas son existence avant ça désolée).
J'ai vu qu'ils avaient fait une moyenne sur deux produits. Je trouve cela léger car en moyenne une femme dépense 433€ par an dans le prêt à porté, cela donne donc 130 kgCO2 / an. Cela me paraît peu.

**Comment by laem** [comment]
Lié à #44

**Comment by fjg** [comment]
Lié à #6 (ca sera plus juste avec les quantités d'habit comme proposé dans #44)

**Comment by fjg** [comment]
Doublon #44
