### ISSUE TITLE
Détails par questions

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#552]
Les questions posées à l'intérieur d'une catégorie sont très intéressantes. Il serait utile d'avoir l'impact d'une réponse précise sur le % total et sur le % de la catégorie correspondante (exemple: si j'ai inscrit avoir fait 1 AR long courrier en avion, combien m'a-t-il coûté en % dans la catégorie transport et en % par rapport au total?)

**Comment by Benjamin-Boisserie-ABC** [comment]
Le découpage chiffré par poste d'émissions peu être obtenu à la fin de la simulation en cliquant sur les histogrammes. 
Prise en compte de la remarque pour ajouter un pourcentage (à côté de l'évaluation chiffrée)
