### ISSUE TITLE
impossible de répondre: "pas de téléphone mobile"

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#553]
Il y a plusieurs réponses possibles dans la rubrique "téléphone" du test, mais aucune option "pas de mobile" (du tout, ni basique ni smart). La seule réponse possible pour continuer le test est: "je ne sais pas" (si j'ai un téléphone...). Mouais...

**Comment by Benjamin-Boisserie-ABC** [comment]
question sur la téléphonie modifiée. Voir #871 
Nous ne donnons pas la possibilité de ne pas avoir de téléphone car ne pas avoir de "mobile" se traduit très probablement par avoir un téléphone "fixe".
Nous aviserons sur la nécessité de mettre une option pas de téléphone (du tout c.a.d ni fixe ni mobile) en fonction des retours suite à cette modification
