### ISSUE TITLE
Manque repas avec poisson comme source animale

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#561]
On a le choix entre viande 1 (poulet, porc) et viande 2 (boeuf, agneau, veau)
Impact carbone du poisson?
https://ourworldindata.org/food-choice-vs-eating-local
Proche de viande 1 pour celu qui est élevé (5kg/kg) mais un peu plus du double des tomates pour celui qui est pêché (3kg / kg)
A mon avis cela peut faire une différence pour les personnes qui ne mangent jamais de viande mais que du poisson et seulement certains jours par semaine

**Comment by laem** [comment]
Merci pour la proposition, voir #185
