### ISSUE TITLE
Chauffage et voiture

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#567]
En tant que locataire d'un logement avec chauffage collectif, je n'ai aucune idée de ma consommation mensuelle en chauffage (les charges couvrant plus que le chauffage seul). Le questionnaire ne faisant pas la distinction entre immeubles et maisons individuelles, il est difficile de savoir si la valeur par défaut est bien réaliste pour mon cas.

Autre point, nous possédons une voiture dans un foyer de 2 personnes, mais l'amortissement de la construction de la voiture ne semble pas divisé par le nombre de personnes.

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, difficile de savoir combien vous consommez lorsque que le système de chauffage est collectif. Néanmoins avec l'approche par la facture peut s'avérer plus pertinente (en divisant la facture collective par le nombre d'habitants ou par les m2 chauffés). Cela reste néanmoins approximatif.
Concernant la voiture cela rejoint, les questionnements sur l'approche par foyer #118
