### ISSUE TITLE
impact de l'épargne 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#568]
Est-ce que l'impact de l'épargne apparaît dand une section ? Je n'ai pas l'impression alors que cela me paraît un poste important (pour celles et ceux qui ont la chance d'avoir de l'argent de côté!).
Et comme il y a de grandes différences entre l'usage qui est fait de cette épargne il faudrait demander le type de produit et la banque utilisés.
Voir entre autre les publications des amis de la Terre :
http://www.financeresponsable.org/entreprise.php

**Comment by fjg** [comment]
voir #24
