### ISSUE TITLE
Scenario 2t

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#569]
Bravo pour cette application ! 
Pour aller plus loin, il serait intéressant soit de proposer des actions pour atteindre / tendre vers un scénario 2t soit- mieux- de permettre d'évaluer l'impact d'action (ex : évaluer l'impact d'un repas carné en moins, l'impact d'un trajet train vs avion vs voiture,). Les propositions pourraient être faite en fonction du/des 1-2-3 postes prioritaires.

**Comment by Benjamin-Boisserie-ABC** [comment]
Ce volet "passage à l'action" est en cours de développement
