### ISSUE TITLE
dépenses vêtements

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#570]
la question des dépenses en terme de vêtements ne me semble pas pertinente. Je dépense beaucoup chaque année en vêtements, environ 1000€ mais uniquement des pièces très qualitatives, fabriquées en Europe, respectant des normes écologiques. Cela revient donc à 5-6 vêtements achetés chaque année tandis qu'un consommateur de grande distribution achèterait pour la même somme une cinquantaine de vêtements produits à l'autre bout du monde avec des matériaux et dans des conditions très polluantes. Chacun fait ses propres choix mais la somme dépensée ne me semble pas être un critère pertinent. Sans cela votre test est intéressant, merci de cette démarche.

**Comment by Benjamin-Boisserie-ABC** [comment]
Question traitée dans la F.A.Q
