### ISSUE TITLE
Manque de précision de l'outil pour affiner les calculs

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#571]
Distinguer les voitures utilisées par le foyer (ex : 1 électrique 15000 km/an et 1 thermique 7000 km/an), affiner la démarche 0 déchets (nombre de sac poubelle noir/an ou poids déchets ménagers par an), ajouter le déplacement par vélo mécanique ou électrique et le kilométrage par an.

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant les voitures, cela est en lien avec l'approche foyer. Voir #118 
Concernant le vélo, une question va être ajoutée même si les déplacements en vélo mécanique et dans une moindre mesure en électrique sont marginaux.
Concernant la démarche zéro déchets. Nos Gestes Climat fait le choix de la simplicité afin d'engager le plus nombre d'utilisateurs à réaliser leur simulation. Améliorer la précision des questions est possible mais au détriment de la simplicité d'utilisation tout en gardant les mêmes ordres de grandeur dans l'évaluation de l'empreinte. 
Néanmoins, le volet "passage à l'action" aborde un plus en détails la question de la gestion des déchets.
