### ISSUE TITLE
Et la descendance?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#573]
Le fait de faire des enfants qui vont eux même générer de l’effet de serre n’est pas du tout abordé. C’est dommage. Il faudrait à mon sens appliquer un coefficient multiplicateur ou mentionner qu’à ces émissions il faut ajouter celles de nos enfants et petits enfants, à raison de 11 tonnes en moyenne s’ils n’ont pas eux même fait leur calcul...

**Comment by laem** [comment]
Voir #88
