### ISSUE TITLE
Prise en compte des jardins et balcons

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#574]
Votre simulation ne prend pas en compte que l'on ai un jardin/balcon ou pas avec possibilité de compostage, de plantation d'arbres, de potager, etc.
Pouvez-vous le prendre en compte.
Cordialement.

**Comment by Benjamin-Boisserie-ABC** [comment]
Certaines de ces questions sont traitées (de manière générale) dans le volet "passage à l'action". Leur prises en compte de manière individuelle serait 1. très approximative d'un point de vue de la comptabilité carbone et 2. pas forcément significative.
