### ISSUE TITLE
Influence du mode de chauffage

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#579]
Est-il possible d'affiner le calcul en renseignant la température de consigne de chauffage? Le bilan (particulièrement dans le cas d'un chauffage au gaz) devrait être différent si on règle à 21°C toute la journée ou à 19°C lorsqu'on est présent et 16°C la nuit et quand on est absent.

**Comment by Benjamin-Boisserie-ABC** [comment]
Cette différence de chauffage se traduit _in fine_ par une consommation en kWh élevée (ou une facture). Cela se verra donc dans l'empreinte carbone finale.
