### ISSUE TITLE
L'âge de mon téléphone

### ISSUE THREAD

**Issue by DavidBruant** [betagouv/ecolab-data#583]
La question sur l'âge du téléphone est posée de la manière suivante : 

> Quel âge a-t-il ?

J'ai le mien depuis 8 mois, mais j'ai gardé le précédent pendant 4 ans, donc je ne sais pas ce que je devrais répondre

Aussi, est-ce que ce qui vous intéresse, c'est le temps que je l'ai eu entre les mains ou le délai depuis lequel il est sorti d'usine ? Je sais répondre à la première question, mais pas à la deuxième (téléphone reconditionné)

**Comment by laem** [comment]
Voir #168
