### ISSUE TITLE
Je ne connais pas les pouces de mon téléphone

### ISSUE THREAD

**Issue by DavidBruant** [betagouv/ecolab-data#586]
> Quel téléphone avez-vous ?

J'ai répondu un peu au pif parce qu'entre "moins de 4,5 pouces" et "moins de 5 pouces", je ne sais pas faire la différence

**Comment by Benjamin-Boisserie-ABC** [comment]
Cette nomenclature provient des facteurs d'émissions qui s'intitulent ainsi dans la Base Carbone.
Nous allons chercher à améliorer la formulation. Voir #869
