### ISSUE TITLE
Formulation de questions avec "votre voiture" alors que je n'en ai pas

### ISSUE THREAD

**Issue by DavidBruant** [betagouv/ecolab-data#589]
Concernant la voiture, j'ai répondu que je faisais 100km/an en voiture (parfois en covoiturage, en montant dans la voiture d'amis, ou en location, etc.). Après on me demande si j'ai ma propre voiture et je réponds que non et plus tard, on me demande "Quelle est la consommation moyenne de votre voiture ?"
Et j'étais surpris par la formulation parce qu'avant cette question, j'avais dis que je n'avais pas de voiture, donc "votre voiture" n'est pas vraiment pertinent

**Comment by laem** [comment]
Merci pour la remarque. Je crois que tu exprimes très précisément ce que d'autres ont voulu dire 👍 . 
On va rendre le "votre" plus neutre. Parce qu'à ce stade, dans publi.codes, on ne peut pas modifier le texte des questions dynamiquement. 

Il faudrait pour ça intégrer un système de templating dans le texte des questions, ce que je trouve trop compliqué à ce stade.
