### ISSUE TITLE
Le détail de l'impact des services publics n'est pas disponible

### ISSUE THREAD

**Issue by DavidBruant** [betagouv/ecolab-data#590]
Je me suis retrouvé avec un bilan à 4 tonnes, j'ai vu que l'objectif, c'est 2 tonnes. Mon plus gros poste, c'est les services publiques avec 1,3 tonnes... et il n'y a aucun détail sur ce quel service public est le plus problématique, etc.
Mes leviers d'actions sont limités, mais j'aimerais bien savoir quand même :-p

**Comment by laem** [comment]
Voir #3
