### ISSUE TITLE
Culpabilisateur pour les gens qui habitent en campagne/montagne

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#596]
Il est très intéressant de voir que depuis que j'ai quitté paris pour la montagne, je suis plus polluante parce que j'ai une voiture, même si je suis végétalienne et que les autres postes polluants sont très limités. L'idée serait de faire croire que nous devrions tous prendre des transports en commun comme dans les grandes villes ? Ils sont inexistants et le resteront. Arrêtez cette vaste plaisanterie visant à créer une fracture entre les méchants provinciaux et leurs voitures et les gentils citadins non pollueurs.

**Comment by laem** [comment]
Une voiture, ça pollue, qu'on l'utilise en montagne ou en ville ou entre les villes ou en vacances. 
Notre rôle n'est pas de pondérer les actions polluantes en fonction des situations géographiques. 

> Ils sont inexistants et le resteront

Factuellement faux. 

> Arrêtez cette vaste plaisanterie visant à créer une fracture entre les méchants provinciaux et leurs voitures et les gentils citadins non pollueurs.

Je vous conseille de suivre ce compte twitter, qui raconte régulièrement ses efforts pour vivre dans la campagne, avec une voiture, et viser quand même un objectif de neutralité carbone 😉
