### ISSUE TITLE
Erreur calcul amortissement voiture

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#597]
Bonjour
Il me semble qu'il y a une erreur dans votre formule de calcul d'amortissement pour la voiture. 
https://ecolab.ademe.fr/apps/climat/documentation/transport/voiture/construction-amortie
Selon votre formule la "construction amortie" est égale coût de la construction divisé par l'âge + 1. Si on suit votre logique pour un véhicule électrique acheté neuf on a 12000 kg/ (1+1) = 6000 kgCO2e. Si je refais la simulation dans un an, mon bilan baissera à 12/3 = 4000 kg/CO2e. La troisième année 12/4 = 3000 kgCO2e. Si bien qu'au bout des trois ans on m'aura déjà imputer 6+4+3=13000 kg/CO2e !!! Soit plus que le coût de construction.
Au passage la correction +1 sur l'âge n'a pas lieu d'être car neuve = 1 et non pas zéro. 
La bonne approche selon moi serait d'imputer pour n'importe quelle année de possession 12/n (n étant la durée de vie du véhicule). Si la durée de vie est de 12 ans alors on retient 1000 kgCO2e quelque soit l'année.
Par ailleurs vous indiquez au bas de la page qu'une voiture est utilisée en moyenne 9 ans en citant un chiffre de wikipédia qui donne ... l'âge moyen du parc, ce qui est tout à fait différent de la durée de vie moyenne d'un véhicule ! De plus beaucoup de véhicules ont une seconde vie en Afrique.
Merci d'avance et merci pour tout votre travaille
Cordialement

**Comment by laem** [comment]
Merci, très pertinent ! 
Voir #225
