### ISSUE TITLE
Vérification des ordres de grandeur et valeurs par défaut

### ISSUE THREAD

**Issue by laem** [betagouv/ecolab-data#6]
Nous pouvons utiliser cet article d'une rare qualité (périmètre large et transparence des sources) pour vérifier la cohérence de notre calcul, et en particulier les valeurs par défaut. 

http://ravijen.fr/?p=440

On notera par exemple une 1ère incohérence : 
- dans micmac, le textile est estimé à 0.3kgCO2e/€
- sur l'article, l'empreinte des vêtements est à 736kgCO2e

Ce qui supposerait que le Français moyen consomme 2000€ / an de textile, et ça paraît délirant.

**Comment by fjg** [comment]
Ravijen commence à dater sur certains aspects (dont le textile, cf. étude ADEME de 2018). Les derniers FE sont ceux de la BC.

**Comment by laem** [comment]
Je ferme. La 1ère vérification a été faite, il s'agit maintenant d'itérer pour être le meilleur modèle existant :)
