### ISSUE TITLE
Synthèse des résultats à compléter 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#604]
J’ai trouvé le questionnaire assez intuitif, cependant le résultat est assez décevant: donné en TeC par grand poste, avec renvoi sur des généralités et l’objectif certes vertueux de 2teC.... Il manque 
- un détail individuel sur ce qui pèse le plus issu du questionnaire
- des comparaisons avec une moyenne, Voire un ecart-type... 
A mon sens c’est plus utile pour passer à l’action !

**Comment by Benjamin-Boisserie-ABC** [comment]
Prise en compte de la remarque concernant la mise en avant des 3 ou 5 postes les plus significatifs pour l'utilisateur.
Concernant la comparaison moyenne voir #868 
Le volet "passage à l'action" est en cours de développement pour essayer de proposer des actions qui collent à l'empreinte carbone et autant que possible à son profil (urbain, périurbain, rural, etc.)
