### ISSUE TITLE
Habitation et construction 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#607]
Le secteur de la construction représente 50% des émissions CO2. Si vous intégrez l âge de la voiture et faites une simulation Sur l utilisation du numérique et de l'alimentation. cela ne serait ce pas opportun de demander l âge de l habitation, type d habitation, construction traditionnelle etc et la valeur PEB? Pour affiner les valeurs co2???

**Comment by laem** [comment]
Tout à fait, voir #111
