### ISSUE TITLE
Achat énergie bas carbone

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#609]
Bonjour, j'achète du biogaz et de l'hydrolique et je trouve dommage que nous puissions le préciser ici car ma conso de gaz fait monter mon empreinte CO2 alors que ce n'est pas représentatif de mes consommations.
Idem pour ma voiture de fonction dont les émissions sont compensées à 100%, aucun moyen de le préciser ici et enfin quid des vêtements de seconde main et de leur empreinte CO2 moindre

**Comment by laem** [comment]
Bonjour, 
les systèmes d'achat de biogaz, sont à ma connaissance comme les fournisseurs d'électricité "verte" : nous n'avons pas accès à une estimation réelle de l'empreinte de leurs offres. 

> Idem pour ma voiture de fonction dont les émissions sont compensées à 100%

Nos Gestes Climat n'a pas pour objectif de faire le bilan des compensations carbone. 

> quid des vêtements de seconde main et de leur empreinte CO2 moindre

Voir #44
