### ISSUE TITLE
Le calculateur ne demande à aucun moment si la personne utilise le chauffage ou non.

### ISSUE THREAD

**Issue by ryanzidago** [betagouv/ecolab-data#611]
Bonjour à vous,

Le calculateur ne demande à aucun moment si la personne souhaitant calculer son empreinte carbonne utilise le chauffage ou non. Sachant que le chauffage à l'air de jouer un rôle important dans l'empreinte carbonne d'une personne, je trouve qu'il serait pertinent d'ajouter cette option.

:pray:

**Comment by ryanzidago** [comment]
ah autant pour moi, il suffit de mettre non partout aux questions concernant le chauffage :facepalm:

**Comment by laem** [comment]
Oui tout à fait, ou simplement de renseigner les facteurs énergétiques.
