### ISSUE TITLE
 CULPABILISANT ET INUTILE

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#616]
Il faut parvenir à deux tonnes, alors que de base, votre calcul comporte 1,3 tonnes pour les services publics, ce qui laisse 0,7 en responsabilité de l'individu qui doit manger ( ce qui correspond déjà à 0,7 même en ne mangeant pas de produits animaux) et il faut encore  se vêtir, se loger et se déplacer !

**Comment by laem** [comment]
C'est la triste réalité. 
Cela dit, nous nous devons d'expliquer ce que sont ces 1.3 tonnes. Ce n'est pas chose aisée à vrai dire.
Voir #198
