### ISSUE TITLE
contreproductif?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#618]
Mon empreinte est de 6,7t . Pour atteindre les 2t de neutralité carbone il faudrait que j arrête de manger,  que je sois sdf et que je ne bouge plus... même pour une écolo ayant 40 ans de service ce n'est pas  réjouissant. 
Votre étude ne fait mention ni des arbres qui absorbent en moyenne 30kg de Co2/an ni des océans qui absorbent 30% des émissions de Co2.
Ne considérons que les arbres.  En 2020 , sur la base de l étude menée en 2015, on peut estimer qu'il y a 2930 milliards d arbres sur terre,  divisé par 7,8 milliards de personnes,  ça fait 375 arbres par personnes.  Mes 6,7t sont absorbés par 223 arbres. Déjà sans océans je suis dans les clous. 
J'ai trouvé votre objectif de 2t contreproductif. Si je n avais pas les données que je viens de citer,  je penserais que c est perdu d avance et que ce n'est plus la peine de faire d efforts.
Par contre il est urgent de planter des arbres car le bilan annuel est négatif. 
A cet égard il serait bon de mentionner qu'un moteur de recherche fonctionne avec des panneaux solaires et plante des arbres avec les  bénéfices dégagés : Ecosia 
Bonne continuation à  vous

**Comment by laem** [comment]
>  Votre étude ne fait mention ni des arbres qui absorbent en moyenne 30kg de Co2/an ni des océans qui absorbent 30% des émissions de Co2.

Ce n'est pas notre rôle. Le GIEC prend évidemment en compte la biomasse pour déterminer les budgets carbone. Ces 30kg/an ne correspondent-ils pas à un arbre en croissance, ce qui n'est à ma connaissance pas le cas de la majorité des arbres sur terre ?

> J'ai trouvé votre objectif de 2t contreproductif. 

C'est notamment pour cela que nous accompagnons cet objectif de cet article, qui trace un chemin moins ambitieux : https://ecolab.ademe.fr/blog/général/budget-empreinte-carbone-c-est-quoi.md

> Si je n avais pas les données que je viens de citer, je penserais que c est perdu d avance et que ce n'est plus la peine de faire d efforts.
Chaque dixième de degré de réchauffement peut avoir des conséquences désastreuses. Le réchauffement climatique n'est pas un tout ou rien. Rien n'est perdu d'avance, tout effort -- même le votre qui d'ailleurs vous a déjà permis de **diviser par deux** votre empreinte par rapport au français moyen est super 👏.

>  Par contre il est urgent de planter des arbres car le bilan annuel est négatif.

Il est surtout urgent d'émettre moins / déforester moins (en conséquence, manger moins de viande). Les arbres peuvent nous aider, mais c'est loin d'être la panacée.

>  A cet égard il serait bon de mentionner qu'un moteur de recherche fonctionne avec des panneaux solaires et plante des arbres avec les bénéfices dégagés : Ecosia

Nous n'avons pas d'estimation de l'impact positif d'utiliser ce moteur de recherche plutôt qu'un autre. Il se pourrait bien qu'une recherche sur Google consomme 2x moins d'énergie que sur Ecosia. Et nous n'allons pas faire de pub pour des entreprises ici, aussi vertes se déclarent-elles.
