### ISSUE TITLE
Feedback sur le calculateur

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#62]
Bonjour,

Merci d'avoir créé ce calculateur très utile.
Quelques remarques après l'avoir utilisé. 

- L'empreinte moyenne d'un Français n'est pas claire. Au début, le calculateur indique 9.2t et à l'issue du test 11t, sachant qu'il me semble qu'il est en fait de 12t.
- Il faudrait pouvoir diviser des usages par le nombre de personnes du foyer. Ex.: nous sommes deux à nous partager l'usage d'une tablette. Pour cette dernière il manque aussi le temps passé dessus.
- Pour l'ordi, pouvoir indiquer qu'on a un ordi fixe ET un portable.

Cordialement

**Comment by Benjamin-Boisserie-ABC** [comment]
Bonjour,

L'empreinte carbone moyenne d'un français est en général située entre 11t et 12t. On utilise souvent le chiffre de 12t par abus de langage pour faciliter la compréhension de l'objectif des 2t (en réalité 1.8t) : en gros on divise par 6.

Le calculateur présente 9.2t car toutes les données n'ont pas encore été consolidées. Au fur et à mesure de ce travail de consolidation nous allons nous approcher de +/- 11t. Au moment ou je vous réponds ce chiffre est d'ailleurs de 10.1t

La déclinaison de l'outil et son utilisation pour un foyer est prévu à plus long terme. Nous commençons par l'individu.

Nous comptons intégrer une question sur l'ordi portable aussi @laem 

Cordialement,

Benjamin de l'ABC
