### ISSUE TITLE
Classe énergétique du logement

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#620]
Bonjour, serais-ce pertinent d'ajouter la classe énergétique de l'habitation. J'habite dans un logement neuf, classe A et j'ai très peu, voir pas mis de chauffage au gaz dans mon logement.

**Comment by laem** [comment]
Bonjour, si vous n'avez presque pas mis de chauffage, il vous suffit de renseigner votre facture en kWh ou en €. Pas besoin à ce stade de la classe énergétique :)
