### ISSUE TITLE
Pas beaucoup d'options de petit-dejeuner. Egalement, il ne faudrait pas obliger à remplir un certain nombre de repas

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#621]
Bonjour, 
Une petite remarque concernant le petit dejeuner. Il devrait y avoir plus d'options (pain + confiture, viennoiseries, céréales avec/sans lait, ...)
Pour le nombre de repas et s'ils sont végétalien/vegan/carnien, je trouve qu'il ne devrait pas y avoir un nombre de repas obligés. Pour le petit dej, les gens ont la possibilité de dire qu'ils n'en prennent pas, je trouve qu'on devrait avoir la possibilité de noter si l'on saute le dinner par exemple

**Comment by laem** [comment]
Pour les options : #453 
Pour le nb de repas voir #207
