### ISSUE TITLE
Végétalien vs Végétarien: NE PAS CONFONDRE

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#622]
Bonjour, 

Je remarque simplement que la distinction entre végétalien et végétarien n'est pas encore très claire, et ne pousse pas à prendre conscience de l'impact des produits laitiers et autres dérivés de l'élevage industriel sur nos émissions carbone. 
Je vous prie de bien vouloir clarifier cette distinction et les calculs afin que le stimulateur prenne cette différence en compte. 
Merci pour votre travail!

**Comment by laem** [comment]
Bonjour, c'est bien le cas. Nous avons un plat végétarien, et un autre végétalien. Si cela ne convient pas, dites-nous précisément pourquoi, votre remarque est trop vague.
