### ISSUE TITLE
Impact de fabrication de maison ou véhicule

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#623]
Bonjour, il est inclus dans le calcul de l'impact d'une voiture ou d'une maison l'impact de sa construction. Cela peut être pertinent dans le cas d'un achat neuf, mais dans le cas d'un achat d'occasion est-ce que cela ne pourrait pas être pris en compte (comme dans la partie loisirs vous distinguez neuf / occasion) ? Normalement nous avons moins contribué à son emprunte, en achetant d'occasion on essaye d'éviter quand même la production dans le neuf et on réutilise le plus possible l'existant.

**Comment by laem** [comment]
Voir #111 pour le logement et #674 pour la voiture, ce dernier bientôt corrigé :)
