### ISSUE TITLE
pouvoir lisser sur plusieurs années

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#625]
je ne prend l'avion qu'une fois tout les 3 ou 4 ans. J'aimerais pouvoir rentrer ce type de paramètres afin d'avoir une moyenne sur une année, sans fausser mon calcul dans un sens ou dans l'autre

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, le mieux est de diviser vos heures de vols ponctuelles par 3 ou 4 pour obtenir des heures de vols "annuelles"
