### ISSUE TITLE
Comptabilisation de l'empreinte carbone professionnelle

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#627]
Bonjour, 

Je ne comprends pas très bien pourquoi il ne faut pas comptabiliser l'impact carbone des activités professionnelles de chacun (trajets en avion, consommation d'énergie, ...), sachant qu'il me semble que le chiffre de 11tCO2eq/pers/an pour un français moyen correspond à un chiffre global qui inclue vie personnelle et vie professionnelle. 

De plus, lors de la réalisation du bilan carbone d'une entreprise ou d'un organisme, sont comptés à l'intérieur les trajets domicile-travail de ses salariés (et souvent l'alimentation du midi qui s'inclue dans le critère "achats de biens et de services") et ces critères sont justement demandés dans le calculateur.

**Comment by laem** [comment]
> Je ne comprends pas très bien pourquoi il ne faut pas comptabiliser l'impact carbone des activités professionnelles de chacun (trajets en avion, consommation d'énergie, ...), sachant qu'il me semble que le chiffre de 11tCO2eq/pers/an pour un français moyen correspond à un chiffre global qui inclue vie personnelle et vie professionnelle. 

Parce que cette empreinte est intégrée dans les consommations, du moins théoriquement. Si un employé de chez Total prend l'avion pour aller visiter une plateforme pétrolière, les émissions de son vol son comptabilisées pour Total, et donc in fine, dans l'empreinte d'un km de voiture ayant utilisé de l'essence de chez Total. 

> De plus, lors de la réalisation du bilan carbone d'une entreprise ou d'un organisme, sont comptés à l'intérieur les trajets domicile-travail de ses salariés (et souvent l'alimentation du midi qui s'inclue dans le critère "achats de biens et de services") et ces critères sont justement demandés dans le calculateur.

Très bonne remarque. C'est une question que l'on s'est posée dans #3 . Normalement, tel que je comprends la chose aujourd'hui, les trajets dom-tra ne sont pas comptabilisés dans l'empreinte d'un steak ou d'1km d'essence. Mais cela doit être vérifié.

**Comment by Benjamin-Boisserie-ABC** [comment]
> Je ne comprends pas très bien pourquoi il ne faut pas comptabiliser l'impact carbone des activités professionnelles de chacun (trajets en avion, consommation d'énergie, ...), sachant qu'il me semble que le chiffre de 11tCO2eq/pers/an pour un français moyen correspond à un chiffre global qui inclue vie personnelle et vie professionnelle.
Les activités professionnelles relèvent du périmètre de comptabilité de l'entreprise. Si vous devez prendre l'avion pour vous rendre à un séminaire dans le cadre du travail, "ce n'est pas de votre ressort". Les émissions seront imputées à l'empreinte carbone de l'entreprise. Ca sera donc à elle de mettre en place des actions pour réduire son empreinte en commençant dans cet exemple à faire voyager ces collaborateurs en train et non en avion (quand cela est possible). Le chiffre de 11 t ne correspond qu'à la sphère personnelle même si le sphère professionnelle a une influence indirecte. Nous devons en effet nous rendre tous les jours au travail et pour beaucoup d'entre nous y manger sur place/cantine. Néanmoins, nous avons le choix quant à notre mode de déplacement (parfois complétement dépendant de notre environnement je le conçois) pour s'y rendre et le choix de choisir notre repas

> De plus, lors de la réalisation du bilan carbone d'une entreprise ou d'un organisme, sont comptés à l'intérieur les trajets domicile-travail de ses salariés (et souvent l'alimentation du midi qui s'inclue dans le critère "achats de biens et de services") et ces critères sont justement demandés dans le calculateur.
En effet, les experts de la comptabilité carbone encouragent les entreprises à prendre en compte les trajets domicile travail et les repas dans leur périmètre de comptabilité lorsqu'elle réalise un bilan d'émissions de GES (BEGES). Ceci pour plusieurs raisons : 
1. elles participent indirectement à ces émissions. Dans la nomenclature de la comptabilité carbone on les appellent les  émissions indirectes (en opposition aux émissions directes liées à l'utilisation d'énergie primaire, d'électricité, de chaleur et de froid). Il est courant que ces émissions indirectes représentent les 3/4 d'un BEGES d'un entreprise  
2. Ne pas les prendre en compte ce serait donc "oublier" les 3/4 des émissions que participent à émettre (même indirectement) une entreprise. C'est d'ailleurs ce qui fait par de nombreuses entreprises à la communication et l'action environnementale très douteuse
