### ISSUE TITLE
Amélioration du calcul de la partie Numérique

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#628]
Bonjour,

Dans mon cas, c'est la partie Pro à travers les usages numériques qui pèse surement le plus dans mon bilan carbone : c'est dommage donc que ce ne soit pas pris en compte : e-mails, visio, etc.

Nous avons fait des simulations de notre impact chez KAPT et ce n'était pas du tout anecdotique, depuis nous essayons d'améliorer cela.

Merci d'avance de votre retour et à votre disposition pour en discuter.

S.G.
(sg@kapt.mobi)
(@guardios)

**Comment by laem** [comment]
> Dans mon cas, c'est la partie Pro à travers les usages numériques qui pèse surement le plus dans mon bilan carbone : c'est dommage donc que ce ne soit pas pris en compte : e-mails, visio, etc.

Non, sûrement pas. A moins d'avoir fait des choix drastiquement hors de la norme sur le reste de sa vie personnelle (végétalien, 0km en voiture, etc.), vos emails et votre visio sont négligeables dans votre empreinte climat totale.

> Nous avons fait des simulations de notre impact chez KAPT et ce n'était pas du tout anecdotique, depuis nous essayons d'améliorer cela.

Il nous faudrait cette simulation pour pouvoir en discuter. Je vous contacte par mail.
