### ISSUE TITLE
quelques points

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#635]
la question sur l'alcool n'est pas claire. une consommation moderee a 0.5l/semaine, c'est de l'alcool pur?
il serait interessant de choisir au debut entre le bilan du foyer (conjoint(e)+enfant(s) )ou un bilan individuel.
tres user friendly en tout cas.

**Comment by Benjamin-Boisserie-ABC** [comment]
Non c'est la quantité de boisson alcoolisé pas la quantité d'alcool pur.
Concernant le foyer voir #113
