### ISSUE TITLE
Erreurs?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#636]
Bonjour il y a eu plusieurs moments où les questions prêtaient à confusion, genre : Mangez vous blanc ou noir ? Réponses Oui ou Non.
Par ailleurs je suis curieux de savoir sur quoi repose les différences, j'avais fait le test avec un autre moteur et mon empreinte était de 1t8, ici elle est de 3 tonnes.

**Comment by laem** [comment]
> Mangez vous blanc ou noir ? Réponses Oui ou Non.

C'est la question du lait végétal. Elle peut prêter à confusion, mais n'est pas non plus si illisible que vous le dites. A travailler.

>  Par ailleurs je suis curieux de savoir sur quoi repose les différences, j'avais fait le test avec un autre moteur et mon empreinte était de 1t8, ici elle est de 3 tonnes.

Tout est disponible ici, à vous de creuser ;)
