### ISSUE TITLE
Recommencer simulation sur mobile

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#639]
Après une première simulation, je souhaite en faire une seconde pour un ami à côté de moi sur le même terminal mobile. Mais le simulateur revient systématiquement sur les résultats. Il faudrait ajouter un raccourci permettant de recommencer. 

Good job en tous cas.

**Comment by laem** [comment]
Cliquez sur "Modifier mes réponses" puis "Tout effacer". 
On pourrait mettre une poubelle plus évidente, mais c'est aussi assez risqué, l'utilisateur peut tout perdre par erreur.
