### ISSUE TITLE
par individu ou par foyer

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#642]
Bonjour,
Vous dites que pour l'alimentation et le transport vous faites le calcul par individu. Mais doit-on rentrer des données par individu ou pour le foyer ? Avec division ensuite automatique par le nb de personnes dans le foyer ? Pas très clair.

**Comment by laem** [comment]
Je modifie la FAQ pour préciser que toutes les réponses doivent être données par individu
