### ISSUE TITLE
isolation du logement

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#643]
L'isolation du logement n'est pas demandé, seul la surface et le mode de chauffage.

En effet, je vie dans une résidence passive, avec chauffage collectif gaz, mais bien isolé et quasiment tout le temps éteint, et je me retrouve à 4T CO2 rien que pour le logement

**Comment by laem** [comment]
La consommation en kWh dépend de votre isolation. Donc indirectement, nous prenons en compte l'isolation. 
Avez-vous vu cette question des kWh ?
