### ISSUE TITLE
Impossible de relancer le test

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#656]
Après avoir déjà réalisé la simulation une première fois, il m'est impossible de refaire la simulation sur le même navigateur web.
Je tombe sur la synthèse de mes résultats et lorsque je souhaite relancer la simulation je me retrouve systématiquement sur cette page.

**Comment by Benjamin-Boisserie-ABC** [comment]
La version actuelle intègre un "bouton" "modifier mes réponses/tout effacer"
