### ISSUE TITLE
Décliner les ascenseurs ce qui est motorisé dans le quotidien.

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#657]
inclure ce qui est motorisé dans un immeuble : ascenseur (Prenez vous l'ascenseur ?). Car plus on est dans le "luxe" plus on consomme

**Comment by laem** [comment]
Les ascenseurs sont des transports : 
- en commun
- électriques
- sobres (moins de volume qu'une voiture pour déplacer un cors humain)
- qui ne parcourent que peu de distance par rapport à la voiture

Je ne vois d'intérêt à poser cette question que pour insister sur son super faible impact, ou comme une bonne occasion de faire de l'humour pour détendre la simulation qui affiche beaucoup de mauvaises nouvelles. 

Voir #415
