### ISSUE TITLE
TRANSPORT : Je ne trouve pas le moyen d'indiquer que la voiture est électrique

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#66]
Avec mon navigateur Opera.

**Comment by laem** [comment]
![image](https://user-images.githubusercontent.com/1177762/86566275-ad688180-bf69-11ea-9b71-859328035210.png)

J'ai testé le simulateur sur Opera 69, windows 10, la question de la motorisation est bien présente. Je ferme en attendant plus de détails ou d'autres retours.
