### ISSUE TITLE
Question kWh fioul pas adaptée

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#662]
Bonjour 
Je me permets de vous contacter car j’aime beaucoup le principe de votre questionnaire. Cela rentre vraiment dans une démarche forte de sensibilisation et je vous en remercie. Cependant une petite remarque : lorsqu’on se chauffe au fioul nous ne pouvons pas savoir les kWh consommés par notre foyer. Nous ne pouvons donc qu’être approximatif sur cette donnée qui pourtant on le sait pèse sur notre empreinte. Je souhaitais donc souligner cette valeur qui permettrait d’affiner ce questionnaire déjà complet. Encore merci et bonne continuation !

**Comment by dracorpg** [comment]
Salut à tous - et spécialement toi @laem - nouveau contributeur ici, je vais tenter d'apporter de traiter quelques sujets "faciles" pour commencer...

Pour un combustible liquide, la grandeur physique de compte est en effet plutôt le volume.
Serait-il pertinent d'utiliser le facteur d'émission volumique à 3,24 kgCO2e / litre de fioul domestique [issu de la Base Carbone](https://www.bilans-ges.ademe.fr/documentation/UPLOAD_DOC_FR/index.htm?new_liquides.htm) (sachant qu'il est correspond à 0,329 kgCO2e / kWhPCI, très proche de la valeur actuellement dans le code 0,324) ?

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet il semble pertinent de pouvoir donner une consommation en litre pour faciliter la saisie de l'utilisateur.
Voir #867
