### ISSUE TITLE
Evolution de l'application 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#663]
Application simple et accessible. Il faudrait ensuite un mode suivant "maintenant j'agis" qui permettrait de voir quelle action individuelle prioriser, et le gain CO2 pour chaque action que j'envisage

**Comment by laem** [comment]
Merci pour le retour ! C'est prévu ;) 
A tester sur https://action--ecolab-climat.netlify.app/actions?branch=action
