### ISSUE TITLE
Forme et préparation au questionnaire

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#666]
Bonjour, quelques remarques de forme après avoir répondu au questionnaire:
- Alimentation: prévenir en amont que 14 repas sont "à distribuer"
- Transport: permettre l'addition automatique des kms par le biais des onglets proposés (ex: je clique deux fois sur traversées France -> 2*2000km = 4000km)
- rappeler qu'on répond sur la base de moyennes/an 
- proposer en amont de vérifier/collecter qques infos avant de débuter: facture d'électricité, autres factures (gaz? fioul?)... pour éviter des réponses rapides et très approximatives.
- indiquer en amont une fourchette estimée du temps de réponse au questionnaire.
- Habillement: l'achat de chaussures fait-il partie du textile? 
Merci pour votre travail.

**Comment by Benjamin-Boisserie-ABC** [comment]
Merci pour vos retours. 
Plusieurs remarques ont déjà été identifiées
