### ISSUE TITLE
mesurer au fur et à mesure des réponses l'empreinte carbonne

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#678]
Ce serait intéressant de voir par catégorie (transport / chauffage ...) l'empreinte carbone que nous générons. Ca permettrait de réfléchir en répondant au questionnaire.

**Comment by laem** [comment]
Mmmh, là je ne comprends pas. Soit le graphique ne s'affiche pas, soit ça a été fait sur un écran trop petit et la personne n'a pas défilé la page vers le bas ❓
