### ISSUE TITLE
Possibilité de refaire le test

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#680]
Bonjour,

je me permets de vous envoyer ce retour, car lors de l'utilisation de cette application. Il a été pour moi impossible de la réutiliser car on retourne toujours sur le premier résultat. je pense que l'ajout d'un bouton interface "refaire le test" peut être judicieux.

Cordialement,

MG

**Comment by Benjamin-Boisserie-ABC** [comment]
la version actuelle de l'outil permet maintenant de modifier les réponses que l'on souhaite
