### ISSUE TITLE
mode chauffage, chauffage urbain

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#681]
Bonjour! J'habite Grenoble et nous avons le plus gros chauffage urbain de France derrière Paris, il semble que ce mode de chauffage ne soit pas intégré dans le calcul... Du coup j'ai répondu "non" aux questions me demandant si j'étais chauffé au charbon ou au fioul, mais je suppose que du coup j'ai zéro en chauffage, ce qui n'est à priori pas exact, sauf à considérer que mes ordures me chauffent (en vrai ils utilisent aussi 15% de charbon... :(

**Comment by laem** [comment]
Bonjour, très bonne remarque ! C'est déjà prévu. #126
