### ISSUE TITLE
On ne peut pas ne pas avoir de voiture selon ce calculateur...

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#683]
Lorsque je clique sur "je n'ai pas de voiture" il continue à me poser des questions sur cette voiture et lorsque je mets qu'il n'y a personne qui le prend, il me met une empreinte infinie...

**Comment by laem** [comment]
Vous avez répondu juste avant la question "combien de kilomètres en voiture" avec une réponse non nulle, non ? Dans ce cas, c'est pertinent de savoir avec quelle voiture vous les avez fait (en moyenne).
