### ISSUE TITLE
Il manque des choses

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#685]
J'ai une pompe à chaleur par exemple, et j'ai aussi une voiture électrique dans mon foyer, j'utilise sois l'une sois l'autre. 
Cordialement, Lisa

**Comment by laem** [comment]
Voir #22 pour la pompe.
Pour la voiture, si vous avez 2 voitures pour 2 personnes, attribuez-vous une voiture ou faites une moyenne. Nous n'avons rien prévu pour ça pour l'instant, mais toute idée est la bienvenue.
