### ISSUE TITLE
Pourquoi les matériaux et la fabrication des équipements numériques (smartphone fabriqué à l'étranger, ordinateur...) n'est pas pris en compte? 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#686]
C'est moi qui achète, utilise, fait fonctionner le commerce mondial avec ces outils qui sont rarement fabriqués en France, dont les minerais extraits viennent du monde entier,... donc ça devrait rentrer sans ma consommation.

**Comment by laem** [comment]
C'est déjà le cas. Par contre, notre modèle est laaaaaaargement améliorable. Voir #56
