### ISSUE TITLE
Calcul construction

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#687]
Bonjour,

Tout d'abord merci et bravo pour cet outil ! 

J'ai été surpris de voir dans le calcul de l'impact de l'habitation une partie "coût de construction". Hors ma maison date de 1780 donc son impact CO2 n'est (à priori) pas comparable avec celui d'une habitation neuve. 
=> il faudrait rajouter la date de construction de l'habitation dans les critères (comme pour la voiture).

Merci !

**Comment by laem** [comment]
Bonne remarque, la correction arrive bientôt :)

**Comment by laem** [comment]
Voir #111
