### ISSUE TITLE
Épargne

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#688]
Bonjour, est-ce qu'il y aurait moyen d'intégrer l'effet de notre épargne ? Notamment si nous la placons dans une banque écologique, sociale et solidaire ou traditionelle ? Ou alors, peut être que ce changement a trop peu d'importance, ou encore est-il intégré aux services publics ? Merci !

**Comment by laem** [comment]
Bonne remarque, voir #24 
En bref, c'est un double comptage. Mais c'est quand même un poste important, que nous essaierons de réintroduire.
