### ISSUE TITLE
Retour sur votre similateur

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#69]
Points positifis:
- fluide, simple d'utilisation, rapide
- petites jauges qui bougent en fonction des réponses
- propositions de réponses
- partie numérique plus complète. Ca donne envie de questionner si on a plusieurs téléphones, ordinateurs, appareils photo.
- partie banque: simple et efficace

Points négatifs:
- alimentation: partie trop simplifiée, bien pour la rapidité, mais réducteur avec ces formulations. ex: pour le régime boeuf une fois/semaine, il pourrait être bien d'indiquer l'équivalent en autres viandes et poisson. 
- De plus, peut-on quantifier l'impact d'un repas fait maison, vs un repas en restauration? 
- il n'y pas d'info sur le type d'habitat (maison/appart, âge, isolation), ni sur les types de fournisseurs d'énergie (verte vs pas verte). A voir si l'impact est suffisamment important pour être pertinent.

Remarque: on pourrait peut-être avoir à la fin un ou des graphiques exemples de ce qu'il faudrait dépenser par secteur pour arriver à 2T?

Merci et bon courage pour le développement de votre outil!

**Comment by laem** [comment]
> De plus, peut-on quantifier l'impact d'un repas fait maison, vs un repas en restauration?

Bonne question. Cela me parait compliqué vu la diversité des cas possibles. On pourrait par contre faire une fiche action "changer mes plaques de cuisson", la différence entre gaz/résistance/induction étant énorme. @Benjamin-Boisserie-ABC

**Comment by laem** [comment]
> Remarque: on pourrait peut-être avoir à la fin un ou des graphiques exemples de ce qu'il faudrait dépenser par secteur pour arriver à 2T?

C'est compliqué, car ça dépend de chacun. Certains peuvent choisir de privilégier le voyage par exemple.
