### ISSUE TITLE
Correction voiture + ajout salle de bain

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#698]
Bonjour,
Concernant la partie voiture, il ne me semble pas qu'il y ait la possibilité de cliquer sur "je ne possède pas de voiture" ou "j'utilise la voiture uniquement comme passager", ce qui fausse la donne.

Ensuite, je suis étonnée qu'il n'y ait pas de chapitre consacré à la consommation dans la salle de bain, alors que c'est LE premier champ auquel s'attaquer lorsque l'on s'engage dans une démarche plus écologique (utilisation d'un oriculi aulieu de coton-tiges, disques démaquillant lavables et non jetables, temps passé sous la douche (consommation d'eau), utilisation de la douche plutôt que de la baignoire, utilisation de pains de savon plutôt que de gel douche, utilisation de protections périodiques jetables / recyclables / lavables, entre autres).

**Comment by laem** [comment]
>  Concernant la partie voiture, il ne me semble pas qu'il y ait la possibilité de cliquer sur "je ne possède pas de voiture" ou "j'utilise la voiture uniquement comme passager", ce qui fausse la donne.

L'important est que vous faites des km en voiture. A partir de là, que vous possédiez ou non cette voiture, on va devoir savoir ses caractéristiques

>  la consommation dans la salle de bain, alors que c'est LE premier champ auquel s'attaquer lorsque l'on s'engage dans une démarche plus écologique

Source ? 

La consommation d'énergie pour chauffer l'eau de votre douche ou bain est en effet importante, mais elle est incluse dans les questions de vos factures énergétiques en kWh :) 
Pour le reste, les objets d'hygiène, nous n'avons pas encore ce détail de calcul. Mais du point de vue climat, c'est peu significatif par rapport au reste de l'empreinte (transport, chauffage, etc.)
