### ISSUE TITLE
Données régime végétarien

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#699]
Bonjour, 
Sur cette page https://ecolab.ademe.fr/apps/climat/actions, vous indiqué qu'un régime végétarien économise 1,4T de CO2 ou encore qu'arrêter l'avion économise 307kg de CO2. 
J'imagine qu'il s'agit de la consommation moyenne de viande ou d'avion dans l'empreinte carbone d'un.e Français.e ? Où peut-on trouver ces chiffres ? 

Merci !

**Comment by laem** [comment]
Bonjour, 
sur les pages action, il y a un lien "comprendre le calcul". Tout y est normalement, mais n'hésitez pas à revenir avec des questions plus précises une fois que vous avez visité ces pages.
