### ISSUE TITLE
UX alimentation

### ISSUE THREAD

**Issue by laem** [betagouv/ecolab-data#7]
Quelle question poser pour l'alimentation ?

Nous sommes partis dans #2 sur une seule question, quel est votre régime.

Dans MicMac version 2.6 (le tableur), il y a deux modes. 

Dans le mode débutant, qui ressemble à notre approche, on renseigne : 
- Nombre de repas végétariens
- Nombre de repas à base de viande rouge
- Nombre de repas à base de viande blanche

Puis boisson, eau en bouteille et zéro déchet. 

Le 2ème mode expert est très précis, mais très complexe (de mon point de vue, impossible). Nous le mettons de côté pour l'instant. 

**Proposition** 

On attend la sortie de la base agribalyse, puis on prend des menus types de la base carbone https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=repas, et on recalcule ces menus avec les nouvelles données. 

Puis dans un second temps, permettre à l'utilisateur de cliquer sur "construire mon régime personnalisé" : pour une semaine donnée, l'utilisateur choisit pour chaque repas le type de repas. Lundi, petit-dej céréales jus de fruit café; midi végétarien; soir viande "bas carbone".

**Comment by fjg** [comment]
Doublon #23
