### ISSUE TITLE
A quand le rapport téléchargeable ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#701]
Merci et bravo pour cette application très bien faite, même s'il reste quelques améliorations à faire que vous avez déjà identifiées. J'aimerais juste pouvoir télécharger un petit rapport avec mes principaux chiffres et les principales recommandations.

**Comment by laem** [comment]
Merci pour la suggestion. Quel serait l'idéal pour vous ? 
Un écran de fin plus détaillé, avec plusieurs pages, accessible sur une URL ? 
Un gros PDF ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Prise en compte de la remarque et du souhait d'obtenir un document récapitulatif
Le format est à discuter
