### ISSUE TITLE
1 voiture pour la famille ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#711]
Bonjour,
Ne possédant qu'une voiture pour la famille (2 adultes & 2 enfants), j'ai du mal à remplir le formulaire pour faire en sorte que l'amortissement de construction de ce véhicule soit répartis entre les deux adultes.
Il me semblerait plus clair d'orienter le formulaire pour parler de l'ensemble des véhicules du foyer.
Cordialement
Laurent M

**Comment by laem** [comment]
Merci pour votre remarque. Pour l'instant il suffit de remplir le taux d'occupation moyen du véhicule pour les kms que vous avez effectués. Ce n'est pas parfait, nous sommes d'accord.

**Comment by Benjamin-Boisserie-ABC** [comment]
Question traitée dans la F.A.Q
Cela rejoint les questionnements liés à l'approche par foyer #113
