### ISSUE TITLE
Donner l'imprécision du calcul ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#715]
Bonjour,

D'abord merci pour ce chouette outil, je prends plaisir à l'utiliser et le diffuser autour de moi.

J'ai conscience que l'outil se veut simple, et en cela, il est très bien conçus.

Je me permets tout de même une question : serait-il possible d'avoir une incertitude sur le calcul ? Pour prendre en compte la diverse provenance des appareils, etc.

Ca pourrait être quelque chose du style par ex : 5 tonnes +/- 0.3 tonnes, et expliquer pourquoi le calcul n'est pas exact. Ca peut permettre d'ouvrir les yeux sur des notions complémentaires !

Courte suggestion, mais encore une fois, j'adore l'outil pour sa simplicité !

Bonne journée

Cordialement

**Comment by laem** [comment]
Merci pour la remarque, c'est très intéressant. Malheureusement, je ne vois pas comment nous pourrions estimer cette imprécision. Elle n'est pas fournie dans les facteurs d'émission que nous utilisons. Quelqu'un a une idée ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Les incertitudes sont données avec les facteurs d'émissions (lorsqu'on télécharge les données de la base carbne). Je ne pense pas nécessaire de donner les ordres de grandeur au grand public, non pas car l'on veut souhaite cacher qqch mais car il faut savoir les décoder.
Tout d'abord une différence de +/- 0.3 tonne pourra très bien s'expliquer par les incertitudes intrinsèques des FE alors que le but de l'outil est de fournir l'ordre de grandeur et non d'avoir l'estimation parfaite au dixième prêt
Deuxièmement, certains FE ont parfois des incertitudes importantes. Ils seraient alors nécessaires de rentrer dans le détail de leur élaboration ce qui est fastidieux et complexe
