### ISSUE TITLE
Prise en compte du biogaz

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#719]
Bonjour,

Peut-on envisager d'intégrer le super joker "biogaz" pour le chauffage ? J'ai bien lu vos remarques sur les contrats "électricité verte", remarquent qui restent valables pour le gaz. Cependant, au vu de la différence d'empreinte entre gaz naturel et biométhane (e.g. 0.0395 kgCO2e/kWhPCS pour le mix moyen Biométhane selon la Base Carbone), ça vaut peut-être le coup de creuser, ou au moins d'en faire mention. En y mettant sans doute des pincettes, à l'image des copaings de C4 : http://www.carbone4.com/wp-content/uploads/2019/06/Publication-Carbone-4-biome%CC%81thane-et-climat.pdf

Merci pour votre travail !

Bastien

**Comment by laem** [comment]
Merci ! Voir #4  :)
