### ISSUE TITLE
Actions - aller au travail en covoiturage - pas forcément pertinent

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#721]
Bonjour. Merci cet outil.
Au niveau des actions, on me suggère de covoiturer pour aller au travail.
Toutefois cette remarque n'est pas pertinente car j'y vais aujourd'hui en transport en commun.
Les transports en voiture personnelle que j'effectue (et que j'ai comptabilisé dans l'outil) ne concernent jamais des déplacements domicile-travail

**Comment by laem** [comment]
Normalement, en cliquant sur la fiche action, vous aurez la question "Combien de jours par semaine prenez-vous votre voiture pour aller au travail ?". Votre réponse est 0, l'action passera donc à 0, vous êtes exemplaires cette fiche ne vous concerne plus ;)

On va améliorer l'interface pour que cela apparaisse mieux.
