### ISSUE TITLE
Suggestion de points à rajouter / compléter

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#722]
Il serait intéressant d'avoir une version courte et une longue comme pour l'outil Micmac. 

Potentiels éléments à ajouter :
Appareils électroniques : Ajouter la liseuse, les enceintes, écouteurs, appareils "dormant" tels que les vieux téléphones et ordinateurs qui pourraient être reconditionnés ou recyclés..., ajouter une option achats neufs/reconditionnés...
Transport : Proposer une option covoiturage, une évaluation de la distance en ferry...
Achats : Évaluer les vêtements achetés non pas en euros mais en quantité (e.g. 2 pulls, 3 tee-shirts etc = 5 achats) étant donné qu'on peut acheter un pull en coton certifié GOTS à 50 euros ou 3 pulls en coton peu respectueux de l'environnement. De fait, en dépensant moins dans les vêtements, on peut polluer plus. Il semble donc plus juste d'évaluer le nombre d'achat effectué...

**Comment by Benjamin-Boisserie-ABC** [comment]
La question des ratios monétaires est traitée dans la F.A.Q
Concernant les appareils électroniques nous sommes dépendant des données disponibles, ces données portant sur les appareils commun et possédés par l'ensemble des foyers.
Enfin Nos Gestes Climat se voulant un outil grand public, fait le choix de la simplicité afin d'engager le plus nombre d’utilisateurs à la simulation. Rajouter des questions c'est complexifier le modèle pour une évaluation carbone qui restera sensiblement la même.
Sachez que vous pouvez contribuer au développement de l'outil. On vous explique ici : https://github.com/betagouv/ecolab-data/blob/master/CONTRIBUTING.md
