### ISSUE TITLE
Facteurs d'émission repas végétalien et végétarien

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#723]
bonjour, 
je ne comprends pas le calcul de C02 des repas végétariens (environ 1364 kg CO2e par an) et végétaliens (environ 1450 kg CO2e).
Merci de vos lumières
HM

**Comment by laem** [comment]
Bonjour, tout est expliqué en ligne (cliquer sur "Comprendre les calculs") ou dans le code source ici https://github.com/betagouv/ecolab-data/blob/master/data/alimentation.yaml
