### ISSUE TITLE
Utilisation de la voiture du couple ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#724]
Nous avons une voiture, utilisée par 2 personnes .

**Comment by laem** [comment]
Pour l'instant, ce n'est pas possible de préciser combien de personnes possèdent la voiture. Nous avons fait le choix (plus simple) d'attribuer la construction de la voiture à ceux qui l'utilisent. Il suffit donc de remplir le nombre de passagers moyens. 
Je note la remarque.

**Comment by Benjamin-Boisserie-ABC** [comment]
lien avec l'approche foyer. Voir #113
