### ISSUE TITLE
deduire ses déchets - compostage 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#726]
Je composte 30% des déchets qui finissaient dans la poubelle d'ordures ménagères depuis 8 ans.

**Comment by laem** [comment]
C'est inclus dans la question du zéro déchets. Je l'ai précisé dans l'aide de la question ici https://github.com/betagouv/ecolab-data/commit/435fa4375d003636df464fcda1a7dee16c5428f1
