### ISSUE TITLE
Les objectifs me semblent tellement inaccessibles que je mise plus sur la réduction de la population

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#731]
J'ai fait mon bilan carbone. Après de nombreux efforts je parviens à 6 tonnes. Si j'étais fortuné je pourrais baisser d'une tonne ou deux. En revanche atteindre 2 tonnes me semble impossible à moins de vivre une vie à laquelle je préfère le suicide. D'où j'en viens à l'idée que la seule solution, c'est la réduction de la population. Distribuer des préservatifs avec une bonne pédagogie serait-il plus efficace que des efforts individuels toujours insuffisants ? Les objectifs de 2 tonnes par personne sont en effet tellement énormes qu'on peut être tenté de dire "après moi le déluge !"

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, à l'heure actuelle il est impossible de passer en dessous des 2 tonnes (que l'on vise en 2050 et pas tout de suite, il ne faut pas l'oublier). Rien que l'impact carbone des services publics représente plus de la moitié des 2 tonnes. Avoir à l'heure actuelle une empreinte carbone de 6 tonnes est déjà un excellent début et c'est presque avoir fait l'essentiel du chemin. 
En effet, c'est là tout l’enjeu de la transition au sens large. Induire des changements de comportements à l'échelle de l'individu mais aussi prendre conscience que la réduction globale de nos émissions (i.e. à l'échelle nationale) passera par des changements structurels profonds. Ces derniers ne peuvent se faire sans la participation des citoyens mais loin de nous de vouloir leur faire porter l'ensemble du poids de la transition. Ils ont une part à jouer dans la transformation de notre société vers une alternative bas carbone. Elle est nécessaire mais malheureusement pas suffisante.
Pour approfondir : http://www.carbone4.com/wp-content/uploads/2019/06/Publication-Carbone-4-Faire-sa-part-pouvoir-responsabilite-climat.pdf
