### ISSUE TITLE
... et la finance

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#732]
Merci pour ce calculateur carbone simplifié, très pédagogique. Bien que ce soit un sujet délicat à aborder pour certains, il faudrait ajouter un volet sur la finance. L'argent épargné par les particuliers est utilisé par les banques pour réaliser des opérations financière (prêts, placements, ....) qui ne sont pas neutres d'un point de vue carbone. Au minimum vous pourriez indiquer que ceci n'est pas pris en compte dans les calculs.

**Comment by Minigerbox** [comment]
Bonjour,
Je suis d'accord, surtout que ce volet était pris en compte dans une version antérieure.
C'est important car, même si ce n'est peut-être pas significatif en terme de "quantité", c'est un sujet auquel on ne pense pas de nous-mêmes donc ça peut nous permettre de nous poser la question de à quoi/à qui sert réellement notre argent épargné ?
Par exemple, depuis ma première visite sur votre simulateur (lorsque la finance était prise en compte), nous en avons parlé avec mon mari et avons choisi d'investir un peu d'argent dans un fournisseur d'électricité verte, plutôt que de le stocker simplement dans une banque.
Merci!

**Comment by martinregner** [comment]
Retour reçu par mail : 

> Bonjour, 
> 
> Merci pour cet outil facile et pédagogique.
> 
> J'avais testé la version bêta il y a qqs mois et mon emprunte liée à mon épargne m'avait interpelée. Elle était très importante en proportion d'autres éléments (sans doute car nous faisons beaucoup d'efforts par ailleurs). Ca a été une vraie prise de conscience pour notre famille. 
> 
> Je trouve qu'il serait intéressant de la réintégrer dans la version finale. Je serais curieuse de savoir pourquoi cela a été retiré. Des acteurs qui ne sont pas à l'aise avec cette réalité ? 
> 
> Merci encore pour votre travail.

**Comment by Benjamin-Boisserie-ABC** [comment]
Cette question nécessite des questions que l'on ne souhaite pas poser (montant de l'épargne, etc.) dans une volonté de partage et de diffusion de l'outil. Cette question pose également des soucis de comptabilité carbone avec un risque de double comptage.
Néanmoins nous aborderons l'impact carbone de l'épargne dans le volet "passage à l'action" avec un message porté sur la sensibilisation au poids de son épargne.
Voir #314
