### ISSUE TITLE
Ne pas mesurer les achats d'objets en €

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#734]
Hello,

Super le calculateur ! 

Une remarque : mesurer les consommations (vêtements, objets, etc.) en € est trompeur selon moi. 
Mon exemple: J'achète peu de choses, mais des choses de qualité (donc chères). Je dépense donc le même montant que si j'achetais une grande quantité de choses bas de gammes
Une solution serait éventuellement de compter les articles achetés pour différentes catégories (vêtements, objets de décoration, jeux, etc.)

**Comment by Benjamin-Boisserie-ABC** [comment]
Question des ratios monétaires traitée dans la F.A.Q
