### ISSUE TITLE
contribution

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#738]
bonjour,

nous sommes un groupe d'ingénieurs et nous voudrions contribuer.
qui doit-on contacter ?
merci

vianney languille

**Comment by laem** [comment]
Merci beaucoup @vianneylanguille pour tes contribution :) 
Je regarde dès que possible et on vous invite au plus vite pour discuter !

**Comment by laem** [comment]
C'est fait, on accueille maintenant sur notre chat les contributeurs :)
