### ISSUE TITLE
changer la façon dont l'empreinte construction d'un véhicule est répartie

### ISSUE THREAD

**Issue by vianneylanguille** [betagouv/ecolab-data#739]
en effet le comportement actuel est un peu perturbant, car si on passe d'une motorisation thermique à une électrique, l'empreinte carbone augmente!

ce qu'il faudrait, c'est prendre le kilométrage moyen des véhicules qui partent à la casse 'KMcasse', l'empreinte carbone de la production de la voiture 'PROD', et le kilométrage annuel réalisé par la personne 'KMan', et calculer l'amortissement annuel de la production 'AMOR' de la voiture comme ceci:
AMOR = PROD / (KMcasse / KMan)

de cette façon on a quelquechose de cohérent. Autrement, répartir l'amortissement de la production sur seulement les années de possession, c'est pas pertinent.

**Comment by laem** [comment]
Bonjour Vianney, as-tu vu [l'implémentation actuelle](https://github.com/betagouv/ecolab-data/blob/master/data/transport.yaml#L154) et [le fil de discussion](https://github.com/betagouv/ecolab-data/issues/225#issuecomment-689472950
) qui l'a précédé ?

**Comment by vianneylanguille** [comment]
Hello,

Oui tout à fait. mais je pense pas que ça reflète vraiment la réalité.

J'ai levé le point car un de mes collègues a fait la solution puis a
regardé ce que ça ferai avec une voiture électrique et ça a augmenté son
empreinte carbone. De quoi discréditer le simulateur en première
approximation, même si la logique qui a amené à cette implémentation a ses
raisons.

Vianney

**Comment by laem** [comment]
>  puis a regardé ce que ça ferai avec une voiture électrique et ça a augmenté son
empreinte carbone.

Ce qui est strictement vrai : l'achat d'une voiture électrique émet plus de GES à la production qu'une thermique équivalente.
Je pense qu'on ne peut plus ignorer cette réalité physique. 

l'implémentation actuelle est un compromis entre réalité physique (la production émet des GES au moment de l'achat) et interface utilisateur (quand je reviens faire une simulation, l'empreinte de la construction de ma voiture n'est pas 0, elle a été lissée dans le temps) grâce à un amortissement non linéaire, dégressif. 

Ta proposition est d'adopter un amortissement linéaire basé sur l'âge total de la voiture (pas de la possession de l'utilisateur), c'est bien ça ?

**Comment by laem** [comment]
Je ferme au profit de #816
