### ISSUE TITLE
On ne pose pas la question du vélo, du VAE, la marche, de l'ascenseur etc.

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#74]
pouvez vous ajouter les impacts pour un velo electrique ?

**Comment by laem** [comment]
Nous avons beaucoup de remarques sur l'absence du vélo, et globalement des moyens de transport sobres et décarbonés.

Pour nous, c'est évident qu'il n'y a pas besoin de poser la question. Ces retours nous montrent que non, ce n'est pas évident. 

Voir notamment #657 pour comprendre.

➡️ je suggère donc de poser une question rhétorique "Est-ce que vous marchez, faites du vélo (électrique ou non), etc." et d'expliquer que ce sont des moyens décarbonés. Ça détendra la simulation, qui en général n'affiche que des "mauvaises nouvelles" 😃
