### ISSUE TITLE
bilan du logement

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#746]
bonjour, 
pour la partie logement, il y a juste la notion de surface c'est très basique.
pour ma part, j'ai une maison qui a plus 100ans en terre, avec des huisseries rénovées en bois, sans pvc, sans alu, des enduits a la chaux au lieu du ciment. je suppose que  comme pour les véhicules l'age de la maison et les matériaux influence le bilan non?

**Comment by Benjamin-Boisserie-ABC** [comment]
Problématique de l'amortissement du logement déjà identifiée. Voir #735 et #111
