### ISSUE TITLE
Bien, à faire connaitre, mais très difficile.(il y a risque de découragement)

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#747]
Faire Préciser le périmètre au début du questionnaire( ex foyer fiscal et nombre d'individus rattaché) 
Est-ce le nombre de smartphone par individu? 
sur l'alimentation il faudrait prendre en compte les légumes du jardin +qques fruitiers (ex avec 180m² et 4 arbres fruitiers on est autonome à 85%).
Inclure les impacts positives telle que Pompe à chaleur/panneaux photovoltaique....). Etre plus exaustif sur les moyens d'actions. (dans une dynamique d'actions)
Mémoriser pour pouvoir le refaire dans 6 mois avec de nouvelles actions mises en place.
Etre plus dans les actions positives (ex nombre de covoit sur le mois écoulé = x T de Co2 gagnées.

**Comment by laem** [comment]
Merci pour vos remarques. Toutes les questions sont par individu, sauf précisé (par exemple : combien de personnes dans la voiture, dans le foyer). 

Pour le reste, nous avons déjà noté ces retours, merci.

Pour le découragement, voir #748

>  Etre plus dans les actions positives (ex nombre de covoit sur le mois écoulé = x T de Co2 gagnées.

Avez-vous vu la partie "actions" du simulateur ? https://ecolab.ademe.fr/apps/climat/actions
