### ISSUE TITLE
Objectif 2T

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#748]
Est-il possible de mettre le modèle 2T en ligne pour se faire une idée de ce qu’il faut faire pour y parvenir.
J’ai tenté l’exercice , cela ressemble à habiter une grotte sur une île déserte .

**Comment by laem** [comment]
Qu'entendez-vous par "mettre le modèle 2T en ligne" ? 
L'objectif est en effet difficile à atteindre. C'est à mon sens le gros intérêt de cette simulation : montrer l'ampleur du défi. 

>  J’ai tenté l’exercice , cela ressemble à habiter une grotte sur une île déserte .

Vous devez considérer que les 1.4 tonnes de services publics doivent et vont (c'est prévu dans la loi) être réduits, donnant de l'air à chaque citoyen pour contenir ses émissions.

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, à l'heure actuelle il est impossible de passer en dessous des 2 tonnes (que l'on vise en 2050 et pas tout de suite, il ne faut pas l'oublier). Rien que l'impact carbone des services publics représente plus de la moitié des 2 tonnes.
En effet, c'est là tout l’enjeu de la transition au sens large. Induire des changements de comportements à l'échelle de l'individu mais aussi prendre conscience que la réduction globale de nos émissions (i.e. à l'échelle nationale) passera par des changements structurels profonds. Ces derniers ne peuvent se faire sans la participation des citoyens mais loin de nous de vouloir leur faire porter l'ensemble du poids de la transition. Ils ont une part à jouer dans la transformation de notre société vers une alternative bas carbone. Elle est nécessaire mais malheureusement pas suffisante.
Pour approfondir : http://www.carbone4.com/wp-content/uploads/2019/06/Publication-Carbone-4-Faire-sa-part-pouvoir-responsabilite-climat.pdf
Lié aussi à #278
