### ISSUE TITLE
Problème action transport - Vélotaf

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#751]
Bonjour, le plan d'action me suggère d'aller au travail en transports en commun. Si le questionnaire m'avait demandé comment je me rends au travail, j'aurais répondu que je m'y rends à vélo :)
Sinon merci - je sais maintenant que je dois devenir végétarien :D

**Comment by laem** [comment]
Haha, merci pour ce retour qui montre bien les limites actuelles de notre implémentation des actions. 

On va les améliorer :)

**Comment by Benjamin-Boisserie-ABC** [comment]
Je ferme l'issue car le problème est résolu sur cette question/action particulière
Pour le reste on œuvre à une meilleure implémentation des actions
