### ISSUE TITLE
bug modifier les données

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#752]
Bonjour,
Après avoir obtenu mon résultat, je clic sur modifier mes réponses. Je souhaite modifier la section "Logement". Je cilc sur la première question Logement, je la valide, mais la suivante est toujours la dernière question à laquelle j'avais répondu. En d'autres termes, pas moyen de refaire un bloc genre Logement après le résultat. Ca serait pratique. Je vais déménager bientôt et aurais bien aimé voir ce que ça fera sur mon bilan...
Merci en tout cas pour cet outil vraiment super !

**Comment by Benjamin-Boisserie-ABC** [comment]
Prise en compte de la remarque
