### ISSUE TITLE
Questions à choix multiples et condition

### ISSUE THREAD

**Issue by Clemog** [betagouv/ecolab-data#753]
Bonjour, 

Merci pour ce simulateur sur lequel je travaille dans le cadre d'une option-projet à l'école Centrale Nantes dans le but de l'utiliser et l'adapter pour nos enjeux.

J'ai une interrogation concernant le langage Publicodes afin de continuer à travailler en attendant l'atelier en décembre.

Je ne parviens pas à mettre en place une condition « applicable si » relativement à une question à choix multiples. Par exemple, je souhaite poser une question : « Qui êtes-vous ? » avec les choix de réponses suivant : « Etudiant », « Doctorant », « Enseignant/Chercheur » ; puis, si la réponse est « Etudiant », demander l’année d’étude. 
De même, j’aimerais demander le moyen de transport utilisé pour la mobilité internationale effectuée par l’étudiant, afin d’éviter de poser la question « Avez-vous utilisé tel moyen de transport ? » « Oui/Non » ? pour chaque moyen de transport. 

Les exemples que je peux lire proposent des questions dont la réponse attendue est oui ou non. Peut-être avez-vous une piste pour m’aider ?

Merci beaucoup, à bientôt !

**Comment by laem** [comment]
Bonjour Clemog, tu as résolu cette question ?

**Comment by Clemog** [comment]
Salut ! 

Je me suis rendu compte que la question n'avait pas forcément lieu d'être puisqu'il est possible en fait possible de donner une condition dans le applicable si, par exemple:

profil . profil-type:
  question: Vous êtes ?
  formule:
    une possibilité: 
      choix obligatoire: oui
      possibilités: 
        - etudiant
        - doctorant
        - personnel de recherche ou enseignement
        - autre personnel

profil . autre question :
 applicable si : profil-type = 'etudiant'
 ...
Je n'avais pas la bonne syntax au départ.

Peut-être peux-tu confirmer au cas où d'autres seraient face à ce problème ? 

Merci !

**Comment by laem** [comment]
C'est bien ça :) 

Tu as vu la documention sur publi.codes ? 
On est en train de l'améliorer :)

**Comment by Clemog** [comment]
Yes merci ! Ça marche ! :)
