### ISSUE TITLE
Alimentation; impact potager et poulailler familial

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#755]
Quid du gain CO2 sur les repas préparés à partir d'un potager familial? environ 80kg d'oeufs produits par an n'est ce pas un gain de 80*2,5 kg CO2 soit environ 200 kg de gain CO2 à déduire sur l'alimentation? c'est loin d'être négligeable...

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Gestes Climat se veut être un calculateur grand public et facile d'utilisation. En ce sens, nous essayons de limiter le nombre de questions aux plus significatives (en terme d'impact carbone) et nous ne pouvons malheureusement pas prendre en compte les spécificités de chacun. Qui plus est afin de répondre à cette question particulière, il faudrait poser d'autres questions comme le mode d'alimentation des poules.
