### ISSUE TITLE
mon petit déjeuner

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#756]
un bol de Ricoré (pas top ! je passerai bientôt à plus simple), un jus de pomme local, une pomme bio, du fromage blanc de chèvre - si possible frais de chez ma voisine, des noix de chez moi

**Comment by Benjamin-Boisserie-ABC** [comment]
Nous travaillons à l'amélioration des choix de petit déjeuner #185 #453 et nous prenons en compte votre retour. Néanmoins, Nos Geste Climat étant un outil grand public ayant pour but d'engager le plus grand nombre d'utilisateurs à la simulation de leur empreinte carbone, nous ne pourrons pas prendre en compte les multitudes de possibilités qui existent.
