### ISSUE TITLE
Questions voiture

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#758]
Lorsque que j'indique que je n'ai pas de voiture individuelle, le questionnaire me pose quand même les questions en rapport (si elle est électrique...).

**Comment by Benjamin-Boisserie-ABC** [comment]
Lié au fait que des km parcourus ont été renseignés. C'est normal. Renseigner alors les caractéristiques d'une voiture "moyenne" que vous avez utilisé (même si ce n'est pas la votre)
