### ISSUE TITLE
Déplacement en vélo

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#759]
Je me déplace beaucoup en vélo ce n'est pas pris en compte dans le programme (5200 km /an dont 1500 km pour les petits déplacements utilitaires et 9000 km en voiture), donc pas de transports en commun en ville seulement quelques voyages en bus longues distances

**Comment by bertrandgorge** [comment]
Il me semble qu'en première estimation, si on fait du vélo (mon cas), alors c'est des km qu'on ne roule pas en voiture. Le calculateur pourrait le dire, mais l'objectif c'est d'identifier les facteurs d'émission, pas les facteur de non émission. Techniquement, rouler à vélo ou ne pas rouler c'est pareil (à l'énergie grise de la fabrication du vélo près).
