### ISSUE TITLE
Empreinte numérique

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#761]
Au delà du hardware il manque une forte part de conso relative au flux de données.
> streaming
> emails
> logiciel à fort échange de données (jeux etc...)

**Comment by laem** [comment]
Merci pour votre retour. 

C'est bien pris en compte dans la question "combien de temps sur internet".

Ici : https://github.com/betagouv/ecolab-data/blob/master/data/numérique.yaml#L34

Au sujet du gros volume de données : il n'y a pas consensus aujourd'hui sur l'ordre de grandeur de l'empreinte énergétique de la transmission d'1go de données. Nous allons donc rester sur cette question jusqu'à obtenir de nouvelles informations plus solides.
