### ISSUE TITLE
Habite en fourgon aménagé ? 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#762]
Je ne chauffe pas. Mange exclusivement Bio Local si possible. Mais je déplace ma maison !

**Comment by 945fc41467** [comment]
Le questionnaire demande le nombre de kilomètres parcourus par an. Donc normalement c'est comptabilisé. Bio local, c'est un peu plus compliqué que ça. Un truc cultivé sous serre chauffée (bon, interdit en bio depuis peu) émet plus que le même machin importé cultivé sous serre passive ou en pleine terre. Une viande bio locale, émet plus qu'un nombre équivalent de kalories en blés importés et cultivés en intensif.

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant le bio voir la F.A.Q
Concernant le sujet du fourgon aménagé vous pouvez en effet renseigner les km parcourus. De plus voir #287
