### ISSUE TITLE
 Vélo ou deux roues

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#763]
Dans la partie transports, vous demandez l'usage d'une voiture, l'utilisation des transports en commun et du train, mais absolument l'utilisation du vélo. Pour ma part je n'utilise pas les métro/bus car je me déplace en vélo pour aller travailler (3000 km / an), aucune rubrique n'aborde ce point dans les transports.

**Comment by bertrandgorge** [comment]
dup du #759

**Comment by laem** [comment]
Merci Bertrand :)
