### ISSUE TITLE
Ajout d'une question sur l'équipement en climatisation

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#765]
Il serait intéressant d'ajouter une rubrique pour demander si le logement est équipé d'une climatisation car c'est un dispositif qui impacte fortement le bilan carbone.

**Comment by Benjamin-Boisserie-ABC** [comment]
La consommation électrique de la climatisation est prise en compte dans la consommation du logement. Concernant les fuites de fluides frigorigènes (même si ils ont un fort pouvoir réchauffant) je ne sais pas si c'est un sujet.
