### ISSUE TITLE
Comptabilisation des repas

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#766]
Bonjour,
Dans le comptage des repas, vous obligez à inscrire au moins 14 repas par semaine. Or, de plus en plus de gens suivent tout au long de l'année un rythme de jeûne intermittent, c'est-à-dire 1 seul repas par jour. Donc vous devriez autoriser un minimum de 7 repas hebdomadaires, voire même 6 pour tenir compte des périodes de jeûne...
Merci.

**Comment by bertrandgorge** [comment]
Quel pourcentage de la population selon vous ? Si l'application devient trop complexe, on perd l'intérêt. Perso je pense qu'il faut être prudent et viser un fonctionnement optimal pour le 80%, quitte à ce que ce ne soit pas parfait pour le reste - tant que l'erreur reste marginale.

**Comment by Benjamin-Boisserie-ABC** [comment]
D'accord avec @bertrandgorge
De plus il me semble que l'outil demande de renseigner 14 repas mais que l'on peut tout de même en valider moins.
@laem tu confirmes ?
