### ISSUE TITLE
Facteur Logement 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#768]
Pouvez vous expliquer le coefficient 17,5 kgCO2e / m² ? 
Ce chiffre devrait dépendre 
de l'année de construction 
et du type de construction , voire de l'age de la maison .
s'il s'agit d'une empreinte carbone de la construction ? 
Merci de votre éclairage;

**Comment by laem** [comment]
Voir #111 et #735
merci pour le retour
