### ISSUE TITLE
achats neufs vestimentaires

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#769]
bonjour, concernant les achats neufs et notamment de vetements, il n'y a pas moyen de preciser (comme pour l'alimentaire) qu'ils sont produits en france ou avec le label oekotex,... peut-etre que ça n'a pas d'incidence ou trop peu sur la consommation de co2?

**Comment by Benjamin-Boisserie-ABC** [comment]
Question traitée dans la F.A.Q
