### ISSUE TITLE
Calcul des GES des déchets

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#771]
Je ne comprends pas le calcul de base dans https://nosgestesclimat.fr/documentation/alimentation/d%C3%A9chets/base 

193×Facteur carbone CO2 3,67 = 707,67

Car dans la référence, https://jancovici.com/changement-climatique/les-ges-et-nous/combien-de-gaz-a-effet-de-serre-dans-notre-poubelle/
le chiffre de 193 est déjà l'emission EqCo2 annuel de la poubelle. Pourquoi le multiplier par 3,67 ??

**Comment by laem** [comment]
Le lien mentionne un équivalent carbone, pas CO2, comme expliqué en détail sur votre 1er lien. Si vous avez d'autres infos, n'hésitez pas.
