### ISSUE TITLE
aller au travail en vélo

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#774]
Bonjour
une recommandation qui m'est faite est d'aller au travail en transport en commun. 
Or je vais au travail tous les jours en vélo (électrique), et cela n'est pas pris en compte. Ou alors le bus est plus écolo que le vélo... ??
C'est dommage, ça ne fait pas sérieux et laisse à penser que les recommandations sont bancales... J'espère que non dans l'ensemble ! ;-)
Merci

**Comment by bertrandgorge** [comment]
dup du #759

**Comment by Benjamin-Boisserie-ABC** [comment]
Un travail est en cours pour améliorer le volet "passage à l'action" et les recommandations que nous donnons. Cela passe pas une question sur le mode de déplacement pour se rendre au travail.
Concernant la prise en compte du vélo, voir #813
