### ISSUE TITLE
Bug amortissement voiture ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#783]
Votre calcul de l'amortissement de la voiture est faux, 9 ans c'est pas la durée de vie mais l'âge moyen du parc auto. Du coup dans vos calculs pour la moyenne des français vous avez un facteur quasi égal à 2 en trop.

**Comment by laem** [comment]
Voir https://twitter.com/RDubouil/status/1336612321414828032

**Comment by Petbaxe** [comment]
C'est comme confondre âge moyen des français (environ 45 ans) et espérance de vie des français (environ 80 ans).
Voici cette source sur l'âge moyen des voitures partant à la casse :
https://www.largus.fr/actualite-automobile/le-top-15-des-voitures-envoyees-a-la-casse-10348407.html
Le chiffre est de 19 ans et il est certainement conservatif puisqu'il ne tient pas compte des voitures qui ne finissent pas leur vie en France mais à l'étranger où elles roulent encore longtemps (Afrique, Pays de l'Est, etc.).
Je pense que prendre 20 ans de durée de vie parait raisonnable.
Cordialement
