### ISSUE TITLE
Emissions d'un logement mal isolé à attribuer au propriétaire ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#791]
Quand on est locataire et non propriétaire, il n'est pas forcément possible de faire des travaux d'isolation, exemple la crise du logement en Ile de France est grande, les loyers très élevés et de nombreux logements sont des passoirs thermiques et certains propriétaires sont plutôt des marchants de sommeil qui profitent de la situation. Est-il possible de prendre en compte le fait que bien souvent les locataires n'ont pas de pouvoir face aux propriétaires dans vos calculs en ajoutant une question sur si on est locataire ou propriétaire pour donner une meilleures perspectives. Les locataires n'ont pas tous les moyens d'avoir un logement décent et à base consommation d'énergie. De plus pour les propriétaires, il serait bien je pense d'ajouter une question sur le nombres de propriétés qu'il possède et leur consommation en énergie.

**Comment by 945fc41467** [comment]
je plussoie

**Comment by laem** [comment]
Bonjour, merci pour votre remarque, elle me semble très pertinente. 

Pour l'instant, nous considérons l'empreinte de la *consommation*. C'est une vision comptable qui n'est en aucun cas la seule possible ou la meilleure. Je la résumé ainsi : 

> si je suis locataire d'un logement mal isolé, incapable d'acheter un autre logement, la responsabilité de ces émissions incombe plutôt au propriétaire qui lui a les moyens de faire ces travaux

Il me semble compliqué à ce stade de changer notre méthode comptable, notamment parce qu'il faudrait alors remettre en question l'attribution des émissions de chaque achat. Le propriétaire d'un logement loué peut être assimilé au loueur d'une voiture (soit la personne morale, soit les personnes physiques qui sont propriétaires de cette entreprise, qui se verraient alors attribuer les émissions de leurs clients. On pourrait même imaginer une comptabilité partagée. 

Mais nous pouvons bien sûr y réfléchir :)

**Comment by Benjamin-Boisserie-ABC** [comment]
Je suis d'accord avec @laem sur l'approche consommation et sur la pertinence de cette dernière.
Je pense que l'aspect locataire/propriétaire et les moyens d'actions associés doivent être abordés dans le volet "passage à l'action" en faisant passer le message que le levier d'action sur l'isolement du logement se situe du côté du propriétaire. Il n'en reste pas moins que le locataire (un peu malgré lui je le conçois) à participé à émettre des émissions de gaz à effet de serre
