### ISSUE TITLE
Mode rural ? Maison bois ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#792]
Il n'est pas demandé dans votre enquête si la personne habite en ville ou en campagne. Ce qui devient significatif sur les questions telles que la mobilité (voiture plutôt que transports en commun, ou encore le choix d'un chauffage principal au bois, plutôt qu'autre chose).

**Comment by laem** [comment]
Le simulateur a pour objectif de mesurer les consommations et l'empreinte en conséquence, de chacun. Le fait de vivre en zone rurale peut augmenter ces consommations (et en diminuer d'autres), mais notre role n'est pas de l'excuser d'une quelconque manière.
