### ISSUE TITLE
passer à l'action: propositions en décalage avec la simulation

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#794]
bien que je ne me rende pas en transport ou en voiture à mon travail une proposition d'action à l'issue de la simulation est d'aller au travail en co-voiturage (les kilomètres que j'ai déclarés faire en voiture sont fait en moyenne avec 3 personnes.)
de plus j'ai déclaré ne pas prendre l'avion, et une action proposée est de prendre le train plutôt que l'avion.

**Comment by 945fc41467** [comment]
Idem

**Comment by Benjamin-Boisserie-ABC** [comment]
C'est un retour déjà identifié et nous avons conscience qu'il est nécessaire d'améliorer le volet "passage à l'action" en améliorant les propositions d'actions aux cas particuliers de chacun
