### ISSUE TITLE
Pouvoir dire : pas de téléphone mobile

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#798]
Dans numérique, il n'y a pas l'option "pas de téléphone mobile"

**Comment by laem** [comment]
C'est vrai, on a fait le choix d'éviter de poser une question en plus, vu que + de 90% de gens en ont.

C'est noté.

**Comment by Benjamin-Boisserie-ABC** [comment]
Problématique résolue par #871 qui considère notamment que pas de téléphone mobile se traduit souvent par un téléphone fixe
