### ISSUE TITLE
Utiisation du vélo

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#799]
J'ai été assez surpris de ne pas voir l'utilisation du vélo dans les recommandations de réduction des émissions de GES pour les transports. En effet, les recommandations dans la catégorie proposent seulement d'avoir recours aux transports en commun ou au covoiturage pour réduire l'empreinte de sa voiture. 
J'utilise déjà un vélo pour la majorité de mes déplacements notamment pour aller au travail, et ma voiture ne me sert que quand je n'ai "pas le choix". 
Ici, le calculateur me propose d'aller au travail "en utilisant les transports en commun", ce qui reviendrait à... augmenter mon empreinte carbone! 
C'est une subtilité, certes, mais il est dommage de ne pas encourager cette solution.

**Comment by Benjamin-Boisserie-ABC** [comment]
Le volet "passage à l'action" est cours de développement/amélioration car il est largement incomplet. Ces problèmes de non adéquation avec le profil de l'utilisateur sont déjà identifiés
