### ISSUE TITLE
Quantité de repas par semaine

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#803]
Bonjour,
Je ne consomme qu'un repas par jour. Soit 7 par semaine. 
Votre interface ne me permet pas de valider ce choix, m'imposant d'enregistrer 14 repas par semaine. 
Je ne peux donc pas poursuivre le test. 
Dommage.

**Comment by Benjamin-Boisserie-ABC** [comment]
L'outil demande 14 repas par semaine (via un message indiquant le nombre qui doit encore être renseigné) mais il est possible de valider la question en n'en renseignant que 7
