### ISSUE TITLE
Je n'ai pas de portable et je me déplace (surtout) à vélo

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#804]
Bravo pour votre démarche et outil.
2 observations toutefois: l'absence de téléphone portable et le déplacement en vélo ne sont pas envisagés (il m'est conseillé de prendre les transports en commun ou le covoiturage: j'ai une voiture pour loisirs et utilitaires).

**Comment by avenirclimatique** [comment]
Pour admin : Ajouter le label "fiche action"
