### ISSUE TITLE
Recommandation covoiturage alors que je n'ai pas de voiturr

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#808]
Bonjour, 

Merci pour cette simulation particulièrement intéressante...il y a encore du chemin à parcourir de mon côté. Cependant je m'interroge, j'ai effectivement renseigné que je parcours des kms en voiture mais que je ne possède pas de voiture, et que je vais au travail en transports en commun. Or, on me recommande de faire du covoiturage pour aller au travail et cela représente 3% de mon total.. est ce normal ?  Merci encore pour votre travail.

**Comment by Benjamin-Boisserie-ABC** [comment]
Le volet "passage à l'action" est actuellement très incomplet et nous œuvrons à son développement/amélioration afin de coller au mieux à la réalité des profils des utilisateurs. 
Les problèmes que vous nous remontez sont déjà identifiés
