### ISSUE TITLE
Remarque sur la rubrique "transports"

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#809]
Bonjour,
Cet outil est intéressant mais dans la rubrique "transports" je trouve dommage qu'on ne puisse pas mentionner l'utilisation quotidienne du vélo, alors qu'il y a des questions sur l'usage de la voiture et des transports en commun. 
Merci,
Cordialement,

**Comment by Minigerbox** [comment]
Bonjour,
Je suis d'accord. Pour moi, il faudrait pouvoir différencier l'usage quotidien de l'usage occasionnel.
Par exemple, je me déplace quotidiennement à pieds ou en vélo. Mais j'utilise ma voiture pour des grands trajets quand on va voir notre famille à l'autre bout de la France. A quatre et chargés, ça reste malheureusement encore trop rentable par rapport au train...
Il faudrait pouvoir préciser cette différence car, même si ça n'influe pas sur mon bilan climat (j'indique quand même un nombre de km important réalisés en voiture), cela pourrait donner plus de de pertinence aux pistes d'actions que vous proposez. Par exemple, actuellement, je ne me retrouve pas dans les propositions de faire du covoiturage ou de prendre les transports en commun pour aller au travail, vu que je prends mon vélo.
Merci !

**Comment by laem** [comment]
Nous ajoutons une question vélo, même si elle n'a aucune conséquence. Vous pouvez renseigner vos km de voiture vacance dans la question voiture.
