### ISSUE TITLE
Reset et améliorations

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#810]
Bonjour, 

J'ai copier/coller le lien de la plateforme pour l'envoyer à un ami, mais, étonnement, même en envoyant le lien générique, cela renvoie sur mon bilan...

Aussi, je trouve dommage que les mobilités douces soient écartées (vélo) tout comme la fourniture d'énergies renouvelables (gaz et électricité). 

Enfin, sur l'alimentation (qui apparait comme le plus gros poste), je trouve la définition des menus pas très précise (le fromage apparait plusieurs fois) et on ne comprend pas du premier coup sur combien de repas on doit s'exprimer...

**Comment by laem** [comment]
Pour l'énergie "verte", voir la FAQ https://nosgestesclimat.fr/contribuer
