### ISSUE TITLE
Émission Ceq bus constaté dans les résultats alors que déclare ne pas utiliser de bus

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#814]
Bonjour,
Je remarque dans mes résultats que j'émets 310,4 kgC/an alors que j'ai déclaré ne pas utiliser de bus. Pouvez-vous m'expliquer le calcul ? prise en compte des services de navette intégré dans les aéroports puisque je déclare utiliser l'avion ??
Merci par avance pour votre retour, et vous remerciant pour la qualité de cet outil !

**Comment by laem** [comment]
Ce qui correspond à la valeur par défaut de notre calcul pour le bus : https://nosgestesclimat.fr/documentation/transport/bus

**Comment by laem** [comment]
Je suspecte que vous avez répondu "je ne sais pas" à la question sur le bus. Normalement, si vous répondez "0", les 310kgCO2e/an passeront à 0.

Je vous laisse vérifier ici https://nosgestesclimat.fr/simulateur/transport/bus

**Comment by laem** [comment]
Je ferme ce ticket, mais n'hésitez pas à le rouvrir si vous avez de nouveaux éléments.
