### ISSUE TITLE
Question 1 sur le petit déjeuner 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#817]
Pour ma part je mange un petit-déjeuner à base de fruits et de noix (banane, avec fruits de saisons, huile de lin, amandes, noisettes, noix, sésame, jus de citron), sans laitage et sans gluten qui ne correspond pas du tout au proposition

**Comment by Benjamin-Boisserie-ABC** [comment]
Nous travaillons à l'amélioration des choix de petit déjeuner #185 et nous prenons en compte votre retour. Néanmoins, Nos Geste Climat étant un outil grand public ayant pour but d'engager le plus grand nombre d'utilisateurs à la simulation de leur empreinte carbone, nous ne pourrons pas prendre en compte les multitudes de possibilités qui existent.
