### ISSUE TITLE
Choix de petits déjeuner + divers

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#818]
Bonjour,
Merci pour ce super outil qui permet de se faire une première idée. J'aurai cependant quelques remarques : 
Lors de ce test, il nous ait proposé 3 types de petits déjeuner : soit viennoiseries pain, soit lait céréales, soit pas de petits déjeuners.
Je connais beaucoup de personnes, moi y compris, qui prenons des petits déjeuners salés, certes il y a la baguette, mais il y a aussi les oeufs, le fromage, voir la viande. d'autre part, il me semble que café/thé et tisane/chicorée n'ont pas du tout le même impact carbone, tout comme le fait de ne manger que des légumes de saison ou non. De plus, la viande n'est pas différenciées, alors qu'à mon avis un petit producteur en biodynamie avec des animaux qui grandissent dehors et qui produit ses propres céréales est moins impactant niveau climat que les grands éleveurs où les betes ne sortent pas... Peut être aussi donner la possibilité d'enregistrer nos résultats, comme il était possible de le faire autrefois.

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant le petit-déjeuner, nous travaillons à l'amélioration des choix de petit déjeuner #185 et nous prenons en compte votre retour. Néanmoins, Nos Geste Climat étant un outil grand public ayant pour but d'engager le plus grand nombre d'utilisateurs à la simulation de leur empreinte carbone, nous ne pourrons pas prendre en compte les multitudes de possibilités qui existent.
Concernant l'alimentation locale, cette question est traitée dans la F.A.Q. Elle ne se résume malheureusement pas à un simple calcul de distance
Concernant l'impact d'une alimentation de saison/hors-saison, nous cherchons à prendre en compte cette info.
Concernant l'impact de la viande et des modes d'élevages, votre remarque est pertinente mais nous sommes aussi contraint par le manque de données fiables et validées.
Concernant l'enregistrement des résultats, c'est un retour qui nous a déjà été fait et dont nous avons pris note.
