### ISSUE TITLE
Retours

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#82]
Bonjour, quelques retours : 
 - alimentation : viande 1 fois / jour : on ne sait pas quel est le type de viande
 - logement : pourquoi ne pas demander le DPE si on ne connait pas ses factures ?
 - numérique : comment peut on connaitre la taille de son smartphone en pouces ?
 - transport : pas de question sur le vélo, pourquoi ? (le train aussi émet peu de CO2, idem métro...). Important d'ajouter le vélo quitte à indiquer que c'est presque 0 CO2

**Comment by Benjamin-Boisserie-ABC** [comment]
Mode expert alimentation : n'est pas la priorité 
logement : DPE trop compliqué 
Numérique : prise en compte de la remarque sur la taille du smartphone (essayer de mettre des noms de modèle)
Transport : sur le vélo voir #74 et l'explication à donner sur pourquoi on ne pose pas de question sur le vélo
