### ISSUE TITLE
Bug avion ?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#820]
A une première question j'ai répondu que je ne prenais jamais l'avion (ou que je faisais 0 km en avion). Ensuite, on me suggère une action qui consiste à privilégier le train par rapport à l'avion. Mais moins que zéro c'est impossible, non ? Un bug ou bien ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Le volet "passage à l'action" est incomplet sur le fond comme sur la forme. Les actions proposées ne collent pas parfaitement au profile de l'utilisateur. Nous en avons connaissance et nous œuvrons au développement/amélioration de ce volet. Néanmoins, si vous avez renseigné "non" à la question "prenez-vous l'avion ?" les actions n'auraient pas dû s'afficher. Peut être avez vous renseigné "oui" puis une distance de 0 km auquel cas le test portant sur la question "prenez-vous l'avion" les actions sur l'aviation se sont affichées et ce même si vous avez renseigné une distance parcourue de 0 km
