### ISSUE TITLE
Menu type

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#821]
Pour le menu type d'une semaine, je consomme en effet 9 repas de viande par semaine, mais cuisinant à la chinoise, on émince une même pièce de viande pour plusieurs repas. Il faudrait pouvoir comptabilisé en quantité de viande totale. Parce je suis sûr que mon bilan alimentaire est meilleur que celui indiqué.

**Comment by Benjamin-Boisserie-ABC** [comment]
Nos Geste Climat étant un outil grand public ayant pour but d'engager le plus grand nombre d'utilisateurs à la simulation de leur empreinte carbone, nous ne pourrons pas prendre en compte les multitudes de possibilités et l'ensemble des cas particuliers qui existent sans complexifier le modèle. Une approche au poids desservirait la finalité "user friendly" de l'outil
**Ce que vous pouvez faire.**
Les repas à base de viande (et donc les grammages associés) sont détaillés dans les sources du volet alimentation (pour cela cliquer sur l'histogramme alimentation en fin de simulation puis naviguez jusqu'au détail des repas). Vous pouvez donc comparer votre consommation de viande hebdomadaire à celle des repas types et ainsi ajuster le nombre de repas à base de viande que vous renseignez.
