### ISSUE TITLE
Carburant voiture bioéthanol E85

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#824]
Bonjour et d'abord merci pour votre site internet très instructif. 
Concernant les questions sur les transports, je voulais savoir si il était possible de préciser quel carburant est utilisé pour le véhicule personnel.
En effet, de plus en plus de personnes en France ont converti leur voiture pour rouler au bioéthanol (e85) grâce à un boîtier de conversion homologué. Et vu que l'éthanol émet 71% de CO2 en moins que l'essence (https://www.bioethanolcarburant.com/carburant-superethanol-e85/), le calcul des émissions de CO2 lié aux transports est fortement faussé dans ce cas, car on est obligé de choisir "véhicule thermique" à la question sur les voitures sans distinction entre essence et bioéthanol.
Merci

**Comment by Benjamin-Boisserie-ABC** [comment]
La question des carburants en général est traité dans le F.A.Q
Concernant la spécificité du bioéthanol, il n'y a pas de facteurs d'émissions à disposition dans la base carbone. Le jour ou ce dernier sera disponible et ou une différence significative apparaitra (avec un carburant normal) nous les prendrons en compte. En effet, les facteurs d'émissions de la Base Carbone font l'objet d'un consensus technique et s'attache à prendre en compte l'ensemble des impacts sur le cycle de vie.
