### ISSUE TITLE
permetre de ne pas avoir de telephone du tout

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#827]
les jeunes ou encore un certain nombre de personne n'ont aucun telephone ou juste celui de leur box internet, il faut inclure cette possibilité

**Comment by Benjamin-Boisserie-ABC** [comment]
cette question a été modifiée pour aborder la "complexité" du téléphone. Néanmoins, cette question ne donne toujours pas la possibilité de répondre "pas de téléphone mobile" car ne pas avoir de téléphone mobile signifie très certainement avoir un téléphone fixe. C'est pourquoi la question aborde maintenant la complexité du produit (basique, smartphone, etc.)
