### ISSUE TITLE
Un problème sans solution ?

### ISSUE THREAD

**Issue by 945fc41467** [betagouv/ecolab-data#828]
L'objectif pour respecter les engagements de l'accord de Paris et de 2T de CO2 par an et par personne.
En mangeant végétalien, n'ayant aucun appareil électronique, vivant à 3 dans un 9m2 chauffé ni au fioul, ni au gaz, parcourant 0km en bus, voiture, avion, train, etc.le simulateur atteint tout juste 2T. Est-ce que cela signifie que cet objectif est inatteignable ?

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, à l'heure actuelle il est impossible de passer en dessous des 2 tonnes (que l'on vise en 2050 et pas tout de suite, il ne faut pas l'oublier). Rien que l'impact carbone des services publics représente plus de la moitié des 2 tonnes.
C'est là tout l’enjeu de la transition au sens large. Induire des changements de comportements à l'échelle de l'individu mais aussi prendre conscience que la réduction globale de nos émissions (i.e. à l'échelle nationale) passera par des changements structurels profonds. Ces derniers ne peuvent se faire sans la participation des citoyens mais loin de nous de vouloir leur faire porter l'ensemble du poids de la transition. Ils ont une part à jouer dans la transformation de notre société vers une alternative bas carbone. Elle est nécessaire mais malheureusement pas suffisante.
Pour approfondir : http://www.carbone4.com/wp-content/uploads/2019/06/Publication-Carbone-4-Faire-sa-part-pouvoir-responsabilite-climat.pdf
Lié à #278
