### ISSUE TITLE
valeur en kWh du m3 de buches

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#830]
Pourquoi ne présentez vous pas la consommation de buches -chauffage par le volume en m3 (stères). Il faudrait encore entendre un stère moyen à 800kg. Wikipédia donne environ 4 kWh par kg brut. Ma conso annuelle voisine 1,5 stère pour 50m2 d'habitation. Le calcul me donne donc 4 kwh*1,5 m3*800 kg/m3= 4800kWh. Lesquels produisent 0.018 kg CO2/kWh soit 86.4kg CO2.

**Comment by Benjamin-Boisserie-ABC** [comment]
Remarque déjà prise en compte. Voir #867
