### ISSUE TITLE
vos suggestions sont nulles

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#831]
Pour réduire mon empreinte carbone, votre outil me suggère de réduire de 1deg mon chauffage alors que nous n'avons que 20° chez nous, devenir végétarien, etc. Cet outil ne sert à rien. La solution est de vivre comme l'homme de Neandertal... il chassait et mangeait de la viande et personne ne lui le reprochait !!!

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant le volet "passage à l'action" nous le savons incomplet et mal adapté aux profils des utilisateurs. Il est en cours de développement/amélioration.
Concernant, l'objectif 2 tonnes à atteindre, il est en effet à l'heure actuelle quasi impossible de passer en dessous des 2 tonnes (que l'on vise en 2050 et pas tout de suite, il ne faut pas l'oublier). Rien que l'impact carbone des services publics représente plus de la moitié des 2 tonnes.
En effet, c'est là tout l’enjeu de la transition au sens large. Induire des changements de comportements à l'échelle de l'individu mais aussi prendre conscience que la réduction globale de nos émissions (i.e. à l'échelle nationale) passera par des changements structurels profonds. Ces derniers ne peuvent se faire sans la participation des citoyens mais loin de nous de vouloir leur faire porter l'ensemble du poids de la transition. Ils ont une part à jouer dans la transformation de notre société vers une alternative bas carbone. Elle est nécessaire mais malheureusement pas suffisante.
Pour approfondir : http://www.carbone4.com/wp-content/uploads/2019/06/Publication-Carbone-4-Faire-sa-part-pouvoir-responsabilite-climat.pdf
Lié à #278
