### ISSUE TITLE
Utilisation du carburant pour le véhicule 

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#832]
J'utilise une voiture de plus de vingt ans, je roule à l'éthanol. Mon empreinte carbone est moindre ?

**Comment by Benjamin-Boisserie-ABC** [comment]
L'impact carbone de la construction a été (largement) amortie. Concernant le carburant, la question est traitée dans le F.A.Q
Concernant la spécificité du bioéthanol, il n'y a pas de facteurs d'émissions à disposition dans la base carbone. Le jour ou ce dernier sera disponible et ou une différence significative apparaitra (avec un carburant normal) nous le prendrons en compte. En effet, les facteurs d'émissions de la Base Carbone font l'objet d'un consensus technique et s'attache à prendre en compte l'ensemble des impacts sur le cycle de vie, en commençant par l'affectation des sols, point critiquable (à mon avis mais peut être que je me trompe) au sujet du bioéthanol.
