### ISSUE TITLE
renseigner une consommation de fioul en litres plutot qu'en kWh

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#833]
Pour le chauffage de la maison, la question porte sur une consommation en kWh, or, il est plus aisé (et plus compréhensible) de renseigner une consommation en litres. Le rapport entre les 2 valeurs est de 10, ce qui peut entrainer une erreur non négligeable.

**Comment by laem** [comment]
Merci pour le retour ! C'est un peu la même remarque qui nous a été faite sur le chauffage au bois, qui se mesure plutôt en stères qu'en kWh. On est en train de corriger ça dans #811. On va enchainer avec le fioul :)

**Comment by Benjamin-Boisserie-ABC** [comment]
En lien aussi avec #867
