### ISSUE TITLE
Pas de question sur le vélo

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#835]
Pourquoi pas de question sur les transports en vélo ? je fais environ 250 km par mois pour aller travailler en vélo; pourquoi, n'est -ce pas pris en compte ?
Merci

**Comment by laem** [comment]
Bonjour, tout simplement parce que son empreinte est nulle ou presque. Mais nous considérons l'option de l'ajouter comme question rhétorique, voir notamment #813.
