### ISSUE TITLE
transports : empreinte carbone de la construction

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#841]
Dans les empreintes carbone du transport, il manque vraisemblablement les couts de construction, pour un véhicule électrique l'empreinte co2 de la construction se rentabiliserai autour de 40000 km pour un véhicule, personnel, de petite taille, entre les versions thermiques et électrique par exemple.

Il manque également le transport par camions qui n'est pas individualisé

**Comment by laem** [comment]
Bonjour, votre retour s'applique à nosgestesclimat.fr ou à ecolab.ademe.fr/apps/transport ? Dans le 1er cas, la construction est bien prise en compte, même si largement améliorable.

> Il manque également le transport par camions qui n'est pas individualisé

Transport de quoi par camion ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Je clos le sujet car : 
- comme tu le dis l'impact de la construction est bien pris en compte dans Nos gestes Climat
- le transport par camion de tout type de produit (alimentaire, biens d'équipement, etc.) est pris en compte dans les périmètres des facteurs d'émissions que l'on utilise. La personne voulais je pense parler "d'énergie grise" sans savoir qu'elle était déjà prise en compte
