### ISSUE TITLE
viande rouge,lait

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#845]
je crois  que la  viande rouge  a un profil  trop negatif   .les troupeaux  de betes
a viande  que je vois  autour d'isigny  sur mer jusqu'en decembre  ont sans doute  un .profil tres inferieur  aux feed-lot  du Texas .
pour le lait   une vache  qui produit 9000 l ne rumine  pas plus qu'ne à 3000  l

**Comment by gaelg** [comment]
On peut retrouver ici les données pour la France : https://www.agribalyse.fr/documentation/acces-donnees
Il me semble que ça correspond à l'ordre de grandeur utilisé ici.
Malheureusement, les ruminants élevés en France semblent en moyenne très émetteurs, malgré l'alimentation à l'herbe une partie de l'année (sans doute à cause du méthane des rots, qu'on a tendance à sous-évaluer).

**Comment by laem** [comment]
Merci @gaelg pour le référence. Notre calcul est transparent, affiché ici : https://nosgestesclimat.fr/documentation/alimentation/plats/viande-2
Il est basé sur FoodGES, qu'on peut voir comme l’ancêtre d'agribalyse, à mettre à jour, mais l'ordre de grandeur est là. Sur nosgestesclimat, nous ne produisons pas des ACV, nous en articulons les résultats. Je ferme donc.
