### ISSUE TITLE
remarque importante

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#846]
La culture en bio ne nécessite pas plus de terre que le conventionnel, confère les X études produites par la ferme du Bec Hellouin, une référence pour nombre d'agriculteurs bio.

**Comment by Benjamin-Boisserie-ABC** [comment]
Il existe un grand nombre de type d'agriculture bio. Il est tout à fait possible que certaines fermes comme la ferme du Bec Hellouin, centre de référence de permaculture, mettent en avant une affectation du sol similaire à l'agriculture conventionnelle (voir même meilleure). Cependant, la permaculture n'est pas, à l'heure actuelle, la forme de culture bio la plus répandue, sans compter la très grande présence de produits bio venant de l’extérieur.
Prendre en compte, l'ensemble des possibilités (quant aux méthodes de production), s'avérerait complexe à la fois d'un poids de vue de la comptabilité carbone et d'un point de vue utilisateur. Ce dernier devrait alors renseigner et répondre à de nombreuses questions, ce qui diminuerait la portée grand public et l'objectif de Nos Gestes Climat d'engager le plus grand nombre à la simulation.
Vous pouvez tout de même nous faire vos propositions pour réussir à prendre en compte et poser la question du bio (essentielle surtout pour d'autres enjeux que le critère carbone - mais c'est mon avis perso). On vous explique comment ici : https://github.com/betagouv/ecolab-data/blob/master/CONTRIBUTING.md
