### ISSUE TITLE
Corriger le FE TV !

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#848]
Dans le calcul de l'empreinte d'un ordinateur, il est considéré 222 kgCO2e pour un écran de 21 pouces et 63 kgCO2e pour une TV de 40 pouces. Je m'attends à une empreinte TV supérieure à celle d'un écran.

**Comment by Benjamin-Boisserie-ABC** [comment]
En effet, il y a une erreur sur le FE de la TV qui devrait être de 371 kgCO2 pour un écran 40-49 pouces tel que le donne la Base Carbone.

**Comment by laem** [comment]
Bien vu, c'était sûrement une erreur de copie, probablement de moi :/
