### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#851]
malgré ma réponse le questionnaire n avance plus à "Utilisez-vous un home cinéma ?" et aussi je n ai pas de tél portable mais il n y a pas de réponse qui le spécifie

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant le téléphone portable nous avons changé l'angle de la question. Voir #871 
De plus, nous considérons que ne pas avoir de téléphone portable se traduit souvent par la présence d'un téléphone fixe. 
Je ferme ce retour n'ayant pas plus de précisions sur le bug
