### ISSUE TITLE
Facteur construction 17.5kgCO2e/m2

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#852]
Bonjour, j'aurais aimé savoir quels étaient les hypothèses du facteur construction de 17.5kgCO2e/m2 ? Cela parait assez bas. 
Merci d'avance

**Comment by Benjamin-Boisserie-ABC** [comment]
Le facteur de construction est issu du facteur d'émission de la Base Carbone "Immeubles de logements collectifs (IC)" donnant  525 kgCO2e/m² SHON. Ce facteur est ensuite divisé par un amortissement de 30 ans. 
Concernant le facteur en lui même nous vous invitons à vous référez directement à la Base Carbone https://www.bilans-ges.ademe.fr/fr/basecarbone et à parcourir la documentation et les hypothèses utilisées pour le construire
