### ISSUE TITLE
Amortissement logement

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#855]
Bonjour,

Contrairement à d'autres postes il ne semble pas y avoir d'amortissement pour les logements : pourquoi ce choix ?
De plus, je suis locataire (en résidence étudiante précisément...), je ne saurais pas trop comment faire mieux que ce qui est proposé mais j'ai un doute quant à la pertinence du résultat sur ce poste dans ce genre de situation.

En tout cas merci beaucoup pour votre travail !

Bien cordialement

**Comment by laem** [comment]
Merci, voir #111
