### ISSUE TITLE
approvisionnement de la nourriture

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#858]
Bonjour, il manque selon moi une question sur le type d'approvisionnement alimentaire : livraison, supermarchés, épicerie vrac.

**Comment by laem** [comment]
Au sujet du vrac : vous avez une question "démarche zéro déchets" qui répond plus ou moins à cela. 
Quand à la livraison vs supermarché, il faudra que l'on creuse les données, je note dans #185
