### ISSUE TITLE
Période facture bois

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#86]
Pour "Pas de facture ? Entrez vos dépenses approximatives par mois" sur la consommation bois ou granulés il peut-être plus simple de donner un chiffre annuel. En général les particuliers font une seule commande pour une année ou deux de chauffage.

**Comment by Benjamin-Boisserie-ABC** [comment]
Prise en compte de la remarque : mettre une 2e case pour entrer les dépenses approximatives par an ---> MAIS pas prioritaire
