### ISSUE TITLE
prise en compte avion

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#862]
bonjour, la question sur l'avion est trop floue. Je ne prends pas l'avion tous les ans, mais j'ai fait un tour du monde en avion il y a 3 ans. dans votre test j'ai mis zéro, ca me donne un très bon résultat, que je sais faux. donc je vous suggérer de le lisser sur une plus longue période, par ex 3 ou 5ans, en nombre d'heures de vol. je crois qu'un nombre important de Francais se paie un voyage lointain non annuel, notamment dans les classes moyennes.  Enfin votre citation disant que seulement 10% des Francais prennent l'avion me semble datée, voir les enquêtes nationales qui montrent une démocratisation de l'aérien : https://www.ecologie.gouv.fr/sites/default/files/ENPA_2015_2016.pdf

**Comment by laem** [comment]
Merci pour le retour. Malheureusement, ce point essentiel que vous notez pour l'avion s'applique à ... tout ! Le smartphone, le canapé, la construction de maison, etc. C'est le point essentiel de l'amortissement, qu'on devra traiter avec beaucoup d'attention, voir https://github.com/betagouv/ecolab-data/issues/816

**Comment by laem** [comment]
> votre citation disant que seulement 10% des Francais prennent l'avion me semble datée

Je ne trouve la correction dans votre lien. 

> Enquête Nationale auprès des Passagers Aériens 

C'est une enquête faite dans un aéroport, comment pourrait-elle déterminer la propotion des français prenant l'avion ?
