### ISSUE TITLE
Pourquoi y a t'il un si grand écart entre vos éstimation et ceux de la banque mondiale?

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#863]
J'ai vu recemment sur le site de la banque mondiale que les émissions en tonnes de CO2 équivalent, per capita, sont 4,6 pour 2014.

Comment ca se fait que votre chiffre est plus que le double? 

https://data.worldbank.org/indicator/EN.ATM.CO2E.PC?locations=FR

**Comment by laem** [comment]
> CO2 emissions (metric tons per capita) - France

> Carbon dioxide emissions are those stemming from the burning of fossil fuels and the manufacture of cement. They include carbon dioxide produced during consumption of solid, liquid, and gas fuels and gas flaring.

- Nous parlons de GES, donc de CO2e et pas de CO2
- La banque mondiale n'attribute pas les importatations dans notre empreinte (votre iphone est attribué aux Chinois)
- peut-être d'autres facteurs
