### ISSUE TITLE
Chauffage

### ISSUE THREAD

**Issue by krichtof** [betagouv/ecolab-data#87]
Bonjour l'équipe ecolab.

Bravo pour le boulot. C'est en effet compliqué de changer ses habitudes si l'on ne mesure pas son impact actuel.

Petite remarque sur le chauffage.
J'ai indiqué que j'étais chauffé au gaz. Mais le simulateur me pose ensuite la question si je suis chauffé au fioul, puis au bois. Peut-être envisager une seule question sur la source de chauffage ?

**Comment by laem** [comment]
Merci pour tes contributions :) 

Alors malheureusement, le bois est à ma connaissance utilisé dans un certain nombre de cas comme un appoint. C'est aussi le cas du combo gaz + électricité : gaz en commun dans l'immeuble mais chauffage d'appoint, par exemple pour la salle de bain. 
Il faudrait qu'on mette la main sur des statistiques précises de l'état du parc de chauffage.
