### ISSUE TITLE
les propositions d'actions ne correspondent pas à ma situation

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#870]
le site me conseille covoiturage, prendre le bus pour baisser mon EC de 7 %. je me déplace à pied en train en vélo que ce soit pour aller à mon travail ou mes loisirs. je n'ai pas besoin du bus ni du covoiturage dans ma configuration actuelle quotidienne. j'ai donc répondu que je ne les prenais pas. Je les pratique si besoin en grande ville. Donc il faut répondre oui je prends le bus : sur le mode du principe et non sur la fréquence.

**Comment by laem** [comment]
Merci, c'est noté, on va faire mieux.
