### ISSUE TITLE
Téléphone portable

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#876]
Bonjour,

Bravo pour votre outil.
Je suis en train d'essayer de calculer l'empreinte carbone de mes enfants (j'ai bien noté d'ailleurs qu'une approche foyer était prévue, comment peut-on être informé de la mise en ligne de cette Maj quand elle sera prête ?). Or il n'est pas possible d'indiquer qu'ils n'ont pas de téléphone portable.

**Comment by laem** [comment]
En effet, le calcul n'est pas vraiment prévu pour les enfants, ni pour les familles en général. 

On considère que tout adulte en France a un téléphone portable ou fixe. 

Mais ne vous souciez pas trop de l'empreinte du téléphone, elle est très faible par rapport au reste, de l'ordre de 10kgCO2e/an sur une moyenne de 10 000 :sweat_smile:

**Comment by laem** [comment]
Voir #113
