### ISSUE TITLE
chauffage logement: chauffage via ordures

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#877]
Bonjour,
je voulais calculer mon empreinte carbone maispour mon logement j habite en Suede et mon logement est chauffé (ainsi que l'eau chaude) via la combustion de déchets. C est plus proche de quelle source de chauffage?

et pourquoi le recyclage ou l'achat d'ocasion n'est pas comptabilisé dans les emissions?

**Comment by laem** [comment]
C'est je crois ce qu'on appelle un réseau de chaleur. Malhereusement, ils sont tous différents, voir #872 

>  le recyclage 
Le recyclage a un impact assez faible et difficile à quantifier. Le zéro déchet est lui compté. 

> l'achat d'ocasion n'est pas comptabilisé dans les emissions?

Pour l'instant on ne demande que de renseigner les achats neufs.
