### ISSUE TITLE
boulot à vélo

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#878]
Bonjour,

Dans votre rubrique "boulot" et déplacement, j'ai été surpris de ne pas y voir figuré les déplacements "domicile-travail à vélo".

Également, dans la simulation "ecolab transport", j'ai été surpris de voir qu'au bout de 30 km, le picto vélo avait complétement disparu !

Merci.

**Comment by laem** [comment]
C'est prévu dans #813
