### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#879]
Bonjour ce qui serait sympa c'est de faire varier les montants d'une année sur l'autre or il faut reprendre tout le test c dommage. 
Et je tv les conseils peu pertinents.

**Comment by Benjamin-Boisserie-ABC** [comment]
Le volet "passage à l'action" est très incomplet et ne colle pas aux profils des utilisateurs. C'est pourquoi ce dernier est en phase d'amélioration et de développement.
Concernant la possibilité de comparer une année à l'autre nous réfléchissons à un moyen simple (techniquement) pour garder une traçabilité de ses résultats.
