### ISSUE TITLE
objectif de 2 tonnes et services publics

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#881]
Bonjour et merci pour cet outil simple, pertinent et indispensable.

Mon commentaire porte sur la difficulté d'atteindre la barre des 2 tonnes compte tenu de l'impact des services publics. Ce sujet est très débattu sur les réseaux.

Au delà du simple bilan de mon empreinte actuelle réelle , j'utilise l'outil pour essayer d'atteindre 2 tonnes en testant différents scenarios de modification de mes habitudes. Je me projette donc dans une  situation future "idéale" et "tenable" pour moi. Je trouve trompeur que la barre des services publics reste figée à 1,1 tonnes dans ce cas. 
En effet, on peut raisonnablement penser que les services publics eux aussi vont voir leur impact baisser dans un futur "idéal". 

S'il est impossible de chiffrer précisément cette baisse, il faudrait à minima une mention sur ce point d'attention ("dans la réalité, il est probable que l'empreinte des services publics baisseront si les mesures nécessaires sont prises") et / ou une case à cocher pour activer cette baisse hypothétique de l'empreinte des services publics, par exemple en pourcentages. (-5%, -10%...). 

Merci
JD Bois

**Comment by Benjamin-Boisserie-ABC** [comment]
Concernant le volet "passage à l'action" nous le savons incomplet et mal adapté aux profils des utilisateurs. Il est en cours de développement/amélioration afin de pouvoir proposer aux utilisateurs des pistes concrètes d'actions au lieu d'avoir "à fouiller" comme vous le faites. En tout cas félicitation pour votre implication et pour l'intérêt dont vous faites preuve pour essayer de réduire votre empreinte carbone 
Concernant, l'objectif 2 tonnes à atteindre, il est en effet à l'heure actuelle quasi impossible de passer en dessous des 2 tonnes (que l'on vise en 2050 et pas tout de suite, il ne faut pas l'oublier). Rien que l'impact carbone des services publics représente plus de la moitié des 2 tonnes mais comme vous le dites leur poids carbone est amené à baisser.
C'est là tout l’enjeu de la transition au sens large. Induire des changements de comportements à l'échelle de l'individu mais aussi prendre conscience que la réduction globale de nos émissions (i.e. à l'échelle nationale) passera par des changements structurels profonds. Ces derniers ne peuvent se faire sans la participation des citoyens mais loin de nous de vouloir leur faire porter l'ensemble du poids de la transition. Ils ont une part à jouer dans la transformation de notre société vers une alternative bas carbone. Elle est nécessaire mais malheureusement pas suffisante.
Pour approfondir : http://www.carbone4.com/wp-content/uploads/2019/06/Publication-Carbone-4-Faire-sa-part-pouvoir-responsabilite-climat.pdf
Lié à #278
