### ISSUE TITLE
pas de cout de construction

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#883]
problème j'ai une maison de 1850 rénovée en matériaux biosourcés donc son impact Co2 ne peu pas être celui que vous avez calculé au regard temps de vie/impact construction. de plus elle est uniquement construite en pierres et enduit chaux/terre donc impact beaucoup moins important. il va falloir intégrer la qualité de la construction à votre étalonnage.

**Comment by Benjamin-Boisserie-ABC** [comment]
Se reporter à #816 concernant l'amortissement.
Concernant les méthodes de construction/rénovation, Nos Gestes Climat est un outil Grand Public ayant pour but d’engager le plus grand nombre à la simulation. Nous avons donc fait le choix de limiter les questions aux grands enjeux afin de proposer un outil simple et facilement utilisable. L'impact des différents types de construction est un sujet déjà identifié mais dont la prise en compte de manière facile et intelligible pour l'utilisateur (i.e. sans le surchargé de question) n'est pas chose aisée.

**Comment by laem** [comment]
J'avais fait pas mal de recherches personnelles sur l'empreinte d'une construction biosourcée : https://github.com/laem/futureco-data/issues/38
C'est pas évident, mais des données existent :) Reste à les analyser et intégrer.
