### ISSUE TITLE
Comparer son bilan personnel avec le bilan moyen de manière plus fine

### ISSUE THREAD

**Issue by krichtof** [betagouv/ecolab-data#89]
La dernière page de la simulation affiche le bilan personnel, catégorie par catégorie.
Pour info, ce que j'ai fait ensuite, c'est que j'ai ouvert une nouvelle page pour afficher la 1ere étape du simulateur, et ainsi comparer catégorie par catégorie mon empreinte avec l'empreinte moyenne des français.

Que pensez-vous d'afficher l'empreinte moyenne catégorie par catégorie aussi dans la page finale du bilan ?

**Comment by laem** [comment]
Super idée. On comptait d'ailleurs retravailler cette page qui n'est qu'une v1 assez brute. 
Pour mieux afficher, graphiquement, l'objectif x tonnes (par exemple 12) -> 2 tonnes. 
Peut-être permettre de cliquer sur la ligne "Moyenne france : 11" tonnes pour afficher le graphe correspondant ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Prise en compte de la remarque
