### ISSUE TITLE
Ce serait top de pouvoir personnaliser ces donnees

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#898]
Par exemple, si je ne prends jamais le bus mais fait 5 court et 4 long voyages en avion... mon bilan est sans doute assez different de ce qui est propose.

**Comment by laem** [comment]
Bonjour, je ne comprends pas votre demande. Il est aujourd'hui justement prévu qu'on puisse dire "0 heures de bus" et renseigner des courts et longs voyages en avion.
Je ferme en attendant plus d'infos de votre part, n'hésitez pas à compléter.
