### ISSUE TITLE
Non, le bio n'est pas moins efficace au m² que le conventionnel, et permet au contraire de faire pousser sous des arbres.

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#900]
Suite à ce passage : « production et produits égaux, une culture bio va nécessiter des parcelles agricoles plus grandes, réduisant la taille des forêts et des zones naturelles, zones essentielles à la séquestration du carbone. C’est pourquoi, à l’échelle globale et à quantités consommées égales, on tend à considérer que le bio a « plus d’impact » sur le climat que l’agriculture conventionnelle. »
C'est faux. Il faut déjà prendre en compte que l'agriculture conventionnelle, utilise massivement des produits pétroliers (comme les engrais de synthèse), cela compte également dans le bilan carbone. l'alimentation produit par quantité de pétrole nécessaire à sa production temps de plus à descendre avec le temps, puisqu'il n'y a plus d'insectes pour régénérer les sols et produire de l'alimentation pour les plantes, ni de plantes permettant de les rengréner (comme les plantes azotantes).

D'après les études de l'INRA de 2013 à 2015, à surface égal, la permaculture à un meilleur rendement. Et la permaculture utilise les plantations à étages qui permettent de cumuler par exemple des céréales et légumes sous des arbres fruitiers, en particulier dans l'agroforesterie. Les arbres nourrissent d'avantages les plantes en sous-bois et composent largement le fait d'avoir moins de soleil, et cela réduit les besoin en eau, ce qui est vital.

https://hal.archives-ouvertes.fr/hal-01548676/document

**Comment by laem** [comment]
Bonjour, ce que vous dites est intéressant mais quelle est sa place ici ? Je ferme en attendant mieux.
