### ISSUE TITLE
Numérique : 0 ans --> Infinity

### ISSUE THREAD

**Issue by nicooprat** [betagouv/ecolab-data#91]
Je viens de changer de smartphone : si j'entre "0 ans" comme ancienneté, la barre "numérique" affiche "Infinity" et bien sûr le graphique n'a plus aucun sens ;)

![image](https://user-images.githubusercontent.com/645641/88522008-1174e780-cff6-11ea-8aab-a4197e2affee.png)

**Comment by laem** [comment]
Réglé. Voir #168
