### ISSUE TITLE
m2

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#916]
Et bien,je vis dans 35m2;l'an passé,j'avais mes 2 filles en garde alternée une semaine sur deux,sauf pendant les vacances.Le logement a un double vitrage,un chauffage au sol,et sinon deux radiateurs d'appoint.

**Comment by laem** [comment]
> j'avais mes 2 filles en garde alternée une semaine sur deux,sauf pendant les vacances

Malheureusement nous ne prenons pas encore en compte ces situations complexes. Vous pouvez cependant en faire une moyenne (à la louche) pour trouver le nombre de personnes vivant chez vous (il peut être décimal).

Pour le reste, remplissez vos m² et vos kWh :)
