### ISSUE TITLE
Actions concrètes

### ISSUE THREAD

**Issue by nicooprat** [betagouv/ecolab-data#92]
J'ai repéré cette phrase en fin de simulation :

> Bientôt, des actions concrètes et chiffrées pour réduire votre empreinte.

J'avais commencé un projet en ce sens il y a quelques années, où on liste des actions du quotidien avec une alternative concrète en face : https://www.alterecolo.fr/ / https://github.com/nicooprat/alterecolo

![image](https://user-images.githubusercontent.com/645641/88522341-81836d80-cff6-11ea-8f29-cdad5628a793.png)

Sait-on jamais, si ça peut servir... ;)

**Comment by laem** [comment]
@Benjamin-Boisserie-ABC @martinregner

**Comment by Benjamin-Boisserie-ABC** [comment]
Merci @nicooprat pour votre lien.

Nous en prenons note

Le simulateur s'accompagnera en effet de propositions d'actions à mettre en oeuvre pour l’utilisateur. Ces actions seront adaptées aux réponses de l'utilisateur pour être pertinentes.

Benjamin de l'ABC
