### ISSUE TITLE
Banques

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#933]
Bonjour,
J'aimerais savoir si, quelque part dans vos calculs, vous incluez mon épargne investie par ma banque dans des énergies fossiles.

**Comment by laem** [comment]
Bonjour, non ce n'est pas le cas, ce serait un double comptage. Les énergies fossiles financées sont comptabilisées pour ceux qui les utilisent. C'est un choix de comptabilité qui se défend, les autres aussi :)
