### ISSUE TITLE
Ajouter la possibilité de définir son fournisseur d'électricité et de gaz

### ISSUE THREAD

**Issue by vivpez** [betagouv/ecolab-data#98]
Lorsqu'on renseigne sa consommation d'électricité et de gaz, il faudrait pouvoir renseigner son fournisseur car selon le fournisseur le facteur d'émission est différent.
C'est particulièrement vrai pour le gaz : quand on opte pour un fournisseur de biogaz (comme ilek), le facteur d'émission est divisé par 10 ( http://www.carbone4.com/wp-content/uploads/2019/06/Publication-Carbone-4-biome%CC%81thane-et-climat.pdf  )
ce qui est un levier puissant de décarbonation.
Si l'utilisateur renseigne son fournisseur d'électricité ou de gaz, faire un calcul market-based et sinon se baser sur un calcul country-based.

**Comment by jennpypi** [comment]
Je plussoie. J'ai failli cliquer "non" à la question "votre logement est-il chauffé au gaz", car on ne pouvait pas préciser la provenance de ce gaz (fournisseur "classique" ou biogaz). J'ai quand même cliqué "oui" et du coup ça me plombe mon bilan Logement :(

**Comment by laem** [comment]
Merci pour les retours, je note dans #4
