### ISSUE TITLE
Erreur à l'affichage des résultats

### ISSUE THREAD

**Issue by publicodes** [betagouv/ecolab-data#99]
Bonjour,
J'ai réalisé le questionnaire jusqu'au bout. A partir du volet "numérique", cela a commencé à ne plus bien fonctionner (les jauges ne s'affichaient plus et il était affiché "infinity" comme quantité carbone). J'ai tout de même continué et le résultat final ne s'est pas affiché. Seulement une page complètement blanche.

**Comment by laem** [comment]
Fixed by #169

**Comment by Benjamin-Boisserie-ABC** [comment]
Problème résolu
